import type { ComponentRegistryItem } from '../types'

export const aceternityComponents: ComponentRegistryItem[] = [
  {
    id: 'aceternity-animated-modal',
    name: 'AceternityAnimatedModal',
    displayName: 'Animated Modal',
    source: 'aceternity',
    categories: ['modal', 'animation'],
    tags: ['modal', 'dialog', 'popup', 'animated', 'overlay'],
    description: 'An animated modal dialog with spring transitions, backdrop blur, and smooth open/close animations.',
    previewImage: '',
    props: [
      { name: 'trigger', type: 'string', default: 'Open Modal', required: false, description: 'Text for the trigger button', group: 'content' },
      { name: 'title', type: 'string', default: 'Book your flight today!', required: false, description: 'Modal title', group: 'content' },
      { name: 'content', type: 'string', default: 'Experience the best of air travel...', required: false, description: 'Modal body text', group: 'content' },
      { name: 'image', type: 'image', default: '', required: false, description: 'Image displayed in the modal', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-animated-modal',
    level: 'primitive',
    code: '<AceternityAnimatedModal trigger="Open" title="Hello" content="World" />',
    suggestedWith: ['aceternity-hero-highlight', 'aceternity-spotlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-animated-tabs',
    name: 'AceternityAnimatedTabs',
    displayName: 'Animated Tabs',
    source: 'aceternity',
    categories: ['navigation', 'animation'],
    tags: ['tabs', 'navigation', 'animated', 'content-switcher'],
    description: 'Animated tab navigation with smooth bubble transition indicator and content switching with fade animations.',
    previewImage: '',
    props: [
      { name: 'tabs', type: 'array', required: false, description: 'Array of tab objects with title, value, content, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes for the tab bar', group: 'style' },
      { name: 'containerClassName', type: 'string', required: false, description: 'Additional CSS classes for the container', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-animated-tabs',
    level: 'section',
    code: '<AceternityAnimatedTabs tabs={[{ title: "Tab 1", value: "tab1", content: "Content" }]} />',
    suggestedWith: ['aceternity-bento-grid', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-animated-testimonials',
    name: 'AceternityAnimatedTestimonials',
    displayName: 'Animated Testimonials',
    source: 'aceternity',
    categories: ['testimonial', 'animation'],
    tags: ['testimonials', 'reviews', 'carousel', 'autoplay', 'animated'],
    description: 'Animated testimonial carousel with stacked image transitions, word-by-word text reveal, and autoplay support.',
    previewImage: '',
    props: [
      { name: 'testimonials', type: 'array', required: false, description: 'Array of testimonial objects with quote, name, designation, and src', group: 'content' },
      { name: 'autoplay', type: 'boolean', default: true, required: false, description: 'Enable automatic rotation', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-animated-testimonials',
    level: 'section',
    code: '<AceternityAnimatedTestimonials autoplay={true} />',
    suggestedWith: ['aceternity-infinite-moving-cards', 'aceternity-card-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-animated-tooltip',
    name: 'AceternityAnimatedTooltip',
    displayName: 'Animated Tooltip',
    source: 'aceternity',
    categories: ['other', 'animation'],
    tags: ['tooltip', 'avatar', 'team', 'hover', 'animated'],
    description: 'Row of avatar images with animated spring tooltips that follow cursor movement on hover.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of tooltip items with id, name, designation, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-animated-tooltip',
    level: 'primitive',
    code: '<AceternityAnimatedTooltip items={[{ id: 1, name: "John", designation: "Dev", image: "/img.jpg" }]} />',
    suggestedWith: ['aceternity-floating-dock', 'aceternity-card-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-aurora-background',
    name: 'AceternityAuroraBackground',
    displayName: 'Aurora Background',
    source: 'aceternity',
    categories: ['hero', 'background'],
    tags: ['aurora', 'background', 'gradient', 'hero', 'animated'],
    description: 'Animated aurora borealis gradient background with title, subtitle, and CTA button overlay.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Background lights are cool, you know.', required: false, description: 'Hero title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'A subtle yet beautiful aurora effect...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'ctaText', type: 'string', default: 'Debug Now', required: false, description: 'Call-to-action button text', group: 'content' },
      { name: 'ctaLink', type: 'string', default: '#', required: false, description: 'Call-to-action link URL', group: 'content' },
      { name: 'showRadial', type: 'boolean', default: true, required: false, description: 'Show radial gradient mask', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-aurora-background',
    level: 'section',
    code: '<AceternityAuroraBackground title="Welcome" subtitle="Explore" ctaText="Start" />',
    suggestedWith: ['aceternity-sparkles', 'aceternity-wavy-background'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-background-beams',
    name: 'AceternityBackgroundBeams',
    displayName: 'Background Beams',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['beams', 'background', 'light', 'animated', 'dark'],
    description: 'Dark background with animated vertical and diagonal light beams streaming across the section.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Join the waitlist', required: false, description: 'Title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Be the first to experience...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-background-beams',
    level: 'section',
    code: '<AceternityBackgroundBeams title="Join Us" subtitle="Sign up today" />',
    suggestedWith: ['aceternity-shooting-stars', 'aceternity-spotlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-background-gradient-animation',
    name: 'AceternityBackgroundGradient',
    displayName: 'Background Gradient Animation',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['gradient', 'background', 'animation', 'interactive', 'blobs'],
    description: 'Mesmerizing animated gradient background with morphing color blobs and optional mouse interactivity.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Gradients X Animations', required: false, description: 'Title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'A mesmerizing gradient animation...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'interactive', type: 'boolean', default: true, required: false, description: 'Enable mouse-following gradient', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-background-gradient-animation',
    level: 'section',
    code: '<AceternityBackgroundGradient title="Hello" interactive={true} />',
    suggestedWith: ['aceternity-aurora-background', 'aceternity-wavy-background'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-bento-grid',
    name: 'AceternityBentoGrid',
    displayName: 'Bento Grid',
    source: 'aceternity',
    categories: ['grid', 'layout', 'feature'],
    tags: ['bento', 'grid', 'layout', 'cards', 'features'],
    description: 'Bento-style grid layout with variable column and row spans, staggered entry animations, and hover effects.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of grid items with title, description, icon, colSpan, and rowSpan', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-bento-grid',
    level: 'section',
    code: '<AceternityBentoGrid items={[{ title: "Feature", description: "Description", icon: "🚀" }]} />',
    suggestedWith: ['aceternity-card-hover-effect', 'aceternity-wobble-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-card-hover-effect',
    name: 'AceternityCardHoverEffect',
    displayName: 'Card Hover Effect',
    source: 'aceternity',
    categories: ['card', 'animation'],
    tags: ['cards', 'hover', 'grid', 'animated', 'links'],
    description: 'Grid of cards with a shared animated hover background that follows the cursor between cards.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of card items with title, description, link, and optional icon', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-card-hover-effect',
    level: 'section',
    code: '<AceternityCardHoverEffect items={[{ title: "Card", description: "Desc", link: "#" }]} />',
    suggestedWith: ['aceternity-bento-grid', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-colourful-text',
    name: 'AceternityColourfulText',
    displayName: 'Colourful Text',
    source: 'aceternity',
    categories: ['text', 'animation'],
    tags: ['text', 'colorful', 'rainbow', 'animated', 'typography'],
    description: 'Text with continuously cycling per-character color animation creating a rainbow wave effect.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Colourful Text', required: false, description: 'The text to display', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-colourful-text',
    level: 'primitive',
    code: '<AceternityColourfulText text="Hello World" />',
    suggestedWith: ['aceternity-flip-words', 'aceternity-typewriter-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-compare',
    name: 'AceternityCompare',
    displayName: 'Compare',
    source: 'aceternity',
    categories: ['media', 'other'],
    tags: ['compare', 'slider', 'before-after', 'images', 'interactive'],
    description: 'Before/after image comparison slider with draggable divider handle and labeled overlays.',
    previewImage: '',
    props: [
      { name: 'beforeImage', type: 'image', default: '', required: false, description: 'Before image URL', group: 'content' },
      { name: 'afterImage', type: 'image', default: '', required: false, description: 'After image URL', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-compare',
    level: 'primitive',
    code: '<AceternityCompare beforeImage="/before.jpg" afterImage="/after.jpg" />',
    suggestedWith: ['aceternity-images-slider', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-direction-aware-hover',
    name: 'AceternityDirectionAwareHover',
    displayName: 'Direction Aware Hover',
    source: 'aceternity',
    categories: ['card', 'animation'],
    tags: ['hover', 'direction', 'card', 'image', 'overlay'],
    description: 'Image card with direction-aware hover overlay that slides in from the direction of mouse entry.',
    previewImage: '',
    props: [
      { name: 'image', type: 'image', default: '', required: false, description: 'Card background image', group: 'content' },
      { name: 'title', type: 'string', default: 'Beautiful Product', required: false, description: 'Product title', group: 'content' },
      { name: 'description', type: 'string', default: 'An amazing product...', required: false, description: 'Product description', group: 'content' },
      { name: 'price', type: 'string', default: '$129.99', required: false, description: 'Price label', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-direction-aware-hover',
    level: 'primitive',
    code: '<AceternityDirectionAwareHover image="/product.jpg" title="Product" price="$99" />',
    suggestedWith: ['aceternity-three-d-card', 'aceternity-glare-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-encrypted-text',
    name: 'AceternityEncryptedText',
    displayName: 'Encrypted Text',
    source: 'aceternity',
    categories: ['text', 'effect'],
    tags: ['encrypted', 'scramble', 'text', 'decode', 'hacker'],
    description: 'Matrix-style text scramble effect that decrypts characters one by one, re-triggered on hover.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Encrypted Text Effect', required: false, description: 'Text to display', group: 'content' },
      { name: 'speed', type: 'number', default: 50, required: false, description: 'Scramble speed in milliseconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-encrypted-text',
    level: 'primitive',
    code: '<AceternityEncryptedText text="Secret Message" speed={50} />',
    suggestedWith: ['aceternity-text-generate-effect', 'aceternity-typewriter-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-expandable-cards',
    name: 'AceternityExpandableCards',
    displayName: 'Expandable Cards',
    source: 'aceternity',
    categories: ['card', 'modal', 'animation'],
    tags: ['expandable', 'cards', 'list', 'modal', 'layout-animation'],
    description: 'List of cards that expand into a full modal overlay with shared layout animations on click.',
    previewImage: '',
    props: [
      { name: 'cards', type: 'array', required: false, description: 'Array of card objects with title, description, src, content, ctaText, ctaLink', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-expandable-cards',
    level: 'section',
    code: '<AceternityExpandableCards cards={[{ title: "Card", description: "Desc", src: "/img.jpg", content: "Details" }]} />',
    suggestedWith: ['aceternity-card-hover-effect', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-flip-words',
    name: 'AceternityFlipWords',
    displayName: 'Flip Words',
    source: 'aceternity',
    categories: ['text', 'animation'],
    tags: ['flip', 'words', 'text', 'cycling', 'animated'],
    description: 'Inline text that cycles through a list of words with a blur and slide flip animation.',
    previewImage: '',
    props: [
      { name: 'words', type: 'array', default: ['better', 'modern', 'beautiful', 'awesome'], required: false, description: 'Words to cycle through', group: 'content' },
      { name: 'duration', type: 'number', default: 3000, required: false, description: 'Time between flips in milliseconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-flip-words',
    level: 'primitive',
    code: '<AceternityFlipWords words={["fast", "modern", "beautiful"]} duration={3000} />',
    suggestedWith: ['aceternity-typewriter-effect', 'aceternity-colourful-text'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-floating-dock',
    name: 'AceternityFloatingDock',
    displayName: 'Floating Dock',
    source: 'aceternity',
    categories: ['navigation', 'animation'],
    tags: ['dock', 'navigation', 'macos', 'floating', 'magnification'],
    description: 'macOS-style floating dock with spring-based icon magnification on mouse hover.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of dock items with title, icon, and href', group: 'content' },
      { name: 'position', type: 'select', default: 'bottom', required: false, description: 'Dock position', options: ['bottom', 'top'], group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-floating-dock',
    level: 'primitive',
    code: '<AceternityFloatingDock items={[{ title: "Home", icon: "🏠", href: "#" }]} position="bottom" />',
    suggestedWith: ['aceternity-floating-navbar', 'aceternity-animated-tooltip'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-floating-navbar',
    name: 'AceternityFloatingNavbar',
    displayName: 'Floating Navbar',
    source: 'aceternity',
    categories: ['navigation', 'header'],
    tags: ['navbar', 'floating', 'sticky', 'hide-on-scroll', 'navigation'],
    description: 'Floating pill-shaped navbar that hides on scroll down and reappears on scroll up.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of nav items with name, link, and optional icon', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-floating-navbar',
    level: 'primitive',
    code: '<AceternityFloatingNavbar items={[{ name: "Home", link: "#" }]} />',
    suggestedWith: ['aceternity-floating-dock', 'aceternity-hero-highlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-focus-cards',
    name: 'AceternityFocusCards',
    displayName: 'Focus Cards',
    source: 'aceternity',
    categories: ['card', 'media', 'animation'],
    tags: ['focus', 'cards', 'images', 'blur', 'gallery'],
    description: 'Image card grid where clicking a card focuses it and blurs the rest with smooth transitions.',
    previewImage: '',
    props: [
      { name: 'cards', type: 'array', required: false, description: 'Array of card objects with title and src', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-focus-cards',
    level: 'section',
    code: '<AceternityFocusCards cards={[{ title: "Card 1", src: "/img.jpg" }]} />',
    suggestedWith: ['aceternity-card-hover-effect', 'aceternity-expandable-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-glare-card',
    name: 'AceternityGlareCard',
    displayName: 'Glare Card',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['glare', 'card', '3d', 'tilt', 'hover'],
    description: 'Dark card with 3D tilt effect and a cursor-following glare overlay on hover.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'The Spirit of Adventure', required: false, description: 'Card title', group: 'content' },
      { name: 'description', type: 'string', default: 'Explore uncharted territories...', required: false, description: 'Card description', group: 'content' },
      { name: 'icon', type: 'string', default: '✨', required: false, description: 'Icon emoji or character', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-glare-card',
    level: 'primitive',
    code: '<AceternityGlareCard title="Card Title" description="Some description" icon="✨" />',
    suggestedWith: ['aceternity-three-d-card', 'aceternity-direction-aware-hover'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-grid-and-dot-backgrounds',
    name: 'AceternityGridBackground',
    displayName: 'Grid & Dot Backgrounds',
    source: 'aceternity',
    categories: ['background', 'layout'],
    tags: ['grid', 'dots', 'background', 'pattern', 'decorative'],
    description: 'Configurable grid or dot pattern background with a radial gradient center fade mask.',
    previewImage: '',
    props: [
      { name: 'variant', type: 'select', default: 'grid', required: false, description: 'Pattern variant', options: ['grid', 'dot'], group: 'style' },
      { name: 'color', type: 'color', default: 'rgba(255,255,255,0.1)', required: false, description: 'Pattern color', group: 'style' },
      { name: 'size', type: 'number', default: 40, required: false, description: 'Grid or dot spacing in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-grid-and-dot-backgrounds',
    level: 'section',
    code: '<AceternityGridBackground variant="grid" size={40} />',
    suggestedWith: ['aceternity-aurora-background', 'aceternity-sparkles'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-hero-highlight',
    name: 'AceternityHeroHighlight',
    displayName: 'Hero Highlight',
    source: 'aceternity',
    categories: ['hero', 'section'],
    tags: ['hero', 'highlight', 'heading', 'cta', 'animated'],
    description: 'Hero section with animated text highlight underline, gradient background, CTA buttons, and optional image.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Build amazing websites with', required: false, description: 'Hero title text', group: 'content' },
      { name: 'highlightedText', type: 'string', default: 'incredible speed', required: false, description: 'Text to highlight', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Create stunning, responsive web experiences...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'ctaButtons', type: 'array', required: false, description: 'Array of CTA buttons with text, href, and variant', group: 'content' },
      { name: 'image', type: 'image', required: false, description: 'Optional hero image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-hero-highlight',
    level: 'section',
    code: '<AceternityHeroHighlight title="Build with" highlightedText="speed" subtitle="Start now" />',
    suggestedWith: ['aceternity-spotlight', 'aceternity-aurora-background'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-hero-parallax',
    name: 'AceternityHeroParallax',
    displayName: 'Hero Parallax',
    source: 'aceternity',
    categories: ['hero', 'animation'],
    tags: ['hero', 'parallax', 'scroll', '3d', 'products'],
    description: 'Scroll-driven hero with 3D perspective rotation and multi-row parallax product card showcase.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'The Ultimate Development Studio', required: false, description: 'Hero title', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'We build beautiful products...', required: false, description: 'Hero subtitle', group: 'content' },
      { name: 'products', type: 'array', required: false, description: 'Array of product items with title, thumbnail, and link', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-hero-parallax',
    level: 'section',
    code: '<AceternityHeroParallax title="Studio" products={[{ title: "App", thumbnail: "/img.jpg", link: "#" }]} />',
    suggestedWith: ['aceternity-hero-highlight', 'aceternity-sticky-scroll-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-images-slider',
    name: 'AceternityImagesSlider',
    displayName: 'Images Slider',
    source: 'aceternity',
    categories: ['media', 'animation'],
    tags: ['slider', 'carousel', 'images', 'autoplay', '3d'],
    description: 'Full-screen image slider with 3D perspective entrance animations, autoplay, overlay, and dot navigation.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs', group: 'content' },
      { name: 'autoplay', type: 'boolean', default: true, required: false, description: 'Enable autoplay', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'up', required: false, description: 'Exit animation direction', options: ['up', 'down'], group: 'behavior' },
      { name: 'overlay', type: 'boolean', default: true, required: false, description: 'Show dark overlay', group: 'style' },
      { name: 'overlayClassName', type: 'string', required: false, description: 'Overlay CSS classes', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-images-slider',
    level: 'section',
    code: '<AceternityImagesSlider images={["/img1.jpg", "/img2.jpg"]} autoplay={true} />',
    suggestedWith: ['aceternity-compare', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-infinite-moving-cards',
    name: 'AceternityInfiniteCards',
    displayName: 'Infinite Moving Cards',
    source: 'aceternity',
    categories: ['testimonial', 'animation'],
    tags: ['infinite', 'scroll', 'marquee', 'testimonials', 'cards'],
    description: 'Horizontally scrolling infinite marquee of testimonial cards with configurable speed and direction.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of items with quote, name, and title', group: 'content' },
      { name: 'direction', type: 'select', default: 'left', required: false, description: 'Scroll direction', options: ['left', 'right'], group: 'behavior' },
      { name: 'speed', type: 'select', default: 'normal', required: false, description: 'Scroll speed', options: ['fast', 'normal', 'slow'], group: 'behavior' },
      { name: 'pauseOnHover', type: 'boolean', default: true, required: false, description: 'Pause scrolling on hover', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-infinite-moving-cards',
    level: 'section',
    code: '<AceternityInfiniteCards items={[{ quote: "Great!", name: "John", title: "CEO" }]} direction="left" />',
    suggestedWith: ['aceternity-animated-testimonials', 'aceternity-card-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-lamp-effect',
    name: 'AceternityLampEffect',
    displayName: 'Lamp Effect',
    source: 'aceternity',
    categories: ['hero', 'effect'],
    tags: ['lamp', 'light', 'glow', 'hero', 'conic-gradient'],
    description: 'Dramatic lamp lighting effect with expanding conic gradient glow and scroll-triggered text reveal.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Build lamps the right way', required: false, description: 'Main heading', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'With Aceternity UI', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'description', type: 'string', default: 'Everything you need to build...', required: false, description: 'Description text', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-lamp-effect',
    level: 'section',
    code: '<AceternityLampEffect title="Welcome" subtitle="To the future" />',
    suggestedWith: ['aceternity-spotlight', 'aceternity-background-beams'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-link-preview',
    name: 'AceternityLinkPreview',
    displayName: 'Link Preview',
    source: 'aceternity',
    categories: ['other', 'animation'],
    tags: ['link', 'preview', 'tooltip', 'hover', 'popup'],
    description: 'Inline link that shows an animated preview popup with image and URL on hover.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Visit Aceternity UI', required: false, description: 'Link text', group: 'content' },
      { name: 'url', type: 'string', default: 'https://ui.aceternity.com', required: false, description: 'Link URL', group: 'content' },
      { name: 'previewImage', type: 'image', default: '', required: false, description: 'Preview image URL', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-link-preview',
    level: 'primitive',
    code: '<AceternityLinkPreview text="Click here" url="https://example.com" previewImage="/preview.jpg" />',
    suggestedWith: ['aceternity-animated-tooltip', 'aceternity-floating-navbar'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-meteors',
    name: 'AceternityMeteors',
    displayName: 'Meteors',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['meteors', 'particles', 'card', 'cosmic', 'animated'],
    description: 'Card component with animated meteor shower particles streaming across the background.',
    previewImage: '',
    props: [
      { name: 'count', type: 'number', default: 20, required: false, description: 'Number of meteors', group: 'behavior' },
      { name: 'title', type: 'string', default: 'Meteors because they look cool', required: false, description: 'Card title', group: 'content' },
      { name: 'description', type: 'string', default: 'A beautiful meteor shower effect...', required: false, description: 'Card description', group: 'content' },
      { name: 'ctaText', type: 'string', default: 'Explore', required: false, description: 'CTA button text', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-meteors',
    level: 'primitive',
    code: '<AceternityMeteors count={20} title="Cosmic Card" ctaText="Explore" />',
    suggestedWith: ['aceternity-shooting-stars', 'aceternity-sparkles'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-moving-border',
    name: 'AceternityMovingBorder',
    displayName: 'Moving Border',
    source: 'aceternity',
    categories: ['button', 'effect'],
    tags: ['button', 'border', 'animated', 'gradient', 'rotating'],
    description: 'Button with a continuously rotating conic gradient border animation effect.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Moving Border Button', required: false, description: 'Button text', group: 'content' },
      { name: 'borderRadius', type: 'string', default: '1.75rem', required: false, description: 'Border radius', group: 'style' },
      { name: 'duration', type: 'number', default: 4, required: false, description: 'Rotation duration in seconds', group: 'behavior' },
      { name: 'colors', type: 'array', default: ['#E2CBFF', '#393BB2', '#E2CBFF'], required: false, description: 'Gradient colors array', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes for inner content', group: 'style' },
      { name: 'containerClassName', type: 'string', required: false, description: 'Additional CSS classes for container', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-moving-border',
    level: 'primitive',
    code: '<AceternityMovingBorder text="Click Me" duration={4} />',
    suggestedWith: ['aceternity-glare-card', 'aceternity-spotlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-shooting-stars',
    name: 'AceternityShootingStars',
    displayName: 'Shooting Stars',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['stars', 'shooting', 'night-sky', 'background', 'animated'],
    description: 'Dark sky background with twinkling stars and animated shooting star trails streaking across.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Shooting Stars', required: false, description: 'Title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Watch the stars streak...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'minDelay', type: 'number', default: 1, required: false, description: 'Minimum delay between shooting stars', group: 'behavior' },
      { name: 'maxDelay', type: 'number', default: 5, required: false, description: 'Maximum delay between shooting stars', group: 'behavior' },
      { name: 'starCount', type: 'number', default: 8, required: false, description: 'Number of shooting stars', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-shooting-stars',
    level: 'section',
    code: '<AceternityShootingStars title="Night Sky" starCount={8} />',
    suggestedWith: ['aceternity-sparkles', 'aceternity-meteors'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-sparkles',
    name: 'AceternitySparkles',
    displayName: 'Sparkles',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['sparkles', 'particles', 'background', 'glow', 'stars'],
    description: 'Dark background filled with twinkling sparkle particles that fade in and out randomly.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Build With Sparkles', required: false, description: 'Title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Create magical interfaces...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'particleColor', type: 'color', default: '#FFF', required: false, description: 'Sparkle particle color', group: 'style' },
      { name: 'minSize', type: 'number', default: 1, required: false, description: 'Minimum particle size', group: 'behavior' },
      { name: 'maxSize', type: 'number', default: 3, required: false, description: 'Maximum particle size', group: 'behavior' },
      { name: 'particleCount', type: 'number', default: 50, required: false, description: 'Number of particles', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-sparkles',
    level: 'section',
    code: '<AceternitySparkles title="Sparkle" particleCount={50} particleColor="#FFF" />',
    suggestedWith: ['aceternity-shooting-stars', 'aceternity-meteors'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-spotlight',
    name: 'AceternitySpotlight',
    displayName: 'Spotlight',
    source: 'aceternity',
    categories: ['hero', 'effect'],
    tags: ['spotlight', 'hero', 'light', 'dark', 'cta'],
    description: 'Dark hero section with an animated SVG spotlight beam illuminating the title and CTA buttons.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Spotlight Effect That Draws Attention', required: false, description: 'Hero title', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Beautiful animated spotlight', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'description', type: 'string', default: 'Illuminate your content...', required: false, description: 'Description text', group: 'content' },
      { name: 'ctaButtons', type: 'array', required: false, description: 'Array of CTA buttons with text, href, variant', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-spotlight',
    level: 'section',
    code: '<AceternitySpotlight title="Welcome" description="Start building" />',
    suggestedWith: ['aceternity-lamp-effect', 'aceternity-hero-highlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-sticky-scroll-reveal',
    name: 'AceternityStickyScrollReveal',
    displayName: 'Sticky Scroll Reveal',
    source: 'aceternity',
    categories: ['section', 'animation'],
    tags: ['sticky', 'scroll', 'reveal', 'content', 'parallax'],
    description: 'Two-column layout with scrolling text content on the left and a sticky visual panel on the right.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of items with title, description, image, and bgColor', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-sticky-scroll-reveal',
    level: 'section',
    code: '<AceternityStickyScrollReveal items={[{ title: "Feature", description: "Details", image: "/img.jpg" }]} />',
    suggestedWith: ['aceternity-timeline', 'aceternity-tracing-beam'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-text-generate-effect',
    name: 'AceternityTextGenerate',
    displayName: 'Text Generate Effect',
    source: 'aceternity',
    categories: ['text', 'animation'],
    tags: ['text', 'generate', 'fade-in', 'stagger', 'blur'],
    description: 'Text that reveals word-by-word with a staggered blur-to-clear fade-in animation on view.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Generating text effects has never been this smooth...', required: false, description: 'Text to generate', group: 'content' },
      { name: 'speed', type: 'number', default: 0.05, required: false, description: 'Stagger delay between words in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-text-generate-effect',
    level: 'primitive',
    code: '<AceternityTextGenerate text="Hello world this is animated" speed={0.05} />',
    suggestedWith: ['aceternity-typewriter-effect', 'aceternity-encrypted-text'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-text-reveal-card',
    name: 'AceternityTextRevealCard',
    displayName: 'Text Reveal Card',
    source: 'aceternity',
    categories: ['text', 'effect'],
    tags: ['text', 'reveal', 'card', 'hover', 'interactive'],
    description: 'Dark card where moving the cursor horizontally reveals hidden text behind a sliding divider.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Sometimes, you just need to see it to believe it.', required: false, description: 'Background text', group: 'content' },
      { name: 'revealText', type: 'string', default: 'You just need to see it to believe it.', required: false, description: 'Revealed text', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-text-reveal-card',
    level: 'primitive',
    code: '<AceternityTextRevealCard text="Hidden message" revealText="Revealed!" />',
    suggestedWith: ['aceternity-encrypted-text', 'aceternity-text-generate-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-three-d-card',
    name: 'Aceternity3DCard',
    displayName: '3D Card',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['3d', 'card', 'tilt', 'perspective', 'hover'],
    description: 'Interactive card with multi-layer 3D depth, mouse-following tilt, and translateZ effects on content.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Make things float in air', required: false, description: 'Card title', group: 'content' },
      { name: 'description', type: 'string', default: 'Hover over this card to unleash...', required: false, description: 'Card description', group: 'content' },
      { name: 'image', type: 'image', default: '', required: false, description: 'Card image', group: 'content' },
      { name: 'imageAlt', type: 'string', default: '3D Card thumbnail', required: false, description: 'Image alt text', group: 'content' },
      { name: 'link', type: 'string', default: '#', required: false, description: 'CTA link URL', group: 'content' },
      { name: 'linkText', type: 'string', default: 'Try now →', required: false, description: 'CTA link text', group: 'content' },
      { name: 'tags', type: 'array', default: ['Next.js', 'Tailwind', 'Framer Motion'], required: false, description: 'Tag labels', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-three-d-card',
    level: 'primitive',
    code: '<Aceternity3DCard title="3D Card" description="Hover me" image="/img.jpg" />',
    suggestedWith: ['aceternity-glare-card', 'aceternity-direction-aware-hover'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-timeline',
    name: 'AceternityTimeline',
    displayName: 'Timeline',
    source: 'aceternity',
    categories: ['section', 'layout'],
    tags: ['timeline', 'history', 'events', 'scroll', 'vertical'],
    description: 'Vertical timeline with scroll-driven opacity and scale transitions for each item and animated dot indicators.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of timeline items with title and content', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-timeline',
    level: 'section',
    code: '<AceternityTimeline items={[{ title: "2024", content: "Started building" }]} />',
    suggestedWith: ['aceternity-tracing-beam', 'aceternity-sticky-scroll-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-tracing-beam',
    name: 'AceternityTracingBeam',
    displayName: 'Tracing Beam',
    source: 'aceternity',
    categories: ['section', 'effect'],
    tags: ['tracing', 'beam', 'progress', 'scroll', 'content'],
    description: 'Content layout with a vertical gradient progress beam that traces scroll position alongside content items.',
    previewImage: '',
    props: [
      { name: 'content', type: 'array', required: false, description: 'Array of content items with title, description, badge, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-tracing-beam',
    level: 'section',
    code: '<AceternityTracingBeam content={[{ title: "Step 1", description: "Getting started", badge: "01" }]} />',
    suggestedWith: ['aceternity-timeline', 'aceternity-sticky-scroll-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-typewriter-effect',
    name: 'AceternityTypewriter',
    displayName: 'Typewriter Effect',
    source: 'aceternity',
    categories: ['text', 'animation'],
    tags: ['typewriter', 'typing', 'text', 'cursor', 'stagger'],
    description: 'Typewriter-style text reveal with character-by-character staggered animation and blinking cursor.',
    previewImage: '',
    props: [
      { name: 'words', type: 'array', required: false, description: 'Array of word objects with text and optional className', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'cursorClassName', type: 'string', required: false, description: 'Cursor CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-typewriter-effect',
    level: 'primitive',
    code: '<AceternityTypewriter words={[{ text: "Build" }, { text: "awesome" }, { text: "apps" }]} />',
    suggestedWith: ['aceternity-text-generate-effect', 'aceternity-flip-words'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-wavy-background',
    name: 'AceternityWavyBackground',
    displayName: 'Wavy Background',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['wavy', 'canvas', 'background', 'animated', 'waves'],
    description: 'Canvas-based animated wave background with configurable colors, blur, speed, and wave properties.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Wavy Background Effect', required: false, description: 'Title text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'A beautiful canvas-based wave animation...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'blur', type: 'number', default: 10, required: false, description: 'Canvas blur amount', group: 'style' },
      { name: 'speed', type: 'select', default: 'slow', required: false, description: 'Animation speed', options: ['slow', 'fast'], group: 'behavior' },
      { name: 'waveWidth', type: 'number', default: 50, required: false, description: 'Wave line width', group: 'style' },
      { name: 'waveOpacity', type: 'number', default: 0.5, required: false, description: 'Wave opacity', group: 'style' },
      { name: 'colors', type: 'array', default: ['#38bdf8', '#818cf8', '#c084fc', '#e879f9', '#22d3ee'], required: false, description: 'Wave colors', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-wavy-background',
    level: 'section',
    code: '<AceternityWavyBackground title="Waves" speed="slow" blur={10} />',
    suggestedWith: ['aceternity-aurora-background', 'aceternity-background-gradient-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-wobble-card',
    name: 'AceternityWobbleCard',
    displayName: 'Wobble Card',
    source: 'aceternity',
    categories: ['card', 'grid', 'animation'],
    tags: ['wobble', 'cards', 'grid', 'tilt', 'colorful'],
    description: 'Colorful card grid with spring-based wobble tilt effect on mouse hover and variable column spans.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of card items with title, description, image, colSpan, and bgColor', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'aceternity-wobble-card',
    level: 'section',
    code: '<AceternityWobbleCard items={[{ title: "Card", description: "Desc", colSpan: 2, bgColor: "#ec4899" }]} />',
    suggestedWith: ['aceternity-bento-grid', 'aceternity-card-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-3d-marquee',
    name: 'AceternityThreeDMarquee',
    displayName: '3D Marquee',
    source: 'aceternity',
    categories: ['animation', 'media'],
    tags: ['marquee', '3d', 'perspective', 'images', 'columns', 'animated'],
    description: '3D perspective marquee with scrolling image columns creating a depth illusion.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs for the marquee columns', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-3d-marquee',
    level: 'section',
    code: '<AceternityThreeDMarquee />',
    suggestedWith: ['aceternity-hero-parallax', 'aceternity-parallax-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-3d-pin',
    name: 'AceternityThreeDPin',
    displayName: '3D Pin',
    source: 'aceternity',
    categories: ['card', 'animation'],
    tags: ['pin', '3d', 'card', 'hover', 'transform', 'animated'],
    description: 'Animated pin card with 3D transform effect on hover.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Pinned Card', required: false, description: 'Card title text', group: 'content' },
      { name: 'href', type: 'string', default: '#', required: false, description: 'Link URL for the pin card', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-3d-pin',
    level: 'primitive',
    code: '<AceternityThreeDPin title="Pinned" href="#" />',
    suggestedWith: ['aceternity-three-d-card', 'aceternity-glare-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-apple-cards-carousel',
    name: 'AceternityAppleCardsCarousel',
    displayName: 'Apple Cards Carousel',
    source: 'aceternity',
    categories: ['media', 'card'],
    tags: ['apple', 'carousel', 'cards', 'modal', 'expand', 'horizontal'],
    description: 'Apple-style horizontal card carousel with expand-to-modal interaction.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-apple-cards-carousel',
    level: 'section',
    code: '<AceternityAppleCardsCarousel />',
    suggestedWith: ['aceternity-carousel', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-background-beams-with-collision',
    name: 'AceternityBackgroundBeamsWithCollision',
    displayName: 'Background Beams With Collision',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['beams', 'collision', 'particles', 'svg', 'background', 'animated'],
    description: 'SVG beams that collide and burst into particles on impact.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to render inside the background', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-background-beams-with-collision',
    level: 'section',
    code: '<AceternityBackgroundBeamsWithCollision />',
    suggestedWith: ['aceternity-background-beams', 'aceternity-sparkles'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-background-boxes',
    name: 'AceternityBackgroundBoxes',
    displayName: 'Background Boxes',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['boxes', 'grid', 'background', 'animated', 'colorful'],
    description: 'Grid of animated boxes as a decorative background element.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to render over the boxes', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-background-boxes',
    level: 'section',
    code: '<AceternityBackgroundBoxes />',
    suggestedWith: ['aceternity-grid-and-dot-backgrounds', 'aceternity-aurora-background'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-background-lines',
    name: 'AceternityBackgroundLines',
    displayName: 'Background Lines',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['lines', 'svg', 'background', 'radial', 'animated'],
    description: 'Animated SVG lines radiating from center as a background effect.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'duration', type: 'number', required: false, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content to render over the lines', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-background-lines',
    level: 'section',
    code: '<AceternityBackgroundLines />',
    suggestedWith: ['aceternity-background-beams', 'aceternity-grid-and-dot-backgrounds'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-card-spotlight',
    name: 'AceternityCardSpotlight',
    displayName: 'Card Spotlight',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['card', 'spotlight', 'cursor', 'hover', 'glow'],
    description: 'Card with a cursor-following spotlight glow effect.',
    previewImage: '',
    props: [
      { name: 'radius', type: 'number', default: 350, required: false, description: 'Spotlight radius in pixels', group: 'behavior' },
      { name: 'color', type: 'color', default: '#262626', required: false, description: 'Spotlight color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Card content', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-card-spotlight',
    level: 'primitive',
    code: '<AceternityCardSpotlight radius={350} color="#262626" />',
    suggestedWith: ['aceternity-spotlight', 'aceternity-glare-card'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-card-stack',
    name: 'AceternityCardStack',
    displayName: 'Card Stack',
    source: 'aceternity',
    categories: ['card', 'animation'],
    tags: ['stack', 'cards', 'rotate', 'interval', 'animated'],
    description: 'Stacked cards that rotate through on an interval with smooth transitions.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of card items to stack', group: 'content' },
      { name: 'offset', type: 'number', required: false, description: 'Vertical offset between cards in pixels', group: 'style' },
      { name: 'scaleFactor', type: 'number', required: false, description: 'Scale reduction factor for stacked cards', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-card-stack',
    level: 'primitive',
    code: '<AceternityCardStack />',
    suggestedWith: ['aceternity-card-hover-effect', 'aceternity-expandable-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-carousel',
    name: 'AceternityCarousel',
    displayName: 'Carousel',
    source: 'aceternity',
    categories: ['media'],
    tags: ['carousel', 'slider', 'thumbnails', 'autoplay', 'gallery'],
    description: 'Full-featured carousel with thumbnails and autoplay support.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-carousel',
    level: 'section',
    code: '<AceternityCarousel />',
    suggestedWith: ['aceternity-images-slider', 'aceternity-apple-cards-carousel'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-container-scroll-animation',
    name: 'AceternityContainerScrollAnimation',
    displayName: 'Container Scroll Animation',
    source: 'aceternity',
    categories: ['animation', 'layout'],
    tags: ['scroll', 'container', 'ipad', '3d', 'rotation', 'animated'],
    description: 'iPad-style scroll animation with 3D rotation as the user scrolls.',
    previewImage: '',
    props: [
      { name: 'titleComponent', type: 'string', required: false, description: 'Title component or text to display', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-container-scroll-animation',
    level: 'section',
    code: '<AceternityContainerScrollAnimation />',
    suggestedWith: ['aceternity-hero-parallax', 'aceternity-sticky-scroll-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-draggable-card',
    name: 'AceternityDraggableCard',
    displayName: 'Draggable Card',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['draggable', 'card', 'drag', 'interactive', 'movable'],
    description: 'Card that can be dragged around the viewport with physics-based movement.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Draggable Card', required: false, description: 'Card title', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Card content', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-draggable-card',
    level: 'primitive',
    code: '<AceternityDraggableCard title="Drag Me" />',
    suggestedWith: ['aceternity-three-d-card', 'aceternity-wobble-card'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-evervault-card',
    name: 'AceternityEvervaultCard',
    displayName: 'Evervault Card',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['evervault', 'encrypted', 'matrix', 'hover', 'characters'],
    description: 'Card with encrypted character hover matrix effect inspired by Evervault.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'hover', required: false, description: 'Text to display in the card', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-evervault-card',
    level: 'primitive',
    code: '<AceternityEvervaultCard text="hover" />',
    suggestedWith: ['aceternity-encrypted-text', 'aceternity-glare-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-file-upload',
    name: 'AceternityFileUpload',
    displayName: 'File Upload',
    source: 'aceternity',
    categories: ['form', 'input'],
    tags: ['file', 'upload', 'drag-drop', 'form', 'animated'],
    description: 'Drag and drop file upload area with smooth animations.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-file-upload',
    level: 'primitive',
    code: '<AceternityFileUpload />',
    suggestedWith: ['aceternity-animated-modal', 'aceternity-multi-step-loader'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-following-pointer',
    name: 'AceternityFollowingPointer',
    displayName: 'Following Pointer',
    source: 'aceternity',
    categories: ['effect', 'animation'],
    tags: ['pointer', 'cursor', 'follow', 'label', 'interactive'],
    description: 'Pointer that follows the cursor with a trailing label element.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Pointer', required: false, description: 'Label text for the pointer', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content that triggers the pointer', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-following-pointer',
    level: 'primitive',
    code: '<AceternityFollowingPointer title="Follow" />',
    suggestedWith: ['aceternity-animated-tooltip', 'aceternity-link-preview'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-glowing-stars',
    name: 'AceternityGlowingStars',
    displayName: 'Glowing Stars',
    source: 'aceternity',
    categories: ['card', 'effect'],
    tags: ['stars', 'glow', 'constellation', 'card', 'animated'],
    description: 'Card with an animated glowing star constellation pattern.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-glowing-stars',
    level: 'primitive',
    code: '<AceternityGlowingStars />',
    suggestedWith: ['aceternity-sparkles', 'aceternity-shooting-stars'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-hover-border-gradient',
    name: 'AceternityHoverBorderGradient',
    displayName: 'Hover Border Gradient',
    source: 'aceternity',
    categories: ['button', 'effect'],
    tags: ['border', 'gradient', 'hover', 'button', 'animated'],
    description: 'Button or container with an animated gradient border on hover.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Button or container content', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'containerClassName', type: 'string', required: false, description: 'Container CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-hover-border-gradient',
    level: 'primitive',
    code: '<AceternityHoverBorderGradient />',
    suggestedWith: ['aceternity-moving-border', 'aceternity-glare-card'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-layout-grid',
    name: 'AceternityLayoutGrid',
    displayName: 'Layout Grid',
    source: 'aceternity',
    categories: ['grid', 'media'],
    tags: ['grid', 'bento', 'images', 'layout', 'gallery'],
    description: 'Bento-style image grid layout with variable card sizes.',
    previewImage: '',
    props: [
      { name: 'cards', type: 'array', required: false, description: 'Array of card objects for the grid', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-layout-grid',
    level: 'section',
    code: '<AceternityLayoutGrid />',
    suggestedWith: ['aceternity-bento-grid', 'aceternity-focus-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-lens',
    name: 'AceternityLens',
    displayName: 'Lens',
    source: 'aceternity',
    categories: ['media', 'effect'],
    tags: ['lens', 'magnify', 'zoom', 'hover', 'image'],
    description: 'Magnifying lens effect that zooms into content on hover.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Content to apply the lens effect on', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-lens',
    level: 'primitive',
    code: '<AceternityLens />',
    suggestedWith: ['aceternity-compare', 'aceternity-images-slider'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'aceternity-macbook-scroll',
    name: 'AceternityMacbookScroll',
    displayName: 'Macbook Scroll',
    source: 'aceternity',
    categories: ['hero', 'animation'],
    tags: ['macbook', 'laptop', '3d', 'scroll', 'lid', 'product'],
    description: '3D MacBook laptop with scroll-driven lid opening animation.',
    previewImage: '',
    props: [
      { name: 'src', type: 'image', required: false, description: 'Image displayed on the MacBook screen', group: 'content' },
      { name: 'title', type: 'string', required: false, description: 'Title text displayed above the MacBook', group: 'content' },
      { name: 'showGradient', type: 'boolean', default: true, required: false, description: 'Show background gradient effect', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-macbook-scroll',
    level: 'section',
    code: '<AceternityMacbookScroll title="Macbook Pro" showGradient={true} />',
    suggestedWith: ['aceternity-hero-parallax', 'aceternity-container-scroll-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-multi-step-loader',
    name: 'AceternityMultiStepLoader',
    displayName: 'Multi Step Loader',
    source: 'aceternity',
    categories: ['effect', 'animation'],
    tags: ['loader', 'multi-step', 'loading', 'progress', 'overlay', 'animated'],
    description: 'Animated multi-step loading overlay with sequential state transitions.',
    previewImage: '',
    props: [
      { name: 'loadingStates', type: 'array', required: false, description: 'Array of loading state objects with text', group: 'content' },
      { name: 'loading', type: 'boolean', default: false, required: false, description: 'Whether the loader is active', group: 'behavior' },
      { name: 'duration', type: 'number', default: 2000, required: false, description: 'Duration per step in milliseconds', group: 'behavior' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-multi-step-loader',
    level: 'primitive',
    code: '<AceternityMultiStepLoader loading={true} duration={2000} />',
    suggestedWith: ['aceternity-animated-modal', 'aceternity-file-upload'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-navbar-menu',
    name: 'AceternityNavbarMenu',
    displayName: 'Navbar Menu',
    source: 'aceternity',
    categories: ['navigation'],
    tags: ['navbar', 'menu', 'dropdown', 'hover', 'navigation'],
    description: 'Animated navigation bar with dropdown hover menus.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-navbar-menu',
    level: 'primitive',
    code: '<AceternityNavbarMenu />',
    suggestedWith: ['aceternity-floating-navbar', 'aceternity-floating-dock'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-parallax-scroll',
    name: 'AceternityParallaxScroll',
    displayName: 'Parallax Scroll',
    source: 'aceternity',
    categories: ['media', 'animation'],
    tags: ['parallax', 'scroll', 'images', 'columns', 'gallery'],
    description: 'Three-column parallax image scroll with varying scroll speeds.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs for the parallax columns', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-parallax-scroll',
    level: 'section',
    code: '<AceternityParallaxScroll />',
    suggestedWith: ['aceternity-hero-parallax', 'aceternity-images-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-placeholders-and-vanish-input',
    name: 'AceternityPlaceholdersAndVanishInput',
    displayName: 'Placeholders & Vanish Input',
    source: 'aceternity',
    categories: ['form', 'animation'],
    tags: ['input', 'placeholder', 'vanish', 'cycling', 'form', 'animated'],
    description: 'Input with cycling placeholder text and a vanish-on-submit animation effect.',
    previewImage: '',
    props: [
      { name: 'placeholders', type: 'array', required: false, description: 'Array of placeholder strings to cycle through', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-placeholders-and-vanish-input',
    level: 'primitive',
    code: '<AceternityPlaceholdersAndVanishInput placeholders={["Search...", "Type here..."]} />',
    suggestedWith: ['aceternity-file-upload', 'aceternity-animated-modal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-sidebar',
    name: 'AceternitySidebar',
    displayName: 'Sidebar',
    source: 'aceternity',
    categories: ['navigation', 'layout'],
    tags: ['sidebar', 'navigation', 'collapsible', 'menu', 'animated'],
    description: 'Collapsible animated sidebar navigation with smooth expand/collapse transitions.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-sidebar',
    level: 'section',
    code: '<AceternitySidebar />',
    suggestedWith: ['aceternity-floating-navbar', 'aceternity-navbar-menu'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-spotlight-new',
    name: 'AceternitySpotlightNew',
    displayName: 'Spotlight New',
    source: 'aceternity',
    categories: ['hero', 'effect'],
    tags: ['spotlight', 'beam', 'svg', 'hero', 'light'],
    description: 'New spotlight effect with SVG-based beam animation.',
    previewImage: '',
    props: [
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'fill', type: 'string', required: false, description: 'Fill color for the spotlight beam', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-spotlight-new',
    level: 'section',
    code: '<AceternitySpotlightNew />',
    suggestedWith: ['aceternity-spotlight', 'aceternity-lamp-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-svg-mask-effect',
    name: 'AceternitySvgMaskEffect',
    displayName: 'SVG Mask Effect',
    source: 'aceternity',
    categories: ['text', 'effect'],
    tags: ['svg', 'mask', 'reveal', 'hover', 'text', 'interactive'],
    description: 'SVG mask reveal effect that uncovers hidden text on mouse hover.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Hidden Text', required: false, description: 'Visible text', group: 'content' },
      { name: 'revealText', type: 'string', default: 'Revealed Text', required: false, description: 'Text revealed on hover', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-svg-mask-effect',
    level: 'primitive',
    code: '<AceternitySvgMaskEffect text="Hover me" revealText="Surprise!" />',
    suggestedWith: ['aceternity-text-reveal-card', 'aceternity-text-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-text-hover-effect',
    name: 'AceternityTextHoverEffect',
    displayName: 'Text Hover Effect',
    source: 'aceternity',
    categories: ['text', 'effect'],
    tags: ['text', 'hover', 'gradient', 'reveal', 'large', 'interactive'],
    description: 'Large text with gradient hover reveal effect on mouse move.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'HOVER', required: false, description: 'Text to display', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-text-hover-effect',
    level: 'primitive',
    code: '<AceternityTextHoverEffect text="HOVER" />',
    suggestedWith: ['aceternity-svg-mask-effect', 'aceternity-text-reveal-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'aceternity-vortex',
    name: 'AceternityVortex',
    displayName: 'Vortex',
    source: 'aceternity',
    categories: ['background', 'effect'],
    tags: ['vortex', 'particles', 'canvas', 'background', 'animated'],
    description: 'Canvas-based particle vortex animation with swirling particles.',
    previewImage: '',
    props: [
      { name: 'particleCount', type: 'number', required: false, description: 'Number of particles in the vortex', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to render over the vortex', group: 'content' },
    ],
    dependencies: ['motion'],
    modulePath: 'aceternity-vortex',
    level: 'section',
    code: '<AceternityVortex />',
    suggestedWith: ['aceternity-sparkles', 'aceternity-wavy-background'],
    version: '1.0.0',
    acceptsChildren: true,
  },
]
