import type { ComponentRegistryItem } from '../types'

export const builtinComponents: ComponentRegistryItem[] = [
  // === Structure ===
  {
    id: 'builtin-section',
    name: 'Section',
    displayName: 'Section',
    source: 'builtin',
    categories: ['layout', 'section'],
    tags: ['structure', 'container', 'wrapper', 'semantic'],
    description: 'A full-width section container. Use to organize your page into distinct areas.',
    previewImage: '',
    props: [
      { name: 'tag', type: 'select', required: false, default: 'section', options: ['section', 'div', 'article', 'aside', 'main', 'header', 'footer', 'nav'], description: 'HTML tag' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<Section>Content here</Section>',
    suggestedWith: ['builtin-container', 'builtin-flex-box'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-container',
    name: 'Container',
    displayName: 'Container',
    source: 'builtin',
    categories: ['layout'],
    tags: ['structure', 'container', 'centered', 'max-width'],
    description: 'A centered container with max-width. Wraps content in a constrained width.',
    previewImage: '',
    props: [
      { name: 'maxWidth', type: 'string', required: false, default: '1200px', description: 'Maximum width' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<Container maxWidth="1200px">Content</Container>',
    suggestedWith: ['builtin-section', 'builtin-flex-box'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-div-block',
    name: 'DivBlock',
    displayName: 'Div Block',
    source: 'builtin',
    categories: ['layout'],
    tags: ['structure', 'div', 'block', 'generic'],
    description: 'A generic div block. The most basic building block for layouts.',
    previewImage: '',
    props: [],
    dependencies: [],
    level: 'layout',
    code: '<DivBlock>Content</DivBlock>',
    suggestedWith: ['builtin-heading', 'builtin-paragraph'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-flex-box',
    name: 'FlexBox',
    displayName: 'Flex Box',
    source: 'builtin',
    categories: ['layout'],
    tags: ['structure', 'flex', 'flexbox', 'row', 'column'],
    description: 'A flexbox container. Arrange children in rows or columns with alignment control.',
    previewImage: '',
    props: [
      { name: 'direction', type: 'select', required: false, default: 'row', options: ['row', 'column', 'row-reverse', 'column-reverse'], description: 'Flex direction' },
      { name: 'wrap', type: 'select', required: false, default: 'nowrap', options: ['nowrap', 'wrap', 'wrap-reverse'], description: 'Flex wrap' },
      { name: 'justify', type: 'select', required: false, default: 'flex-start', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], description: 'Justify content' },
      { name: 'align', type: 'select', required: false, default: 'stretch', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], description: 'Align items' },
      { name: 'gap', type: 'string', required: false, default: '0px', description: 'Gap between items' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<FlexBox direction="row" gap="16px">Children</FlexBox>',
    suggestedWith: ['builtin-div-block', 'builtin-heading'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-grid-layout',
    name: 'GridLayout',
    displayName: 'Grid',
    source: 'builtin',
    categories: ['layout', 'grid'],
    tags: ['structure', 'grid', 'css-grid', 'columns', 'rows'],
    description: 'A CSS Grid container. Create complex two-dimensional layouts.',
    previewImage: '',
    props: [
      { name: 'columns', type: 'string', required: false, default: 'repeat(2, 1fr)', description: 'Grid template columns' },
      { name: 'rows', type: 'string', required: false, default: 'auto', description: 'Grid template rows' },
      { name: 'gap', type: 'string', required: false, default: '16px', description: 'Grid gap' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<GridLayout columns="repeat(3, 1fr)" gap="24px">Children</GridLayout>',
    suggestedWith: ['builtin-div-block', 'builtin-container'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-columns',
    name: 'Columns',
    displayName: 'Columns',
    source: 'builtin',
    categories: ['layout', 'grid'],
    tags: ['structure', 'columns', 'grid', 'multi-column'],
    description: 'A simple equal-width column layout. Quick way to create 2, 3, or 4 column grids.',
    previewImage: '',
    props: [
      { name: 'count', type: 'select', required: false, default: '2', options: ['2', '3', '4'], description: 'Number of columns' },
      { name: 'gap', type: 'string', required: false, default: '24px', description: 'Gap between columns' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<Columns count={3} gap="24px">Children</Columns>',
    suggestedWith: ['builtin-div-block', 'builtin-container'],
    version: '1.0.0',
    acceptsChildren: true,
  },

  // === Typography ===
  {
    id: 'builtin-heading',
    name: 'Heading',
    displayName: 'Heading',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'heading', 'title', 'h1', 'h2', 'h3'],
    description: 'A heading element (H1-H6). Use for titles and section headers.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Heading', description: 'Heading text' },
      { name: 'level', type: 'select', required: false, default: '2', options: ['1', '2', '3', '4', '5', '6'], description: 'Heading level (H1-H6)' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<Heading level={2} text="Your Heading" />',
    suggestedWith: ['builtin-paragraph', 'builtin-div-block'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-paragraph',
    name: 'Paragraph',
    displayName: 'Paragraph',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'paragraph', 'text', 'body'],
    description: 'A paragraph element for body text content.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', description: 'Paragraph text' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<Paragraph text="Your text here" />',
    suggestedWith: ['builtin-heading', 'builtin-link-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-text-block',
    name: 'TextBlock',
    displayName: 'Text Block',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'text', 'inline', 'span'],
    description: 'An inline text block (span). For text within other elements.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Text block', description: 'Text content' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<TextBlock text="Inline text" />',
    suggestedWith: ['builtin-heading', 'builtin-paragraph'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-link-element',
    name: 'LinkElement',
    displayName: 'Link',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'link', 'anchor', 'href', 'navigation'],
    description: 'A text link element with configurable URL and target.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Link', description: 'Link text' },
      { name: 'href', type: 'string', required: false, default: '#', description: 'URL' },
      { name: 'target', type: 'select', required: false, default: '_self', options: ['_self', '_blank'], description: 'Open in' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<LinkElement text="Click here" href="/page" />',
    suggestedWith: ['builtin-paragraph', 'builtin-button-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-rich-text',
    name: 'RichText',
    displayName: 'Rich Text',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'richtext', 'html', 'content', 'cms'],
    description: 'A rich text block supporting HTML content. Ideal for CMS-connected content.',
    previewImage: '',
    props: [
      { name: 'content', type: 'richtext', required: false, default: '<p>Rich text content here.</p>', description: 'HTML content' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<RichText content="<p>Your content</p>" />',
    suggestedWith: ['builtin-section', 'builtin-container'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-list-element',
    name: 'ListElement',
    displayName: 'List',
    source: 'builtin',
    categories: ['text'],
    tags: ['typography', 'list', 'ul', 'ol', 'items'],
    description: 'An ordered or unordered list with configurable items.',
    previewImage: '',
    props: [
      { name: 'type', type: 'select', required: false, default: 'ul', options: ['ul', 'ol'], description: 'List type' },
      { name: 'items', type: 'array', required: false, default: ['Item 1', 'Item 2', 'Item 3'], description: 'List items' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<ListElement type="ul" items={["Item 1", "Item 2"]} />',
    suggestedWith: ['builtin-heading', 'builtin-paragraph'],
    version: '1.0.0',
    acceptsChildren: false,
  },

  // === Media ===
  {
    id: 'builtin-image',
    name: 'ImageElement',
    displayName: 'Image',
    source: 'builtin',
    categories: ['media'],
    tags: ['media', 'image', 'photo', 'picture', 'img'],
    description: 'An image element with configurable source, alt text, and sizing.',
    previewImage: '',
    props: [
      { name: 'src', type: 'image', required: false, default: 'https://placehold.co/800x400/e2e8f0/64748b?text=Image', description: 'Image source URL' },
      { name: 'alt', type: 'string', required: false, default: 'Image', description: 'Alt text' },
      { name: 'objectFit', type: 'select', required: false, default: 'cover', options: ['cover', 'contain', 'fill', 'none'], description: 'Object fit' },
      { name: 'width', type: 'string', required: false, default: '100%', description: 'Width' },
      { name: 'height', type: 'string', required: false, default: 'auto', description: 'Height' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<ImageElement src="/image.jpg" alt="Description" />',
    suggestedWith: ['builtin-div-block', 'builtin-link-block'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-video',
    name: 'VideoElement',
    displayName: 'Video',
    source: 'builtin',
    categories: ['media'],
    tags: ['media', 'video', 'player', 'embed'],
    description: 'An HTML5 video player with playback controls.',
    previewImage: '',
    props: [
      { name: 'src', type: 'string', required: false, default: '', description: 'Video source URL' },
      { name: 'poster', type: 'image', required: false, description: 'Poster image URL' },
      { name: 'autoPlay', type: 'boolean', required: false, default: false, description: 'Auto-play' },
      { name: 'loop', type: 'boolean', required: false, default: false, description: 'Loop' },
      { name: 'muted', type: 'boolean', required: false, default: true, description: 'Muted' },
      { name: 'controls', type: 'boolean', required: false, default: true, description: 'Show controls' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<VideoElement src="/video.mp4" controls />',
    suggestedWith: ['builtin-section', 'builtin-div-block'],
    version: '1.0.0',
    acceptsChildren: false,
  },

  // === Forms ===
  {
    id: 'builtin-form-block',
    name: 'FormBlock',
    displayName: 'Form',
    source: 'builtin',
    categories: ['form'],
    tags: ['form', 'input', 'submit', 'container'],
    description: 'A form container. Drop input fields and buttons inside.',
    previewImage: '',
    props: [
      { name: 'action', type: 'string', required: false, default: '#', description: 'Form action URL' },
      { name: 'method', type: 'select', required: false, default: 'post', options: ['get', 'post'], description: 'HTTP method' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<FormBlock action="/submit">Fields here</FormBlock>',
    suggestedWith: ['builtin-input-field', 'builtin-button-element'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'builtin-input-field',
    name: 'InputField',
    displayName: 'Input',
    source: 'builtin',
    categories: ['form', 'input'],
    tags: ['form', 'input', 'text', 'email', 'field'],
    description: 'A labeled input field with configurable type and validation.',
    previewImage: '',
    props: [
      { name: 'label', type: 'string', required: false, default: 'Label', description: 'Input label' },
      { name: 'type', type: 'select', required: false, default: 'text', options: ['text', 'email', 'password', 'number', 'tel', 'url', 'search', 'date'], description: 'Input type' },
      { name: 'placeholder', type: 'string', required: false, default: 'Enter text...', description: 'Placeholder' },
      { name: 'name', type: 'string', required: false, default: 'field', description: 'Field name' },
      { name: 'required', type: 'boolean', required: false, default: false, description: 'Required' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<InputField label="Email" type="email" placeholder="you@example.com" />',
    suggestedWith: ['builtin-form-block', 'builtin-button-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-text-area',
    name: 'TextAreaField',
    displayName: 'Text Area',
    source: 'builtin',
    categories: ['form', 'input'],
    tags: ['form', 'textarea', 'multiline', 'message'],
    description: 'A labeled multi-line text area for longer text input.',
    previewImage: '',
    props: [
      { name: 'label', type: 'string', required: false, default: 'Message', description: 'Label' },
      { name: 'placeholder', type: 'string', required: false, default: 'Enter text...', description: 'Placeholder' },
      { name: 'name', type: 'string', required: false, default: 'message', description: 'Field name' },
      { name: 'rows', type: 'number', required: false, default: 4, description: 'Number of rows' },
      { name: 'required', type: 'boolean', required: false, default: false, description: 'Required' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<TextAreaField label="Message" rows={4} />',
    suggestedWith: ['builtin-form-block', 'builtin-input-field'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-select-field',
    name: 'SelectField',
    displayName: 'Select',
    source: 'builtin',
    categories: ['form', 'input'],
    tags: ['form', 'select', 'dropdown', 'options'],
    description: 'A labeled dropdown select field with configurable options.',
    previewImage: '',
    props: [
      { name: 'label', type: 'string', required: false, default: 'Select', description: 'Label' },
      { name: 'name', type: 'string', required: false, default: 'select', description: 'Field name' },
      { name: 'options', type: 'array', required: false, default: ['Option 1', 'Option 2', 'Option 3'], description: 'Options' },
      { name: 'placeholder', type: 'string', required: false, default: 'Choose an option...', description: 'Placeholder' },
      { name: 'required', type: 'boolean', required: false, default: false, description: 'Required' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<SelectField label="Country" options={["US", "UK", "FR"]} />',
    suggestedWith: ['builtin-form-block', 'builtin-input-field'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-button-element',
    name: 'ButtonElement',
    displayName: 'Button',
    source: 'builtin',
    categories: ['button', 'form'],
    tags: ['button', 'cta', 'action', 'submit', 'click'],
    description: 'A button element with variant and size options.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Button', description: 'Button text' },
      { name: 'variant', type: 'select', required: false, default: 'primary', options: ['primary', 'secondary', 'outline', 'ghost'], description: 'Variant' },
      { name: 'size', type: 'select', required: false, default: 'md', options: ['sm', 'md', 'lg'], description: 'Size' },
      { name: 'type', type: 'select', required: false, default: 'button', options: ['button', 'submit', 'reset'], description: 'Button type' },
    ],
    dependencies: [],
    level: 'primitive',
    code: '<ButtonElement text="Click Me" variant="primary" />',
    suggestedWith: ['builtin-form-block', 'builtin-link-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'builtin-link-block',
    name: 'LinkBlock',
    displayName: 'Link Block',
    source: 'builtin',
    categories: ['layout'],
    tags: ['link', 'block', 'container', 'clickable', 'anchor'],
    description: 'A block-level link that wraps content. Make any group of elements clickable.',
    previewImage: '',
    props: [
      { name: 'href', type: 'string', required: false, default: '#', description: 'URL' },
      { name: 'target', type: 'select', required: false, default: '_self', options: ['_self', '_blank'], description: 'Open in' },
    ],
    dependencies: [],
    level: 'layout',
    code: '<LinkBlock href="/page">Clickable content</LinkBlock>',
    suggestedWith: ['builtin-image', 'builtin-heading'],
    version: '1.0.0',
    acceptsChildren: true,
  },
]
