import type { ComponentRegistryItem } from '../types'

export const osmoComponents: ComponentRegistryItem[] = [
  {
    id: 'osmo-apple-dock-navigation',
    name: 'OsmoAppleDockNavigation',
    displayName: 'Apple Dock Navigation',
    source: 'osmo',
    categories: ['navigation'],
    tags: ['dock', 'apple', 'macos', 'magnification', 'tooltip', 'nav'],
    description: 'An Apple macOS-style dock navigation with magnification effect on hover. Icons scale up near the cursor with smooth transitions and tooltips.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of dock items with label, icon character, and href',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Tooltip label' },
          { name: 'icon', type: 'string', required: true, description: 'Icon character or emoji' },
          { name: 'href', type: 'string', required: true, description: 'Link URL' },
        ],
      },
      { name: 'position', type: 'select', default: 'bottom', required: false, options: ['bottom', 'left', 'right'], description: 'Dock position on screen', group: 'style' },
      { name: 'size', type: 'number', default: 56, required: false, description: 'Base icon size in pixels', group: 'style' },
    ],
    dependencies: [],
    modulePath: 'osmo-apple-dock-navigation',
    level: 'primitive',
    code: '<OsmoAppleDockNavigation position="bottom" size={56} />',
    suggestedWith: ['osmo-bold-fullscreen-navigation', 'osmo-scaling-hamburger-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-before-after-split-slider',
    name: 'OsmoBeforeAfterSplitSlider',
    displayName: 'Before/After Split Slider',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['before', 'after', 'split', 'slider', 'compare', 'image', 'drag'],
    description: 'A before/after image comparison slider with a draggable divider. Click or drag to reveal the before and after images side by side.',
    previewImage: '',
    props: [
      { name: 'beforeImage', type: 'image', default: 'https://picsum.photos/seed/before/800/500?grayscale', required: false, description: 'Before state image URL', group: 'content' },
      { name: 'afterImage', type: 'image', default: 'https://picsum.photos/seed/after/800/500', required: false, description: 'After state image URL', group: 'content' },
      { name: 'initialPosition', type: 'number', default: 50, required: false, description: 'Initial divider position as percentage (0-100)', group: 'behavior' },
    ],
    dependencies: [],
    modulePath: 'osmo-before-after-split-slider',
    level: 'primitive',
    code: '<OsmoBeforeAfterSplitSlider beforeImage="/before.jpg" afterImage="/after.jpg" initialPosition={50} />',
    suggestedWith: ['osmo-pixelated-image-reveal', 'osmo-image-to-background-zoom'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-bold-fullscreen-navigation',
    name: 'OsmoBoldFullscreenNavigation',
    displayName: 'Bold Fullscreen Navigation',
    source: 'osmo',
    categories: ['navigation'],
    tags: ['fullscreen', 'navigation', 'menu', 'overlay', 'bold', 'hamburger', 'background-image'],
    description: 'A bold fullscreen navigation overlay with large text links. Hovering a link reveals a background image with smooth GSAP clip-path transitions.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of navigation items with label, href, and background image',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Link text' },
          { name: 'href', type: 'string', required: true, description: 'Link URL' },
          { name: 'image', type: 'image', required: true, description: 'Background image on hover' },
        ],
      },
      { name: 'bgColor', type: 'color', default: '#0a0a0a', required: false, description: 'Overlay background color', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-bold-fullscreen-navigation',
    level: 'section',
    code: '<OsmoBoldFullscreenNavigation bgColor="#0a0a0a" />',
    suggestedWith: ['osmo-scaling-hamburger-navigation', 'osmo-apple-dock-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-css-marquee',
    name: 'OsmoCSSMarquee',
    displayName: 'CSS Marquee',
    source: 'osmo',
    categories: ['animation', 'text'],
    tags: ['marquee', 'css', 'ticker', 'scroll', 'loop', 'no-js', 'lightweight'],
    description: 'A lightweight CSS-only infinite marquee with no JavaScript dependencies. Supports configurable speed, direction, and gap between items.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings to display', group: 'content' },
      { name: 'speed', type: 'number', default: 30, required: false, description: 'Animation duration in seconds (higher = slower)', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, options: ['left', 'right'], description: 'Scroll direction', group: 'behavior' },
      { name: 'gap', type: 'number', default: 48, required: false, description: 'Gap between items in pixels', group: 'style' },
    ],
    dependencies: [],
    modulePath: 'osmo-css-marquee',
    level: 'primitive',
    code: '<OsmoCSSMarquee items={["Creative Studio", "Digital Design"]} speed={30} />',
    suggestedWith: ['osmo-draggable-marquee', 'gsap-scroll-infinite-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-directional-list-hover',
    name: 'OsmoDirectionalListHover',
    displayName: 'Directional List Hover',
    source: 'osmo',
    categories: ['navigation', 'animation'],
    tags: ['list', 'hover', 'directional', 'preview', 'image', 'cursor-follow'],
    description: 'A styled list of links where hovering reveals a floating image preview that follows the cursor. Entrance direction is detected from mouse position.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of list items with title, image, and link',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Item title text' },
          { name: 'image', type: 'image', required: true, description: 'Preview image URL' },
          { name: 'link', type: 'string', required: true, description: 'Link URL' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-directional-list-hover',
    level: 'section',
    code: '<OsmoDirectionalListHover />',
    suggestedWith: ['osmo-bold-fullscreen-navigation', 'osmo-sticky-features'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-draggable-marquee',
    name: 'OsmoDraggableMarquee',
    displayName: 'Draggable Marquee',
    source: 'osmo',
    categories: ['animation', 'text'],
    tags: ['marquee', 'draggable', 'drag', 'ticker', 'scroll', 'interactive', 'loop'],
    description: 'An infinite marquee that can be grabbed and dragged with pointer events. Auto-scrolls by default and pauses on hover. Supports left/right direction.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings to display', group: 'content' },
      { name: 'speed', type: 'number', default: 60, required: false, description: 'Auto-scroll speed in pixels per second', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, options: ['left', 'right'], description: 'Marquee direction', group: 'behavior' },
      { name: 'pauseOnHover', type: 'boolean', default: true, required: false, description: 'Pause auto-scroll on mouse hover', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-draggable-marquee',
    level: 'primitive',
    code: '<OsmoDraggableMarquee items={["Design", "Code", "Ship"]} speed={60} />',
    suggestedWith: ['osmo-css-marquee', 'gsap-scroll-infinite-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-dropping-cards-stack',
    name: 'OsmoDroppingCardsStack',
    displayName: 'Dropping Cards Stack',
    source: 'osmo',
    categories: ['card', 'animation'],
    tags: ['cards', 'stack', 'drop', 'carousel', 'autoplay', 'animated'],
    description: 'An animated card stack where the active card sits on top and previous cards drop away with rotation. Includes autoplay and dot indicators.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, description, and image',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card title' },
          { name: 'description', type: 'string', required: true, description: 'Card description' },
          { name: 'image', type: 'image', required: true, description: 'Card image URL' },
        ],
      },
      { name: 'autoplay', type: 'boolean', default: true, required: false, description: 'Auto-cycle through cards', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-dropping-cards-stack',
    level: 'primitive',
    code: '<OsmoDroppingCardsStack autoplay />',
    suggestedWith: ['osmo-stacking-cards-parallax', 'osmo-stacking-cards-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-falling-2d-objects',
    name: 'OsmoFalling2DObjects',
    displayName: 'Falling 2D Objects',
    source: 'osmo',
    categories: ['animation', 'effect'],
    tags: ['physics', 'matter-js', 'falling', 'gravity', 'objects', 'interactive', '2d'],
    description: 'A 2D physics simulation using Matter.js where colorful objects fall, bounce, and can be dragged with the mouse. Configurable gravity and bounciness.',
    previewImage: '',
    props: [
      { name: 'textures', type: 'array', required: false, description: 'Array of color strings for the falling objects', group: 'style' },
      { name: 'objectCount', type: 'number', default: 30, required: false, description: 'Number of objects to create', group: 'content' },
      { name: 'objectSize', type: 'number', default: 40, required: false, description: 'Base size of objects in pixels', group: 'style' },
      { name: 'gravity', type: 'number', default: 1, required: false, description: 'Gravity strength multiplier', group: 'behavior' },
      { name: 'bounciness', type: 'number', default: 0.6, required: false, description: 'Bounciness (restitution) of objects (0-1)', group: 'behavior' },
    ],
    dependencies: ['matter-js'],
    modulePath: 'osmo-falling-2d-objects',
    level: 'section',
    code: '<OsmoFalling2DObjects objectCount={30} gravity={1} bounciness={0.6} />',
    suggestedWith: ['osmo-falling-text-gravity', 'osmo-interactive-pixel-grid'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-falling-text-gravity',
    name: 'OsmoFallingTextGravity',
    displayName: 'Falling Text Gravity',
    source: 'osmo',
    categories: ['text', 'animation'],
    tags: ['gravity', 'falling', 'text', 'bounce', 'characters', 'physics-like'],
    description: 'Text characters that fall individually with simulated gravity and bounce physics. Each letter drops, bounces multiple times, and settles at the bottom.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'GRAVITY', required: false, description: 'Text to animate with falling effect', group: 'content' },
      { name: 'gravity', type: 'number', default: 1, required: false, description: 'Gravity speed multiplier', group: 'behavior' },
      { name: 'bounciness', type: 'number', default: 0.4, required: false, description: 'Bounce height ratio (0-1)', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-falling-text-gravity',
    level: 'primitive',
    code: '<OsmoFallingTextGravity text="GRAVITY" gravity={1} bounciness={0.4} />',
    suggestedWith: ['osmo-falling-2d-objects', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-footer-parallax-effect',
    name: 'OsmoFooterParallaxEffect',
    displayName: 'Footer Parallax Effect',
    source: 'osmo',
    categories: ['footer', 'animation'],
    tags: ['footer', 'parallax', 'scroll', 'cta', 'links', 'gradient'],
    description: 'A footer section with parallax scroll effects. The title slides in with a sticky feel, subtitle fades in, and social links stagger-reveal.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: "Let's Work Together", required: false, description: 'Main heading text', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Ready to start your next project?', required: false, description: 'Subtitle text above the title', group: 'content' },
      {
        name: 'links',
        type: 'array',
        required: false,
        description: 'Array of footer link objects',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Link text' },
          { name: 'href', type: 'string', required: true, description: 'Link URL' },
        ],
      },
      { name: 'bgColor', type: 'color', default: '#0a0a0a', required: false, description: 'Footer background color', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-footer-parallax-effect',
    level: 'section',
    code: '<OsmoFooterParallaxEffect title="Let\'s Work Together" />',
    suggestedWith: ['osmo-highlight-text-on-scroll', 'osmo-stacking-cards-parallax'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-glowing-dots-grid',
    name: 'OsmoGlowingDotsGrid',
    displayName: 'Glowing Dots Grid',
    source: 'osmo',
    categories: ['background', 'effect'],
    tags: ['dots', 'grid', 'glow', 'mouse', 'interactive', 'ambient', 'background'],
    description: 'An interactive grid of dots that glow and scale when the cursor is nearby. Creates an ambient background effect with configurable color and radius.',
    previewImage: '',
    props: [
      { name: 'rows', type: 'number', default: 15, required: false, description: 'Number of dot rows', group: 'style' },
      { name: 'cols', type: 'number', default: 25, required: false, description: 'Number of dot columns', group: 'style' },
      { name: 'color', type: 'color', default: '#667eea', required: false, description: 'Dot color', group: 'style' },
      { name: 'glowRadius', type: 'number', default: 5, required: false, description: 'Number of dots affected by cursor proximity', group: 'behavior' },
      { name: 'interactive', type: 'boolean', default: true, required: false, description: 'Enable mouse interaction', group: 'behavior' },
    ],
    dependencies: [],
    modulePath: 'osmo-glowing-dots-grid',
    level: 'section',
    code: '<OsmoGlowingDotsGrid rows={15} cols={25} color="#667eea" />',
    suggestedWith: ['osmo-interactive-pixel-grid', 'gsap-mouse-spotlight-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-highlight-text-on-scroll',
    name: 'OsmoHighlightTextOnScroll',
    displayName: 'Highlight Text on Scroll',
    source: 'osmo',
    categories: ['text', 'animation'],
    tags: ['highlight', 'text', 'scroll', 'progressive', 'reading', 'color', 'scrub'],
    description: 'Text where each word progressively highlights with color as the user scrolls, creating a guided reading experience with scrub-linked animation.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'As you scroll down this page, each word will progressively highlight, creating a beautiful reading experience.', required: false, description: 'Text content to highlight', group: 'content' },
      { name: 'highlightColor', type: 'color', default: '#667eea', required: false, description: 'Color words transition to on scroll', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-highlight-text-on-scroll',
    level: 'primitive',
    code: '<OsmoHighlightTextOnScroll text="Highlight this text on scroll" highlightColor="#667eea" />',
    suggestedWith: ['gsap-scroll-text-reveal', 'osmo-masked-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-horizontal-scrolling-sections',
    name: 'OsmoHorizontalScrollingSections',
    displayName: 'Horizontal Scrolling Sections',
    source: 'osmo',
    categories: ['section', 'layout', 'animation'],
    tags: ['horizontal', 'scroll', 'sections', 'pin', 'fullscreen', 'counter'],
    description: 'Full-viewport horizontal scrolling sections with pinned scroll and animated content reveal. Each panel shows a numbered counter with title and description.',
    previewImage: '',
    props: [
      {
        name: 'sections',
        type: 'array',
        required: false,
        description: 'Array of section objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Section heading' },
          { name: 'content', type: 'string', required: true, description: 'Section body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Section background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-horizontal-scrolling-sections',
    level: 'section',
    code: '<OsmoHorizontalScrollingSections />',
    suggestedWith: ['gsap-scroll-horizontal-section', 'osmo-stacking-cards-parallax'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-image-to-background-zoom',
    name: 'OsmoImageToBackgroundZoom',
    displayName: 'Image to Background Zoom',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['image', 'zoom', 'background', 'expand', 'fullscreen', 'gallery', 'clip-path'],
    description: 'A gallery where clicking an image zooms it to fill the entire container using clip-path animation. Click the background to dismiss.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with source and title',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'title', type: 'string', required: true, description: 'Image title overlay' },
        ],
      },
      { name: 'duration', type: 'number', default: 0.8, required: false, description: 'Zoom animation duration in seconds', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-image-to-background-zoom',
    level: 'section',
    code: '<OsmoImageToBackgroundZoom duration={0.8} />',
    suggestedWith: ['osmo-pixelated-image-reveal', 'osmo-before-after-split-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-interactive-pixel-grid',
    name: 'OsmoInteractivePixelGrid',
    displayName: 'Interactive Pixel Grid',
    source: 'osmo',
    categories: ['background', 'effect'],
    tags: ['pixel', 'grid', 'interactive', 'canvas', 'mouse', 'glow', 'trail'],
    description: 'A canvas-based interactive pixel grid that lights up with color when the cursor moves over it. Pixels fade and decay over time for a trailing effect.',
    previewImage: '',
    props: [
      { name: 'gridSize', type: 'number', default: 20, required: false, description: 'Size of each grid cell in pixels', group: 'style' },
      { name: 'colors', type: 'array', required: false, description: 'Array of hex color strings for pixels', group: 'style' },
      { name: 'interactionRadius', type: 'number', default: 3, required: false, description: 'Radius of cursor influence in grid cells', group: 'behavior' },
    ],
    dependencies: [],
    modulePath: 'osmo-interactive-pixel-grid',
    level: 'section',
    code: '<OsmoInteractivePixelGrid gridSize={20} interactionRadius={3} />',
    suggestedWith: ['osmo-glowing-dots-grid', 'gsap-mouse-spotlight-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-line-reveal-testimonials',
    name: 'OsmoLineRevealTestimonials',
    displayName: 'Line Reveal Testimonials',
    source: 'osmo',
    categories: ['testimonial', 'animation'],
    tags: ['testimonials', 'reveal', 'line', 'scroll', 'quotes', 'stagger'],
    description: 'Testimonial cards that reveal on scroll with a gradient divider line, staggered text lines, and author info animation.',
    previewImage: '',
    props: [
      {
        name: 'testimonials',
        type: 'array',
        required: false,
        description: 'Array of testimonial objects with quote, author, and role',
        group: 'content',
        itemSchema: [
          { name: 'quote', type: 'string', required: true, description: 'Testimonial quote text' },
          { name: 'author', type: 'string', required: true, description: 'Author name' },
          { name: 'role', type: 'string', required: true, description: 'Author role/company' },
        ],
      },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Animation speed multiplier', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-line-reveal-testimonials',
    level: 'section',
    code: '<OsmoLineRevealTestimonials speed={1} />',
    suggestedWith: ['osmo-sticky-features', 'gsap-scroll-stagger-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-magnetic-cursor',
    name: 'OsmoMagneticCursor',
    displayName: 'Magnetic Cursor',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['magnetic', 'cursor', 'hover', 'interactive', 'attraction', 'elastic'],
    description: 'A container that makes any child element with data-magnetic attribute react magnetically to the cursor, with elastic snap-back on leave.',
    previewImage: '',
    props: [
      { name: 'strength', type: 'number', default: 0.5, required: false, description: 'Magnetic pull strength (0-1)', group: 'behavior' },
      { name: 'radius', type: 'number', default: 150, required: false, description: 'Magnetic effect radius in pixels', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content with data-magnetic elements', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-magnetic-cursor',
    level: 'effect',
    code: '<OsmoMagneticCursor strength={0.5}><button data-magnetic>Hover me</button></OsmoMagneticCursor>',
    suggestedWith: ['gsap-mouse-magnetic-element', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'osmo-masked-text-reveal',
    name: 'OsmoMaskedTextReveal',
    displayName: 'Masked Text Reveal',
    source: 'osmo',
    categories: ['text', 'animation', 'hero'],
    tags: ['mask', 'text', 'reveal', 'scroll', 'image', 'clip-path', 'scale'],
    description: 'Large text with mix-blend-mode difference that scales down while a background image expands from center via clip-path animation on scroll.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'REVEAL', required: false, description: 'Display text', group: 'content' },
      { name: 'image', type: 'image', default: 'https://picsum.photos/seed/masked/1200/600', required: false, description: 'Background image that reveals', group: 'content' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Animation speed multiplier', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-masked-text-reveal',
    level: 'section',
    code: '<OsmoMaskedTextReveal text="REVEAL" image="/bg.jpg" />',
    suggestedWith: ['osmo-highlight-text-on-scroll', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-parallax-image-gallery',
    name: 'OsmoParallaxImageGallery',
    displayName: 'Parallax Image Gallery',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['parallax', 'gallery', 'images', 'masonry', 'scroll', 'depth'],
    description: 'A masonry-style two-column image gallery with alternating parallax directions on scroll. Images reveal with scale animation when entering view.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of gallery images with src and alt',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
        ],
      },
      { name: 'speed', type: 'number', default: 0.5, required: false, description: 'Parallax speed multiplier', group: 'behavior' },
      { name: 'gap', type: 'number', default: 24, required: false, description: 'Gap between images in pixels', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-parallax-image-gallery',
    level: 'section',
    code: '<OsmoParallaxImageGallery speed={0.5} gap={24} />',
    suggestedWith: ['gsap-scroll-parallax-images', 'osmo-image-to-background-zoom'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-pixelated-image-reveal',
    name: 'OsmoPixelatedImageReveal',
    displayName: 'Pixelated Image Reveal',
    source: 'osmo',
    categories: ['media', 'effect'],
    tags: ['pixelated', 'image', 'reveal', 'scroll', 'canvas', 'retro', 'transition'],
    description: 'An image that starts heavily pixelated and progressively sharpens to full resolution on scroll using canvas-based pixelation.',
    previewImage: '',
    props: [
      { name: 'image', type: 'image', default: 'https://picsum.photos/seed/pixel/800/500', required: false, description: 'Image to reveal', group: 'content' },
      { name: 'pixelSize', type: 'number', default: 20, required: false, description: 'Initial pixel block size', group: 'style' },
      { name: 'revealSpeed', type: 'number', default: 1, required: false, description: 'Reveal animation speed multiplier', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-pixelated-image-reveal',
    level: 'primitive',
    code: '<OsmoPixelatedImageReveal image="/photo.jpg" pixelSize={20} />',
    suggestedWith: ['osmo-before-after-split-slider', 'osmo-image-to-background-zoom'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-rotating-image-trail',
    name: 'OsmoRotatingImageTrail',
    displayName: 'Rotating Image Trail',
    source: 'osmo',
    categories: ['effect', 'media'],
    tags: ['trail', 'images', 'mouse', 'rotate', 'cursor', 'follow', 'spawn'],
    description: 'Images that spawn and rotate along the mouse trail as the cursor moves. Each image pops in with scale animation and fades out over time.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs for the trail', group: 'content' },
      { name: 'trailLength', type: 'number', default: 8, required: false, description: 'Maximum number of trail images visible', group: 'behavior' },
      { name: 'rotation', type: 'number', default: 15, required: false, description: 'Maximum rotation angle in degrees', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-rotating-image-trail',
    level: 'section',
    code: '<OsmoRotatingImageTrail trailLength={8} rotation={15} />',
    suggestedWith: ['osmo-stacking-image-trail', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-rotating-text',
    name: 'OsmoRotatingText',
    displayName: 'Rotating Text',
    source: 'osmo',
    categories: ['text', 'animation'],
    tags: ['rotating', 'text', 'words', 'cycle', 'typewriter', 'loop'],
    description: 'A text rotator that cycles through an array of words with slide up/down entrance and exit animations using GSAP.',
    previewImage: '',
    props: [
      { name: 'words', type: 'array', required: false, description: 'Array of words to cycle through', group: 'content' },
      { name: 'speed', type: 'number', default: 2, required: false, description: 'Duration each word is displayed in seconds', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'up', required: false, options: ['up', 'down'], description: 'Slide direction of the text rotation', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-rotating-text',
    level: 'primitive',
    code: '<OsmoRotatingText words={["Creative", "Beautiful", "Powerful"]} speed={2} />',
    suggestedWith: ['gsap-text-kinetic-typography', 'osmo-text-scramble'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scaling-hamburger-navigation',
    name: 'OsmoScalingHamburgerNavigation',
    displayName: 'Scaling Hamburger Navigation',
    source: 'osmo',
    categories: ['navigation'],
    tags: ['hamburger', 'navigation', 'scale', 'overlay', 'menu', 'circle', 'expand'],
    description: 'A hamburger menu that triggers a scaling circle overlay expanding from the button. Links animate in with a bouncy stagger effect.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of navigation items with label and href',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Link text' },
          { name: 'href', type: 'string', required: true, description: 'Link URL' },
        ],
      },
      { name: 'bgColor', type: 'color', default: '#0a0a0a', required: false, description: 'Overlay background color', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-scaling-hamburger-navigation',
    level: 'primitive',
    code: '<OsmoScalingHamburgerNavigation bgColor="#0a0a0a" />',
    suggestedWith: ['osmo-bold-fullscreen-navigation', 'osmo-apple-dock-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-stacking-cards-parallax',
    name: 'OsmoStackingCardsParallax',
    displayName: 'Stacking Cards Parallax',
    source: 'osmo',
    categories: ['section', 'card', 'animation'],
    tags: ['stacking', 'cards', 'parallax', 'pin', 'scroll', 'overlay'],
    description: 'Full-height cards that pin and stack on top of each other as the user scrolls. Previous cards scale down and fade, creating a layered parallax effect.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, description, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card heading' },
          { name: 'description', type: 'string', required: true, description: 'Card body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Card background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-stacking-cards-parallax',
    level: 'section',
    code: '<OsmoStackingCardsParallax />',
    suggestedWith: ['osmo-stacking-cards-slider', 'osmo-horizontal-scrolling-sections'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-stacking-cards-slider',
    name: 'OsmoStackingCardsSlider',
    displayName: 'Stacking Cards Slider',
    source: 'osmo',
    categories: ['section', 'card', 'animation'],
    tags: ['stacking', 'cards', 'slider', 'pin', 'scroll', 'steps'],
    description: 'Cards that pin and stack with offset positioning as the user scrolls. Each new card slides over the previous one which scales down and dims.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card step title' },
          { name: 'content', type: 'string', required: true, description: 'Card body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Card background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-stacking-cards-slider',
    level: 'section',
    code: '<OsmoStackingCardsSlider />',
    suggestedWith: ['osmo-stacking-cards-parallax', 'osmo-dropping-cards-stack'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-stacking-image-trail',
    name: 'OsmoStackingImageTrail',
    displayName: 'Stacking Image Trail',
    source: 'osmo',
    categories: ['effect', 'media'],
    tags: ['trail', 'images', 'stacking', 'mouse', 'cursor', 'spawn', 'depth'],
    description: 'Images that spawn at the cursor position and stack on top of each other. Older images scale down and fade for a depth-of-stack effect.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs for the trail', group: 'content' },
      { name: 'stackCount', type: 'number', default: 5, required: false, description: 'Maximum number of stacked images visible', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-stacking-image-trail',
    level: 'section',
    code: '<OsmoStackingImageTrail stackCount={5} />',
    suggestedWith: ['osmo-rotating-image-trail', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-sticky-features',
    name: 'OsmoStickyFeatures',
    displayName: 'Sticky Features',
    source: 'osmo',
    categories: ['feature', 'section'],
    tags: ['sticky', 'features', 'scroll', 'split', 'image', 'text', 'showcase'],
    description: 'A split-layout feature showcase with sticky text on the left and an image on the right. Each feature section reveals on scroll with GSAP animations.',
    previewImage: '',
    props: [
      {
        name: 'features',
        type: 'array',
        required: false,
        description: 'Array of feature objects with title, description, and image',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Feature heading' },
          { name: 'description', type: 'string', required: true, description: 'Feature body text' },
          { name: 'image', type: 'image', required: true, description: 'Feature image URL' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-sticky-features',
    level: 'section',
    code: '<OsmoStickyFeatures />',
    suggestedWith: ['osmo-stacking-cards-parallax', 'osmo-line-reveal-testimonials'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-text-scramble',
    name: 'OsmoTextScramble',
    displayName: 'Text Scramble',
    source: 'osmo',
    categories: ['text', 'effect'],
    tags: ['scramble', 'text', 'decode', 'glitch', 'hover', 'reveal', 'cipher'],
    description: 'A text scramble effect that decodes characters progressively using random character replacement. Triggered by hover, scroll, or page load.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'OSMO SCRAMBLE', required: false, description: 'Text to display and scramble', group: 'content' },
      { name: 'speed', type: 'number', default: 30, required: false, description: 'Frame delay in milliseconds (lower = faster)', group: 'behavior' },
      { name: 'trigger', type: 'select', default: 'hover', required: false, options: ['hover', 'scroll', 'load'], description: 'What triggers the scramble animation', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-text-scramble',
    level: 'primitive',
    code: '<OsmoTextScramble text="SCRAMBLE" trigger="hover" />',
    suggestedWith: ['gsap-text-scramble', 'osmo-rotating-text'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-three-d-image-carousel',
    name: 'Osmo3DImageCarousel',
    displayName: '3D Image Carousel',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['3d', 'carousel', 'images', 'rotate', 'perspective', 'gallery', 'autoplay'],
    description: 'A 3D rotating image carousel with CSS perspective transforms. Images are positioned in a circle and can auto-rotate or be navigated with prev/next buttons.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of carousel images with src and alt',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
        ],
      },
      { name: 'autoplay', type: 'boolean', default: true, required: false, description: 'Auto-rotate the carousel', group: 'behavior' },
      { name: 'perspective', type: 'number', default: 1000, required: false, description: 'CSS perspective value in pixels', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'osmo-three-d-image-carousel',
    level: 'section',
    code: '<Osmo3DImageCarousel autoplay perspective={1000} />',
    suggestedWith: ['gsap-drag-infinite-slider', 'osmo-parallax-image-gallery'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-variable-font-weight-hover',
    name: 'OsmoVariableFontWeightHover',
    displayName: 'Variable Font Weight Hover',
    source: 'osmo',
    categories: ['text', 'effect'],
    tags: ['variable-font', 'font-weight', 'hover', 'interactive', 'proximity', 'typography'],
    description: 'Text where each character dynamically adjusts its font weight based on cursor proximity, creating a fluid variable font effect on hover.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'HOVER OVER THIS TEXT', required: false, description: 'Text to display', group: 'content' },
      { name: 'minWeight', type: 'number', default: 100, required: false, description: 'Minimum font weight when cursor is far', group: 'style' },
      { name: 'maxWeight', type: 'number', default: 900, required: false, description: 'Maximum font weight when cursor is close', group: 'style' },
    ],
    dependencies: [],
    modulePath: 'osmo-variable-font-weight-hover',
    level: 'primitive',
    code: '<OsmoVariableFontWeightHover text="HOVER OVER THIS TEXT" minWeight={100} maxWeight={900} />',
    suggestedWith: ['gsap-text-kinetic-typography', 'osmo-text-scramble'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-download-button',
    name: 'OsmoDownloadButton',
    displayName: 'Download Button',
    source: 'osmo',
    categories: ['button', 'animation'],
    tags: ['download', 'button', 'fetch', 'blob', 'animated', 'checkmark', 'success', 'file'],
    description: 'An animated download button that fetches a file via blob URL and triggers a browser download. Shows idle, downloading, and success states with smooth SVG transitions including an arrow-to-checkmark animation.',
    previewImage: '',
    props: [
      { name: 'src', type: 'string', default: 'https://example.com/file.pdf', required: false, description: 'URL of the file to download', group: 'content' },
      { name: 'fileName', type: 'string', default: '', required: false, description: 'Custom filename for the downloaded file (auto-detected from URL if empty)', group: 'content' },
      { name: 'label', type: 'string', default: 'Download', required: false, description: 'Button label text', group: 'content' },
      { name: 'successLabel', type: 'string', default: 'Downloaded!', required: false, description: 'Label shown after successful download', group: 'content' },
      { name: 'backgroundColor', type: 'color', default: '#0065e1', required: false, description: 'Button background color', group: 'style' },
      { name: 'hoverColor', type: 'color', default: '#0a75f8', required: false, description: 'Button hover background color', group: 'style' },
      { name: 'textColor', type: 'color', default: '#f2f2f2', required: false, description: 'Button text and icon color', group: 'style' },
    ],
    dependencies: [],
    modulePath: 'osmo-download-button',
    level: 'primitive',
    code: '<OsmoDownloadButton src="https://example.com/file.pdf" label="Download" />',
    suggestedWith: [],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-blob-cursor',
    name: 'OsmoBlobCursor',
    displayName: 'Blob Cursor',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'blob', 'interactive', 'mouse', 'follow'],
    description: 'A blob shape that follows the cursor with smooth spring interpolation and radial gradient glow effect.',
    previewImage: '',
    props: [
      { name: 'color', type: 'color', required: false, default: '#8b5cf6', description: 'Blob color', group: 'style' },
      { name: 'size', type: 'number', required: false, default: 200, description: 'Blob size in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-blob-cursor',
    level: 'effect',
    code: '<OsmoBlobCursor color="#8b5cf6" size={200} />',
    suggestedWith: ['osmo-cursor-glow-effect', 'osmo-cursor-spotlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-ripple-effect',
    name: 'OsmoRippleEffect',
    displayName: 'Ripple Effect',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['ripple', 'click', 'interactive', 'wave', 'mouse'],
    description: 'A ripple animation that expands from the click position with configurable color, duration, and size.',
    previewImage: '',
    props: [
      { name: 'color', type: 'color', required: false, default: '#8b5cf6', description: 'Ripple border color', group: 'style' },
      { name: 'duration', type: 'number', required: false, default: 0.8, description: 'Ripple animation duration in seconds', group: 'behavior' },
      { name: 'maxSize', type: 'number', required: false, default: 300, description: 'Maximum ripple diameter in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-ripple-effect',
    level: 'effect',
    code: '<OsmoRippleEffect color="#8b5cf6" duration={0.8} maxSize={300} />',
    suggestedWith: ['osmo-blob-cursor', 'osmo-cursor-glow-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-cursor-glow-effect',
    name: 'OsmoCursorGlowEffect',
    displayName: 'Cursor Glow Effect',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'glow', 'interactive', 'mouse', 'radial', 'ambient'],
    description: 'A soft glow effect that follows the cursor with spring physics and screen blend mode.',
    previewImage: '',
    props: [
      { name: 'color', type: 'color', required: false, default: '#06b6d4', description: 'Glow color', group: 'style' },
      { name: 'size', type: 'number', required: false, default: 300, description: 'Glow diameter in pixels', group: 'style' },
      { name: 'intensity', type: 'number', required: false, default: 0.6, description: 'Glow intensity (0-1)', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-cursor-glow-effect',
    level: 'effect',
    code: '<OsmoCursorGlowEffect color="#06b6d4" size={300} intensity={0.6} />',
    suggestedWith: ['osmo-blob-cursor', 'osmo-cursor-spotlight'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-cursor-spotlight',
    name: 'OsmoCursorSpotlight',
    displayName: 'Cursor Spotlight',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'spotlight', 'reveal', 'mask', 'interactive', 'mouse'],
    description: 'A spotlight effect that reveals hidden content beneath a dark overlay as the cursor moves.',
    previewImage: '',
    props: [
      { name: 'size', type: 'number', required: false, default: 250, description: 'Spotlight diameter in pixels', group: 'style' },
      { name: 'borderColor', type: 'color', required: false, default: '#f59e0b', description: 'Spotlight border glow color', group: 'style' },
      { name: 'content', type: 'string', required: false, default: 'Hidden content revealed by spotlight. Move your cursor to explore the darkness.', description: 'Text content to reveal', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-cursor-spotlight',
    level: 'effect',
    code: '<OsmoCursorSpotlight size={250} borderColor="#f59e0b" />',
    suggestedWith: ['osmo-cursor-glow-effect', 'osmo-blob-cursor'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-color-transition-scroll',
    name: 'OsmoColorTransitionScroll',
    displayName: 'Color Transition Scroll',
    source: 'osmo',
    categories: ['effect', 'animation', 'background'],
    tags: ['color', 'transition', 'scroll', 'background', 'gradient', 'sections'],
    description: 'Background color transitions smoothly between multiple colors as the user scrolls, with labeled section indicators.',
    previewImage: '',
    props: [
      { name: 'colors', type: 'array', required: false, description: 'Array of hex color strings for scroll transitions', group: 'style' },
      { name: 'labels', type: 'array', required: false, description: 'Array of label strings for each color section', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-color-transition-scroll',
    level: 'effect',
    code: '<OsmoColorTransitionScroll colors={["#0f172a", "#4c1d95", "#2563eb"]} labels={["Dark", "Purple", "Blue"]} />',
    suggestedWith: ['osmo-scroll-progress-circle', 'osmo-text-blur-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scroll-snap-gallery',
    name: 'OsmoScrollSnapGallery',
    displayName: 'Scroll Snap Gallery',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['scroll', 'snap', 'gallery', 'images', 'fullscreen', 'vertical'],
    description: 'A vertical snap-scroll image gallery where each slide fills the viewport with scale and content reveal animations.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of gallery images with src, alt, and caption',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
          { name: 'caption', type: 'string', required: false, description: 'Image caption' },
        ],
      },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-scroll-snap-gallery',
    level: 'effect',
    code: '<OsmoScrollSnapGallery />',
    suggestedWith: ['osmo-scroll-fade-gallery', 'osmo-hover-zoom-gallery'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scroll-progress-circle',
    name: 'OsmoScrollProgressCircle',
    displayName: 'Scroll Progress Circle',
    source: 'osmo',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'progress', 'circle', 'indicator', 'svg', 'percentage'],
    description: 'A circular SVG-based scroll progress indicator fixed in the corner showing current scroll percentage.',
    previewImage: '',
    props: [
      { name: 'size', type: 'number', required: false, default: 80, description: 'Circle diameter in pixels', group: 'style' },
      { name: 'strokeWidth', type: 'number', required: false, default: 4, description: 'Stroke width in pixels', group: 'style' },
      { name: 'color', type: 'color', required: false, default: '#8b5cf6', description: 'Progress stroke color', group: 'style' },
      { name: 'trackColor', type: 'color', required: false, default: '#ffffff15', description: 'Track background color', group: 'style' },
      { name: 'showPercentage', type: 'boolean', required: false, default: true, description: 'Show percentage number', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-scroll-progress-circle',
    level: 'effect',
    code: '<OsmoScrollProgressCircle size={80} color="#8b5cf6" showPercentage />',
    suggestedWith: ['osmo-color-transition-scroll', 'osmo-scroll-morph-header'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scroll-fade-gallery',
    name: 'OsmoScrollFadeGallery',
    displayName: 'Scroll Fade Gallery',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['scroll', 'fade', 'gallery', 'images', 'grid', 'reveal'],
    description: 'A responsive image grid where each image fades in with scale and vertical movement as it enters the viewport on scroll.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of gallery images with src and alt',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
        ],
      },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-scroll-fade-gallery',
    level: 'effect',
    code: '<OsmoScrollFadeGallery />',
    suggestedWith: ['osmo-scroll-snap-gallery', 'osmo-hover-zoom-gallery'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scroll-ticker',
    name: 'OsmoScrollTicker',
    displayName: 'Scroll Ticker',
    source: 'osmo',
    categories: ['animation', 'text'],
    tags: ['scroll', 'ticker', 'marquee', 'horizontal', 'news', 'text'],
    description: 'A horizontal news ticker that scrolls its content based on the page scroll position with configurable direction and speed.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings to display', group: 'content' },
      { name: 'speed', type: 'number', required: false, default: 300, description: 'Scroll distance multiplier in pixels', group: 'behavior' },
      { name: 'direction', type: 'select', required: false, default: 'left', options: ['left', 'right'], description: 'Scroll direction', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-scroll-ticker',
    level: 'effect',
    code: '<OsmoScrollTicker items={["Breaking News", "Product Launch"]} speed={300} />',
    suggestedWith: ['osmo-infinite-logo-slider', 'osmo-css-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-infinite-logo-slider',
    name: 'OsmoInfiniteLogoSlider',
    displayName: 'Infinite Logo Slider',
    source: 'osmo',
    categories: ['animation', 'media'],
    tags: ['logo', 'slider', 'infinite', 'carousel', 'brand', 'loop', 'marquee'],
    description: 'An infinitely looping logo carousel with smooth linear animation and optional pause on hover.',
    previewImage: '',
    props: [
      {
        name: 'logos',
        type: 'array',
        required: false,
        description: 'Array of logo objects with name and color',
        group: 'content',
        itemSchema: [
          { name: 'name', type: 'string', required: true, description: 'Company name' },
          { name: 'color', type: 'color', required: false, description: 'Brand color' },
        ],
      },
      { name: 'speed', type: 'number', required: false, default: 25, description: 'Animation duration in seconds (higher = slower)', group: 'behavior' },
      { name: 'pauseOnHover', type: 'boolean', required: false, default: true, description: 'Pause animation on hover', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-infinite-logo-slider',
    level: 'effect',
    code: '<OsmoInfiniteLogoSlider speed={25} pauseOnHover />',
    suggestedWith: ['osmo-scroll-ticker', 'osmo-css-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-parallax-cards',
    name: 'OsmoParallaxCards',
    displayName: 'Parallax Cards',
    source: 'osmo',
    categories: ['card', 'animation'],
    tags: ['parallax', 'cards', 'scroll', 'depth', 'grid', '3d'],
    description: 'A grid of cards with alternating parallax scroll directions, rotation, and scale effects for a dynamic depth feel.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, description, and color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card title' },
          { name: 'description', type: 'string', required: true, description: 'Card description' },
          { name: 'color', type: 'color', required: true, description: 'Accent color' },
        ],
      },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-parallax-cards',
    level: 'effect',
    code: '<OsmoParallaxCards />',
    suggestedWith: ['osmo-hover-tilt-card', 'osmo-hover-lift-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-scroll-morph-header',
    name: 'OsmoScrollMorphHeader',
    displayName: 'Scroll Morph Header',
    source: 'osmo',
    categories: ['navigation', 'animation'],
    tags: ['header', 'morph', 'scroll', 'sticky', 'navbar', 'shrink', 'blur'],
    description: 'A sticky header that morphs on scroll, shrinking in height, resizing the title, and revealing a backdrop blur background.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', required: false, default: 'Morphing Header', description: 'Header title text', group: 'content' },
      { name: 'bgColor', type: 'color', required: false, default: '#0f172a', description: 'Header background color', group: 'style' },
      { name: 'accentColor', type: 'color', required: false, default: '#8b5cf6', description: 'CTA button color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-scroll-morph-header',
    level: 'effect',
    code: '<OsmoScrollMorphHeader title="Morphing Header" bgColor="#0f172a" accentColor="#8b5cf6" />',
    suggestedWith: ['osmo-scroll-progress-circle', 'osmo-slide-in-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-text-split-hover',
    name: 'OsmoTextSplitHover',
    displayName: 'Text Split Hover',
    source: 'osmo',
    categories: ['text', 'effect'],
    tags: ['text', 'split', 'hover', 'characters', 'stagger', 'interactive'],
    description: 'Text that splits vertically on hover with alternating characters moving up and down with staggered timing.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'SPLIT HOVER', description: 'Text to display', group: 'content' },
      { name: 'splitOffset', type: 'number', required: false, default: 20, description: 'Vertical split distance in pixels', group: 'style' },
      { name: 'color', type: 'color', required: false, default: '#8b5cf6', description: 'Text color on hover', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-text-split-hover',
    level: 'effect',
    code: '<OsmoTextSplitHover text="SPLIT HOVER" splitOffset={20} color="#8b5cf6" />',
    suggestedWith: ['osmo-text-gradient-animation', 'osmo-text-blur-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-image-reveal-slider',
    name: 'OsmoImageRevealSlider',
    displayName: 'Image Reveal Slider',
    source: 'osmo',
    categories: ['media', 'animation'],
    tags: ['image', 'reveal', 'slider', 'before', 'after', 'compare', 'drag'],
    description: 'A draggable before/after image comparison slider with a centered drag handle and labeled sides.',
    previewImage: '',
    props: [
      { name: 'beforeImage', type: 'image', required: false, default: 'https://picsum.photos/seed/reveal-before/800/500?grayscale', description: 'Before image URL', group: 'content' },
      { name: 'afterImage', type: 'image', required: false, default: 'https://picsum.photos/seed/reveal-after/800/500', description: 'After image URL', group: 'content' },
      { name: 'height', type: 'number', required: false, default: 400, description: 'Container height in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-image-reveal-slider',
    level: 'effect',
    code: '<OsmoImageRevealSlider beforeImage="/before.jpg" afterImage="/after.jpg" height={400} />',
    suggestedWith: ['osmo-hover-expand-image', 'osmo-hover-zoom-gallery'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-hover-tilt-card',
    name: 'OsmoHoverTiltCard',
    displayName: 'Hover Tilt Card',
    source: 'osmo',
    categories: ['card', 'effect'],
    tags: ['tilt', '3d', 'hover', 'card', 'perspective', 'glare', 'interactive'],
    description: 'A card that tilts in 3D space following the cursor with spring physics, glare effect, and configurable max tilt angle.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', required: false, default: '3D Tilt Card', description: 'Card title', group: 'content' },
      { name: 'description', type: 'string', required: false, default: 'Hover over this card to see it tilt in 3D space.', description: 'Card description', group: 'content' },
      { name: 'glareColor', type: 'color', required: false, default: '#ffffff', description: 'Glare highlight color', group: 'style' },
      { name: 'maxTilt', type: 'number', required: false, default: 15, description: 'Maximum tilt angle in degrees', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-hover-tilt-card',
    level: 'effect',
    code: '<OsmoHoverTiltCard title="3D Tilt Card" maxTilt={15} />',
    suggestedWith: ['osmo-hover-lift-card', 'osmo-parallax-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-text-blur-reveal',
    name: 'OsmoTextBlurReveal',
    displayName: 'Text Blur Reveal',
    source: 'osmo',
    categories: ['text', 'animation'],
    tags: ['text', 'blur', 'reveal', 'scroll', 'focus', 'words', 'progressive'],
    description: 'Text where each word progressively un-blurs and fades in as the user scrolls, creating a focus reveal reading effect.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Design is not just what it looks like and feels like. Design is how it works.', description: 'Text content to reveal', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-text-blur-reveal',
    level: 'effect',
    code: '<OsmoTextBlurReveal text="Design is how it works." />',
    suggestedWith: ['osmo-text-reveal-lines', 'osmo-highlight-text-on-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-grid-hover-effect',
    name: 'OsmoGridHoverEffect',
    displayName: 'Grid Hover Effect',
    source: 'osmo',
    categories: ['card', 'effect'],
    tags: ['grid', 'hover', 'items', 'highlight', 'interactive', 'features'],
    description: 'A feature grid where hovering an item highlights it with background, border color change, and icon scale animation.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of grid items with title, description, and icon',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Item title' },
          { name: 'description', type: 'string', required: true, description: 'Item description' },
          { name: 'icon', type: 'string', required: true, description: 'Icon emoji' },
        ],
      },
      { name: 'columns', type: 'number', required: false, default: 3, description: 'Number of grid columns', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-grid-hover-effect',
    level: 'effect',
    code: '<OsmoGridHoverEffect columns={3} />',
    suggestedWith: ['osmo-hover-lift-card', 'osmo-hover-tilt-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-hover-expand-image',
    name: 'OsmoHoverExpandImage',
    displayName: 'Hover Expand Image',
    source: 'osmo',
    categories: ['media', 'effect'],
    tags: ['hover', 'expand', 'image', 'gallery', 'accordion', 'flexible'],
    description: 'A horizontal image gallery where images expand on hover and compress neighboring images, with title reveal animations.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with src, alt, and title',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
          { name: 'title', type: 'string', required: true, description: 'Image title' },
        ],
      },
      { name: 'height', type: 'number', required: false, default: 500, description: 'Gallery height in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-hover-expand-image',
    level: 'effect',
    code: '<OsmoHoverExpandImage height={500} />',
    suggestedWith: ['osmo-hover-zoom-gallery', 'osmo-image-reveal-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-hover-lift-card',
    name: 'OsmoHoverLiftCard',
    displayName: 'Hover Lift Card',
    source: 'osmo',
    categories: ['card', 'effect'],
    tags: ['hover', 'lift', 'card', 'shadow', 'elevation', 'pricing'],
    description: 'Cards that lift up on hover with colored shadow, animated top border, and configurable lift amount.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, description, tag, and color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card title' },
          { name: 'description', type: 'string', required: true, description: 'Card description' },
          { name: 'tag', type: 'string', required: true, description: 'Card tag or price' },
          { name: 'color', type: 'color', required: true, description: 'Accent color' },
        ],
      },
      { name: 'liftAmount', type: 'number', required: false, default: 12, description: 'Lift distance in pixels', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-hover-lift-card',
    level: 'effect',
    code: '<OsmoHoverLiftCard liftAmount={12} />',
    suggestedWith: ['osmo-hover-tilt-card', 'osmo-grid-hover-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-hover-zoom-gallery',
    name: 'OsmoHoverZoomGallery',
    displayName: 'Hover Zoom Gallery',
    source: 'osmo',
    categories: ['media', 'effect'],
    tags: ['hover', 'zoom', 'gallery', 'images', 'grid', 'scale', 'dim'],
    description: 'An image grid gallery where the hovered image zooms in while other images dim, with title reveal and border highlight.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with src, alt, and title',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
          { name: 'title', type: 'string', required: true, description: 'Image title' },
        ],
      },
      { name: 'zoomScale', type: 'number', required: false, default: 1.15, description: 'Zoom scale factor on hover', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-hover-zoom-gallery',
    level: 'effect',
    code: '<OsmoHoverZoomGallery zoomScale={1.15} />',
    suggestedWith: ['osmo-scroll-fade-gallery', 'osmo-hover-expand-image'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-typewriter-cursor',
    name: 'OsmoTypewriterCursor',
    displayName: 'Typewriter Cursor',
    source: 'osmo',
    categories: ['text', 'effect'],
    tags: ['typewriter', 'cursor', 'typing', 'text', 'loop', 'blink', 'cycle'],
    description: 'A typewriter effect that cycles through phrases with typing and deleting animations and a blinking cursor.',
    previewImage: '',
    props: [
      { name: 'phrases', type: 'array', required: false, description: 'Array of text strings to cycle through', group: 'content' },
      { name: 'typingSpeed', type: 'number', required: false, default: 80, description: 'Typing speed in ms per character', group: 'behavior' },
      { name: 'deletingSpeed', type: 'number', required: false, default: 40, description: 'Deleting speed in ms per character', group: 'behavior' },
      { name: 'pauseDuration', type: 'number', required: false, default: 2000, description: 'Pause duration before deleting in ms', group: 'behavior' },
      { name: 'cursorColor', type: 'color', required: false, default: '#8b5cf6', description: 'Cursor color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-typewriter-cursor',
    level: 'effect',
    code: '<OsmoTypewriterCursor phrases={["Developer", "Designer", "Creator"]} typingSpeed={80} />',
    suggestedWith: ['osmo-text-gradient-animation', 'osmo-text-split-hover'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-text-gradient-animation',
    name: 'OsmoTextGradientAnimation',
    displayName: 'Text Gradient Animation',
    source: 'osmo',
    categories: ['text', 'effect'],
    tags: ['text', 'gradient', 'animation', 'color', 'loop', 'shimmer'],
    description: 'Text with an animated multi-color gradient that continuously shifts across the text using background-clip.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Gradient Text', description: 'Text to display', group: 'content' },
      { name: 'colors', type: 'array', required: false, description: 'Array of hex color strings for the gradient', group: 'style' },
      { name: 'speed', type: 'number', required: false, default: 4, description: 'Animation cycle duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-text-gradient-animation',
    level: 'effect',
    code: '<OsmoTextGradientAnimation text="Gradient Text" speed={4} />',
    suggestedWith: ['osmo-typewriter-cursor', 'osmo-text-split-hover'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-text-reveal-lines',
    name: 'OsmoTextRevealLines',
    displayName: 'Text Reveal Lines',
    source: 'osmo',
    categories: ['text', 'animation'],
    tags: ['text', 'reveal', 'lines', 'scroll', 'clip-path', 'stagger'],
    description: 'Text lines that reveal one by one on scroll with clip-path, vertical movement, and fade-in animations.',
    previewImage: '',
    props: [
      { name: 'lines', type: 'array', required: false, description: 'Array of text line strings', group: 'content' },
      { name: 'staggerDelay', type: 'number', required: false, default: 0.08, description: 'Delay between each line reveal', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-text-reveal-lines',
    level: 'effect',
    code: '<OsmoTextRevealLines lines={["We craft digital", "experiences that", "push boundaries."]} />',
    suggestedWith: ['osmo-text-blur-reveal', 'osmo-text-split-hover'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-animated-background-grid',
    name: 'OsmoAnimatedBackgroundGrid',
    displayName: 'Animated Background Grid',
    source: 'osmo',
    categories: ['background', 'effect'],
    tags: ['grid', 'dots', 'background', 'animated', 'pulse', 'wave', 'ambient'],
    description: 'An animated dot grid background with wave-like pulsating animations creating an ambient visual effect.',
    previewImage: '',
    props: [
      { name: 'rows', type: 'number', required: false, default: 12, description: 'Number of dot rows', group: 'style' },
      { name: 'cols', type: 'number', required: false, default: 20, description: 'Number of dot columns', group: 'style' },
      { name: 'dotSize', type: 'number', required: false, default: 3, description: 'Dot diameter in pixels', group: 'style' },
      { name: 'dotColor', type: 'color', required: false, default: '#8b5cf6', description: 'Dot color', group: 'style' },
      { name: 'speed', type: 'number', required: false, default: 3, description: 'Animation cycle speed in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-animated-background-grid',
    level: 'effect',
    code: '<OsmoAnimatedBackgroundGrid rows={12} cols={20} dotColor="#8b5cf6" speed={3} />',
    suggestedWith: ['osmo-glowing-dots-grid', 'osmo-interactive-pixel-grid'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'osmo-slide-in-navigation',
    name: 'OsmoSlideInNavigation',
    displayName: 'Slide-in Navigation',
    source: 'osmo',
    categories: ['navigation', 'animation'],
    tags: ['navigation', 'slide', 'menu', 'hamburger', 'overlay', 'sidebar', 'panel'],
    description: 'A slide-in navigation panel triggered by a hamburger button, with staggered link animations and backdrop blur overlay.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of navigation items with label and href',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Link text' },
          { name: 'href', type: 'string', required: true, description: 'Link URL' },
        ],
      },
      { name: 'bgColor', type: 'color', required: false, default: '#0a0a0a', description: 'Panel background color', group: 'style' },
      { name: 'accentColor', type: 'color', required: false, default: '#8b5cf6', description: 'Link hover color', group: 'style' },
      { name: 'direction', type: 'select', required: false, default: 'right', options: ['left', 'right'], description: 'Slide-in direction', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'osmo-slide-in-navigation',
    level: 'effect',
    code: '<OsmoSlideInNavigation bgColor="#0a0a0a" direction="right" />',
    suggestedWith: ['osmo-scroll-morph-header', 'osmo-scaling-hamburger-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
]
