'use client'

import { lazy, type ComponentType } from 'react'

type LazyComponent = React.LazyExoticComponent<ComponentType<Record<string, unknown>>>

// Dynamic import map: registry ID -> lazy-loaded component
const COMPONENT_MAP: Record<string, () => Promise<{ default: ComponentType<Record<string, unknown>> }>> = {
  // === Builtin elements (20) ===
  'builtin-section': () => import('@/components/registry/builtin/section'),
  'builtin-container': () => import('@/components/registry/builtin/container'),
  'builtin-div-block': () => import('@/components/registry/builtin/div-block'),
  'builtin-flex-box': () => import('@/components/registry/builtin/flex-box'),
  'builtin-grid-layout': () => import('@/components/registry/builtin/grid-layout'),
  'builtin-columns': () => import('@/components/registry/builtin/columns'),
  'builtin-heading': () => import('@/components/registry/builtin/heading'),
  'builtin-paragraph': () => import('@/components/registry/builtin/paragraph'),
  'builtin-text-block': () => import('@/components/registry/builtin/text-block'),
  'builtin-link-element': () => import('@/components/registry/builtin/link-element'),
  'builtin-rich-text': () => import('@/components/registry/builtin/rich-text'),
  'builtin-list-element': () => import('@/components/registry/builtin/list-element'),
  'builtin-image': () => import('@/components/registry/builtin/image-element'),
  'builtin-video': () => import('@/components/registry/builtin/video-element'),
  'builtin-form-block': () => import('@/components/registry/builtin/form-block'),
  'builtin-input-field': () => import('@/components/registry/builtin/input-field'),
  'builtin-text-area': () => import('@/components/registry/builtin/text-area-field'),
  'builtin-select-field': () => import('@/components/registry/builtin/select-field'),
  'builtin-button-element': () => import('@/components/registry/builtin/button-element'),
  'builtin-link-block': () => import('@/components/registry/builtin/link-block'),

  // === Shadcn UI (33) ===
  'shadcn-accordion': () => import('@/components/registry/shadcn/accordion'),
  'shadcn-alert': () => import('@/components/registry/shadcn/alert'),
  'shadcn-avatar': () => import('@/components/registry/shadcn/avatar'),
  'shadcn-badge': () => import('@/components/registry/shadcn/badge'),
  'shadcn-breadcrumb': () => import('@/components/registry/shadcn/breadcrumb'),
  'shadcn-button': () => import('@/components/registry/shadcn/button'),
  'shadcn-card': () => import('@/components/registry/shadcn/card'),
  'shadcn-carousel': () => import('@/components/registry/shadcn/carousel'),
  'shadcn-checkbox': () => import('@/components/registry/shadcn/checkbox'),
  'shadcn-collapsible': () => import('@/components/registry/shadcn/collapsible'),
  'shadcn-dialog': () => import('@/components/registry/shadcn/dialog'),
  'shadcn-dropdown-menu': () => import('@/components/registry/shadcn/dropdown-menu'),
  'shadcn-hover-card': () => import('@/components/registry/shadcn/hover-card'),
  'shadcn-input': () => import('@/components/registry/shadcn/input'),
  'shadcn-label': () => import('@/components/registry/shadcn/label'),
  'shadcn-navigation-menu': () => import('@/components/registry/shadcn/navigation-menu'),
  'shadcn-pagination': () => import('@/components/registry/shadcn/pagination'),
  'shadcn-popover': () => import('@/components/registry/shadcn/popover'),
  'shadcn-progress': () => import('@/components/registry/shadcn/progress'),
  'shadcn-radio-group': () => import('@/components/registry/shadcn/radio-group'),
  'shadcn-scroll-area': () => import('@/components/registry/shadcn/scroll-area'),
  'shadcn-select': () => import('@/components/registry/shadcn/select'),
  'shadcn-separator': () => import('@/components/registry/shadcn/separator'),
  'shadcn-sheet': () => import('@/components/registry/shadcn/sheet'),
  'shadcn-skeleton': () => import('@/components/registry/shadcn/skeleton'),
  'shadcn-slider': () => import('@/components/registry/shadcn/slider'),
  'shadcn-switch': () => import('@/components/registry/shadcn/switch'),
  'shadcn-table': () => import('@/components/registry/shadcn/table'),
  'shadcn-tabs': () => import('@/components/registry/shadcn/tabs'),
  'shadcn-textarea': () => import('@/components/registry/shadcn/textarea'),
  'shadcn-toggle-group': () => import('@/components/registry/shadcn/toggle-group'),
  'shadcn-toggle': () => import('@/components/registry/shadcn/toggle'),
  'shadcn-tooltip': () => import('@/components/registry/shadcn/tooltip'),

  // === Aceternity UI (68) ===
  'aceternity-animated-modal': () => import('@/components/registry/aceternity/animated-modal'),
  'aceternity-animated-tabs': () => import('@/components/registry/aceternity/animated-tabs'),
  'aceternity-animated-testimonials': () => import('@/components/registry/aceternity/animated-testimonials'),
  'aceternity-animated-tooltip': () => import('@/components/registry/aceternity/animated-tooltip'),
  'aceternity-aurora-background': () => import('@/components/registry/aceternity/aurora-background'),
  'aceternity-background-beams': () => import('@/components/registry/aceternity/background-beams'),
  'aceternity-background-gradient-animation': () => import('@/components/registry/aceternity/background-gradient-animation'),
  'aceternity-bento-grid': () => import('@/components/registry/aceternity/bento-grid'),
  'aceternity-card-hover-effect': () => import('@/components/registry/aceternity/card-hover-effect'),
  'aceternity-colourful-text': () => import('@/components/registry/aceternity/colourful-text'),
  'aceternity-compare': () => import('@/components/registry/aceternity/compare'),
  'aceternity-direction-aware-hover': () => import('@/components/registry/aceternity/direction-aware-hover'),
  'aceternity-encrypted-text': () => import('@/components/registry/aceternity/encrypted-text'),
  'aceternity-expandable-cards': () => import('@/components/registry/aceternity/expandable-cards'),
  'aceternity-flip-words': () => import('@/components/registry/aceternity/flip-words'),
  'aceternity-floating-dock': () => import('@/components/registry/aceternity/floating-dock'),
  'aceternity-floating-navbar': () => import('@/components/registry/aceternity/floating-navbar'),
  'aceternity-focus-cards': () => import('@/components/registry/aceternity/focus-cards'),
  'aceternity-glare-card': () => import('@/components/registry/aceternity/glare-card'),
  'aceternity-grid-and-dot-backgrounds': () => import('@/components/registry/aceternity/grid-and-dot-backgrounds'),
  'aceternity-hero-highlight': () => import('@/components/registry/aceternity/hero-highlight'),
  'aceternity-hero-parallax': () => import('@/components/registry/aceternity/hero-parallax'),
  'aceternity-images-slider': () => import('@/components/registry/aceternity/images-slider'),
  'aceternity-infinite-moving-cards': () => import('@/components/registry/aceternity/infinite-moving-cards'),
  'aceternity-lamp-effect': () => import('@/components/registry/aceternity/lamp-effect'),
  'aceternity-link-preview': () => import('@/components/registry/aceternity/link-preview'),
  'aceternity-meteors': () => import('@/components/registry/aceternity/meteors'),
  'aceternity-moving-border': () => import('@/components/registry/aceternity/moving-border'),
  'aceternity-shooting-stars': () => import('@/components/registry/aceternity/shooting-stars'),
  'aceternity-sparkles': () => import('@/components/registry/aceternity/sparkles'),
  'aceternity-spotlight': () => import('@/components/registry/aceternity/spotlight'),
  'aceternity-sticky-scroll-reveal': () => import('@/components/registry/aceternity/sticky-scroll-reveal'),
  'aceternity-text-generate-effect': () => import('@/components/registry/aceternity/text-generate-effect'),
  'aceternity-text-reveal-card': () => import('@/components/registry/aceternity/text-reveal-card'),
  'aceternity-three-d-card': () => import('@/components/registry/aceternity/three-d-card'),
  'aceternity-timeline': () => import('@/components/registry/aceternity/timeline'),
  'aceternity-tracing-beam': () => import('@/components/registry/aceternity/tracing-beam'),
  'aceternity-typewriter-effect': () => import('@/components/registry/aceternity/typewriter-effect'),
  'aceternity-wavy-background': () => import('@/components/registry/aceternity/wavy-background'),
  'aceternity-wobble-card': () => import('@/components/registry/aceternity/wobble-card'),
  'aceternity-3d-marquee': () => import('@/components/registry/aceternity/3d-marquee'),
  'aceternity-3d-pin': () => import('@/components/registry/aceternity/3d-pin'),
  'aceternity-apple-cards-carousel': () => import('@/components/registry/aceternity/apple-cards-carousel'),
  'aceternity-background-beams-with-collision': () => import('@/components/registry/aceternity/background-beams-with-collision'),
  'aceternity-background-boxes': () => import('@/components/registry/aceternity/background-boxes'),
  'aceternity-background-lines': () => import('@/components/registry/aceternity/background-lines'),
  'aceternity-card-spotlight': () => import('@/components/registry/aceternity/card-spotlight'),
  'aceternity-card-stack': () => import('@/components/registry/aceternity/card-stack'),
  'aceternity-carousel': () => import('@/components/registry/aceternity/carousel'),
  'aceternity-container-scroll-animation': () => import('@/components/registry/aceternity/container-scroll-animation'),
  'aceternity-draggable-card': () => import('@/components/registry/aceternity/draggable-card'),
  'aceternity-evervault-card': () => import('@/components/registry/aceternity/evervault-card'),
  'aceternity-file-upload': () => import('@/components/registry/aceternity/file-upload'),
  'aceternity-following-pointer': () => import('@/components/registry/aceternity/following-pointer'),
  'aceternity-glowing-stars': () => import('@/components/registry/aceternity/glowing-stars'),
  'aceternity-hover-border-gradient': () => import('@/components/registry/aceternity/hover-border-gradient'),
  'aceternity-layout-grid': () => import('@/components/registry/aceternity/layout-grid'),
  'aceternity-lens': () => import('@/components/registry/aceternity/lens'),
  'aceternity-macbook-scroll': () => import('@/components/registry/aceternity/macbook-scroll'),
  'aceternity-multi-step-loader': () => import('@/components/registry/aceternity/multi-step-loader'),
  'aceternity-navbar-menu': () => import('@/components/registry/aceternity/navbar-menu'),
  'aceternity-parallax-scroll': () => import('@/components/registry/aceternity/parallax-scroll'),
  'aceternity-placeholders-and-vanish-input': () => import('@/components/registry/aceternity/placeholders-and-vanish-input'),
  'aceternity-sidebar': () => import('@/components/registry/aceternity/sidebar'),
  'aceternity-spotlight-new': () => import('@/components/registry/aceternity/spotlight-new'),
  'aceternity-svg-mask-effect': () => import('@/components/registry/aceternity/svg-mask-effect'),
  'aceternity-text-hover-effect': () => import('@/components/registry/aceternity/text-hover-effect'),
  'aceternity-vortex': () => import('@/components/registry/aceternity/vortex'),
  'aceternity-container-text-flip': () => import('@/components/registry/aceternity/container-text-flip'),
  'aceternity-layout-text-flip': () => import('@/components/registry/aceternity/layout-text-flip'),
  'aceternity-pointer-highlight': () => import('@/components/registry/aceternity/pointer-highlight'),
  'aceternity-glowing-effect': () => import('@/components/registry/aceternity/glowing-effect'),
  'aceternity-stateful-button': () => import('@/components/registry/aceternity/stateful-button'),
  'aceternity-tabs': () => import('@/components/registry/aceternity/tabs'),
  'aceternity-comet-card': () => import('@/components/registry/aceternity/comet-card'),
  'aceternity-tooltip-card': () => import('@/components/registry/aceternity/tooltip-card'),
  'aceternity-resizable-navbar': () => import('@/components/registry/aceternity/resizable-navbar'),
  'aceternity-sticky-banner': () => import('@/components/registry/aceternity/sticky-banner'),
  'aceternity-noise-background': () => import('@/components/registry/aceternity/noise-background'),
  'aceternity-background-ripple-effect': () => import('@/components/registry/aceternity/background-ripple-effect'),
  'aceternity-dotted-glow-background': () => import('@/components/registry/aceternity/dotted-glow-background'),
  'aceternity-canvas-reveal-effect': () => import('@/components/registry/aceternity/canvas-reveal-effect'),
  'aceternity-pixelated-canvas': () => import('@/components/registry/aceternity/pixelated-canvas'),
  'aceternity-webcam-pixel-grid': () => import('@/components/registry/aceternity/webcam-pixel-grid'),
  'aceternity-loader': () => import('@/components/registry/aceternity/loader'),
  'aceternity-world-map': () => import('@/components/registry/aceternity/world-map'),
  'aceternity-google-gemini-effect': () => import('@/components/registry/aceternity/google-gemini-effect'),
  'aceternity-dither-shader': () => import('@/components/registry/aceternity/dither-shader'),

  // === Skiper UI (28) ===
  'skiper-animated-number': () => import('@/components/registry/skiper/animated-number'),
  'skiper-apple-feature-block': () => import('@/components/registry/skiper/apple-feature-block'),
  'skiper-apple-nav-bar': () => import('@/components/registry/skiper/apple-nav-bar'),
  'skiper-canvas-crowd': () => import('@/components/registry/skiper/canvas-crowd'),
  'skiper-card-stack-scroll': () => import('@/components/registry/skiper/card-stack-scroll'),
  'skiper-drawing-cursor-effect': () => import('@/components/registry/skiper/drawing-cursor-effect'),
  'skiper-dynamic-island': () => import('@/components/registry/skiper/dynamic-island'),
  'skiper-expand-on-hover': () => import('@/components/registry/skiper/expand-on-hover'),
  'skiper-horizontal-text-reveal': () => import('@/components/registry/skiper/horizontal-text-reveal'),
  'skiper-hover-expand': () => import('@/components/registry/skiper/hover-expand'),
  'skiper-hover-members': () => import('@/components/registry/skiper/hover-members'),
  'skiper-image-cursor-trail': () => import('@/components/registry/skiper/image-cursor-trail'),
  'skiper-infinite-canvas': () => import('@/components/registry/skiper/infinite-canvas'),
  'skiper-interactive-3d-hero': () => import('@/components/registry/skiper/interactive-3d-hero'),
  'skiper-parallax-scroll': () => import('@/components/registry/skiper/parallax-scroll'),
  'skiper-pixel-preloader': () => import('@/components/registry/skiper/pixel-preloader'),
  'skiper-progressive-blur': () => import('@/components/registry/skiper/progressive-blur'),
  'skiper-projects-showcase': () => import('@/components/registry/skiper/projects-showcase'),
  'skiper-rolling-text': () => import('@/components/registry/skiper/rolling-text'),
  'skiper-scroll-with-fade': () => import('@/components/registry/skiper/scroll-with-fade'),
  'skiper-stairs-preloader': () => import('@/components/registry/skiper/stairs-preloader'),
  'skiper-text-reveal-box': () => import('@/components/registry/skiper/text-reveal-box'),
  'skiper-text-roll-navigation': () => import('@/components/registry/skiper/text-roll-navigation'),
  'skiper-text-scroll-animation': () => import('@/components/registry/skiper/text-scroll-animation'),
  'skiper-three-d-perspective-text': () => import('@/components/registry/skiper/three-d-perspective-text'),
  'skiper-vercel-navigation': () => import('@/components/registry/skiper/vercel-navigation'),
  'skiper-vercel-tooltip': () => import('@/components/registry/skiper/vercel-tooltip'),
  'skiper-words-preloader': () => import('@/components/registry/skiper/words-preloader'),

  // === GSAP (20) ===
  'gsap-drag-cards': () => import('@/components/registry/gsap/drag-cards'),
  'gsap-drag-infinite-slider': () => import('@/components/registry/gsap/drag-infinite-slider'),
  'gsap-mouse-cursor-follower': () => import('@/components/registry/gsap/mouse-cursor-follower'),
  'gsap-mouse-inertia-gallery': () => import('@/components/registry/gsap/mouse-inertia-gallery'),
  'gsap-mouse-magnetic-element': () => import('@/components/registry/gsap/mouse-magnetic-element'),
  'gsap-mouse-spotlight-effect': () => import('@/components/registry/gsap/mouse-spotlight-effect'),
  'gsap-mouse-tilt-card': () => import('@/components/registry/gsap/mouse-tilt-card'),
  'gsap-scroll-counter': () => import('@/components/registry/gsap/scroll-counter'),
  'gsap-scroll-horizontal-section': () => import('@/components/registry/gsap/scroll-horizontal-section'),
  'gsap-scroll-infinite-marquee': () => import('@/components/registry/gsap/scroll-infinite-marquee'),
  'gsap-scroll-parallax-images': () => import('@/components/registry/gsap/scroll-parallax-images'),
  'gsap-scroll-pin-section': () => import('@/components/registry/gsap/scroll-pin-section'),
  'gsap-scroll-progress-bar': () => import('@/components/registry/gsap/scroll-progress-bar'),
  'gsap-scroll-scale-on-scroll': () => import('@/components/registry/gsap/scroll-scale-on-scroll'),
  'gsap-scroll-snap-sections': () => import('@/components/registry/gsap/scroll-snap-sections'),
  'gsap-scroll-stagger-reveal': () => import('@/components/registry/gsap/scroll-stagger-reveal'),
  'gsap-scroll-text-reveal': () => import('@/components/registry/gsap/scroll-text-reveal'),
  'gsap-text-kinetic-typography': () => import('@/components/registry/gsap/text-kinetic-typography'),
  'gsap-text-scramble': () => import('@/components/registry/gsap/text-scramble'),
  'gsap-text-split-animation': () => import('@/components/registry/gsap/text-split-animation'),

  // === Osmo Supply (31) ===
  'osmo-apple-dock-navigation': () => import('@/components/registry/osmo/apple-dock-navigation'),
  'osmo-before-after-split-slider': () => import('@/components/registry/osmo/before-after-split-slider'),
  'osmo-bold-fullscreen-navigation': () => import('@/components/registry/osmo/bold-fullscreen-navigation'),
  'osmo-css-marquee': () => import('@/components/registry/osmo/css-marquee'),
  'osmo-directional-list-hover': () => import('@/components/registry/osmo/directional-list-hover'),
  'osmo-draggable-marquee': () => import('@/components/registry/osmo/draggable-marquee'),
  'osmo-dropping-cards-stack': () => import('@/components/registry/osmo/dropping-cards-stack'),
  'osmo-falling-2d-objects': () => import('@/components/registry/osmo/falling-2d-objects'),
  'osmo-falling-text-gravity': () => import('@/components/registry/osmo/falling-text-gravity'),
  'osmo-footer-parallax-effect': () => import('@/components/registry/osmo/footer-parallax-effect'),
  'osmo-glowing-dots-grid': () => import('@/components/registry/osmo/glowing-dots-grid'),
  'osmo-highlight-text-on-scroll': () => import('@/components/registry/osmo/highlight-text-on-scroll'),
  'osmo-horizontal-scrolling-sections': () => import('@/components/registry/osmo/horizontal-scrolling-sections'),
  'osmo-image-to-background-zoom': () => import('@/components/registry/osmo/image-to-background-zoom'),
  'osmo-interactive-pixel-grid': () => import('@/components/registry/osmo/interactive-pixel-grid'),
  'osmo-line-reveal-testimonials': () => import('@/components/registry/osmo/line-reveal-testimonials'),
  'osmo-magnetic-cursor': () => import('@/components/registry/osmo/magnetic-cursor'),
  'osmo-masked-text-reveal': () => import('@/components/registry/osmo/masked-text-reveal'),
  'osmo-parallax-image-gallery': () => import('@/components/registry/osmo/parallax-image-gallery'),
  'osmo-pixelated-image-reveal': () => import('@/components/registry/osmo/pixelated-image-reveal'),
  'osmo-rotating-image-trail': () => import('@/components/registry/osmo/rotating-image-trail'),
  'osmo-rotating-text': () => import('@/components/registry/osmo/rotating-text'),
  'osmo-scaling-hamburger-navigation': () => import('@/components/registry/osmo/scaling-hamburger-navigation'),
  'osmo-stacking-cards-parallax': () => import('@/components/registry/osmo/stacking-cards-parallax'),
  'osmo-stacking-cards-slider': () => import('@/components/registry/osmo/stacking-cards-slider'),
  'osmo-stacking-image-trail': () => import('@/components/registry/osmo/stacking-image-trail'),
  'osmo-sticky-features': () => import('@/components/registry/osmo/sticky-features'),
  'osmo-text-scramble': () => import('@/components/registry/osmo/text-scramble'),
  'osmo-three-d-image-carousel': () => import('@/components/registry/osmo/three-d-image-carousel'),
  'osmo-variable-font-weight-hover': () => import('@/components/registry/osmo/variable-font-weight-hover'),
  'osmo-download-button': () => import('@/components/registry/osmo/download-button'),

  // === New Shadcn Sections (65) ===
  'shadcn-announcement-bar': () => import('@/components/registry/shadcn/announcement-bar'),
  'shadcn-blog-grid': () => import('@/components/registry/shadcn/blog-grid'),
  'shadcn-case-study-card': () => import('@/components/registry/shadcn/case-study-card'),
  'shadcn-comparison-table': () => import('@/components/registry/shadcn/comparison-table'),
  'shadcn-contact-form': () => import('@/components/registry/shadcn/contact-form'),
  'shadcn-content-two-column': () => import('@/components/registry/shadcn/content-two-column'),
  'shadcn-cookie-banner': () => import('@/components/registry/shadcn/cookie-banner'),
  'shadcn-cta-banner': () => import('@/components/registry/shadcn/cta-banner'),
  'shadcn-cta-centered': () => import('@/components/registry/shadcn/cta-centered'),
  'shadcn-cta-newsletter': () => import('@/components/registry/shadcn/cta-newsletter'),
  'shadcn-cta-split': () => import('@/components/registry/shadcn/cta-split'),
  'shadcn-cta-with-form': () => import('@/components/registry/shadcn/cta-with-form'),
  'shadcn-faq-accordion': () => import('@/components/registry/shadcn/faq-accordion'),
  'shadcn-faq-categorized': () => import('@/components/registry/shadcn/faq-categorized'),
  'shadcn-faq-simple': () => import('@/components/registry/shadcn/faq-simple'),
  'shadcn-faq-two-column': () => import('@/components/registry/shadcn/faq-two-column'),
  'shadcn-feature-alternating': () => import('@/components/registry/shadcn/feature-alternating'),
  'shadcn-feature-cards': () => import('@/components/registry/shadcn/feature-cards'),
  'shadcn-feature-centered': () => import('@/components/registry/shadcn/feature-centered'),
  'shadcn-feature-comparison': () => import('@/components/registry/shadcn/feature-comparison'),
  'shadcn-feature-grid-3col': () => import('@/components/registry/shadcn/feature-grid-3col'),
  'shadcn-feature-grid-4col': () => import('@/components/registry/shadcn/feature-grid-4col'),
  'shadcn-feature-list': () => import('@/components/registry/shadcn/feature-list'),
  'shadcn-feature-split': () => import('@/components/registry/shadcn/feature-split'),
  'shadcn-feature-timeline': () => import('@/components/registry/shadcn/feature-timeline'),
  'shadcn-feature-with-tabs': () => import('@/components/registry/shadcn/feature-with-tabs'),
  'shadcn-feedback-form': () => import('@/components/registry/shadcn/feedback-form'),
  'shadcn-footer-centered': () => import('@/components/registry/shadcn/footer-centered'),
  'shadcn-footer-default': () => import('@/components/registry/shadcn/footer-default'),
  'shadcn-footer-minimal': () => import('@/components/registry/shadcn/footer-minimal'),
  'shadcn-footer-social': () => import('@/components/registry/shadcn/footer-social'),
  'shadcn-footer-with-newsletter': () => import('@/components/registry/shadcn/footer-with-newsletter'),
  'shadcn-header-centered': () => import('@/components/registry/shadcn/header-centered'),
  'shadcn-header-default': () => import('@/components/registry/shadcn/header-default'),
  'shadcn-header-mega-menu': () => import('@/components/registry/shadcn/header-mega-menu'),
  'shadcn-header-transparent': () => import('@/components/registry/shadcn/header-transparent'),
  'shadcn-header-with-cta': () => import('@/components/registry/shadcn/header-with-cta'),
  'shadcn-hero-animated': () => import('@/components/registry/shadcn/hero-animated'),
  'shadcn-hero-centered': () => import('@/components/registry/shadcn/hero-centered'),
  'shadcn-hero-gradient': () => import('@/components/registry/shadcn/hero-gradient'),
  'shadcn-hero-minimal': () => import('@/components/registry/shadcn/hero-minimal'),
  'shadcn-hero-split': () => import('@/components/registry/shadcn/hero-split'),
  'shadcn-hero-video': () => import('@/components/registry/shadcn/hero-video'),
  'shadcn-hero-with-badges': () => import('@/components/registry/shadcn/hero-with-badges'),
  'shadcn-hero-with-form': () => import('@/components/registry/shadcn/hero-with-form'),
  'shadcn-how-it-works': () => import('@/components/registry/shadcn/how-it-works'),
  'shadcn-login-form': () => import('@/components/registry/shadcn/login-form'),
  'shadcn-logo-cloud': () => import('@/components/registry/shadcn/logo-cloud'),
  'shadcn-newsletter-form': () => import('@/components/registry/shadcn/newsletter-form'),
  'shadcn-pricing-cards': () => import('@/components/registry/shadcn/pricing-cards'),
  'shadcn-pricing-comparison': () => import('@/components/registry/shadcn/pricing-comparison'),
  'shadcn-pricing-enterprise': () => import('@/components/registry/shadcn/pricing-enterprise'),
  'shadcn-pricing-simple': () => import('@/components/registry/shadcn/pricing-simple'),
  'shadcn-pricing-three-tier': () => import('@/components/registry/shadcn/pricing-three-tier'),
  'shadcn-pricing-toggle': () => import('@/components/registry/shadcn/pricing-toggle'),
  'shadcn-signup-form': () => import('@/components/registry/shadcn/signup-form'),
  'shadcn-social-proof-banner': () => import('@/components/registry/shadcn/social-proof-banner'),
  'shadcn-stats-section': () => import('@/components/registry/shadcn/stats-section'),
  'shadcn-team-grid': () => import('@/components/registry/shadcn/team-grid'),
  'shadcn-testimonial-carousel': () => import('@/components/registry/shadcn/testimonial-carousel'),
  'shadcn-testimonial-grid': () => import('@/components/registry/shadcn/testimonial-grid'),
  'shadcn-testimonial-marquee': () => import('@/components/registry/shadcn/testimonial-marquee'),
  'shadcn-testimonial-single': () => import('@/components/registry/shadcn/testimonial-single'),
  'shadcn-testimonial-video': () => import('@/components/registry/shadcn/testimonial-video'),
  'shadcn-testimonial-with-avatar': () => import('@/components/registry/shadcn/testimonial-with-avatar'),

  // === New GSAP Effects (30) ===
  'gsap-cursor-trail-effect': () => import('@/components/registry/gsap/cursor-trail-effect'),
  'gsap-drag-slider-3d': () => import('@/components/registry/gsap/drag-slider-3d'),
  'gsap-elastic-cursor': () => import('@/components/registry/gsap/elastic-cursor'),
  'gsap-flip-card-animation': () => import('@/components/registry/gsap/flip-card-animation'),
  'gsap-floating-elements': () => import('@/components/registry/gsap/floating-elements'),
  'gsap-hover-image-distortion': () => import('@/components/registry/gsap/hover-image-distortion'),
  'gsap-hover-reveal-image': () => import('@/components/registry/gsap/hover-reveal-image'),
  'gsap-hover-scale-text': () => import('@/components/registry/gsap/hover-scale-text'),
  'gsap-loading-sequence': () => import('@/components/registry/gsap/loading-sequence'),
  'gsap-number-counter-scroll': () => import('@/components/registry/gsap/number-counter-scroll'),
  'gsap-page-transition': () => import('@/components/registry/gsap/page-transition'),
  'gsap-reveal-menu': () => import('@/components/registry/gsap/reveal-menu'),
  'gsap-scroll-clip-path': () => import('@/components/registry/gsap/scroll-clip-path'),
  'gsap-scroll-color-change': () => import('@/components/registry/gsap/scroll-color-change'),
  'gsap-scroll-image-reveal': () => import('@/components/registry/gsap/scroll-image-reveal'),
  'gsap-scroll-parallax-layers': () => import('@/components/registry/gsap/scroll-parallax-layers'),
  'gsap-scroll-path-animation': () => import('@/components/registry/gsap/scroll-path-animation'),
  'gsap-scroll-rotate-element': () => import('@/components/registry/gsap/scroll-rotate-element'),
  'gsap-scroll-skew-element': () => import('@/components/registry/gsap/scroll-skew-element'),
  'gsap-scroll-split-text': () => import('@/components/registry/gsap/scroll-split-text'),
  'gsap-scroll-text-fade': () => import('@/components/registry/gsap/scroll-text-fade'),
  'gsap-scroll-timeline-horizontal': () => import('@/components/registry/gsap/scroll-timeline-horizontal'),
  'gsap-scroll-timeline-vertical': () => import('@/components/registry/gsap/scroll-timeline-vertical'),
  'gsap-scroll-video-playback': () => import('@/components/registry/gsap/scroll-video-playback'),
  'gsap-scroll-video-scrub': () => import('@/components/registry/gsap/scroll-video-scrub'),
  'gsap-smooth-scroll': () => import('@/components/registry/gsap/smooth-scroll'),
  'gsap-stagger-list-items': () => import('@/components/registry/gsap/stagger-list-items'),
  'gsap-text-glitch-effect': () => import('@/components/registry/gsap/text-glitch-effect'),
  'gsap-text-mask-reveal': () => import('@/components/registry/gsap/text-mask-reveal'),
  'gsap-text-wave-animation': () => import('@/components/registry/gsap/text-wave-animation'),

  // === New Osmo Effects (25) ===
  'osmo-animated-background-grid': () => import('@/components/registry/osmo/animated-background-grid'),
  'osmo-blob-cursor': () => import('@/components/registry/osmo/blob-cursor'),
  'osmo-color-transition-scroll': () => import('@/components/registry/osmo/color-transition-scroll'),
  'osmo-cursor-glow-effect': () => import('@/components/registry/osmo/cursor-glow-effect'),
  'osmo-cursor-spotlight': () => import('@/components/registry/osmo/cursor-spotlight'),
  'osmo-grid-hover-effect': () => import('@/components/registry/osmo/grid-hover-effect'),
  'osmo-hover-expand-image': () => import('@/components/registry/osmo/hover-expand-image'),
  'osmo-hover-lift-card': () => import('@/components/registry/osmo/hover-lift-card'),
  'osmo-hover-tilt-card': () => import('@/components/registry/osmo/hover-tilt-card'),
  'osmo-hover-zoom-gallery': () => import('@/components/registry/osmo/hover-zoom-gallery'),
  'osmo-image-reveal-slider': () => import('@/components/registry/osmo/image-reveal-slider'),
  'osmo-infinite-logo-slider': () => import('@/components/registry/osmo/infinite-logo-slider'),
  'osmo-parallax-cards': () => import('@/components/registry/osmo/parallax-cards'),
  'osmo-ripple-effect': () => import('@/components/registry/osmo/ripple-effect'),
  'osmo-scroll-fade-gallery': () => import('@/components/registry/osmo/scroll-fade-gallery'),
  'osmo-scroll-morph-header': () => import('@/components/registry/osmo/scroll-morph-header'),
  'osmo-scroll-progress-circle': () => import('@/components/registry/osmo/scroll-progress-circle'),
  'osmo-scroll-snap-gallery': () => import('@/components/registry/osmo/scroll-snap-gallery'),
  'osmo-scroll-ticker': () => import('@/components/registry/osmo/scroll-ticker'),
  'osmo-slide-in-navigation': () => import('@/components/registry/osmo/slide-in-navigation'),
  'osmo-text-blur-reveal': () => import('@/components/registry/osmo/text-blur-reveal'),
  'osmo-text-gradient-animation': () => import('@/components/registry/osmo/text-gradient-animation'),
  'osmo-text-reveal-lines': () => import('@/components/registry/osmo/text-reveal-lines'),
  'osmo-text-split-hover': () => import('@/components/registry/osmo/text-split-hover'),
  'osmo-typewriter-cursor': () => import('@/components/registry/osmo/typewriter-cursor'),

  // === New Skiper Effects (25) ===
  'skiper-3d-card-flip': () => import('@/components/registry/skiper/3d-card-flip'),
  'skiper-3d-carousel': () => import('@/components/registry/skiper/3d-carousel'),
  'skiper-3d-flip-gallery': () => import('@/components/registry/skiper/3d-flip-gallery'),
  'skiper-3d-text-effect': () => import('@/components/registry/skiper/3d-text-effect'),
  'skiper-aurora-effect': () => import('@/components/registry/skiper/aurora-effect'),
  'skiper-crystal-card': () => import('@/components/registry/skiper/crystal-card'),
  'skiper-depth-card': () => import('@/components/registry/skiper/depth-card'),
  'skiper-floating-card': () => import('@/components/registry/skiper/floating-card'),
  'skiper-glass-morphism-card': () => import('@/components/registry/skiper/glass-morphism-card'),
  'skiper-gradient-mesh': () => import('@/components/registry/skiper/gradient-mesh'),
  'skiper-holographic-card': () => import('@/components/registry/skiper/holographic-card'),
  'skiper-hover-blur-effect': () => import('@/components/registry/skiper/hover-blur-effect'),
  'skiper-hover-distortion': () => import('@/components/registry/skiper/hover-distortion'),
  'skiper-light-beam-effect': () => import('@/components/registry/skiper/light-beam-effect'),
  'skiper-liquid-button': () => import('@/components/registry/skiper/liquid-button'),
  'skiper-magnetic-button': () => import('@/components/registry/skiper/magnetic-button'),
  'skiper-morphing-blob': () => import('@/components/registry/skiper/morphing-blob'),
  'skiper-neon-glow-text': () => import('@/components/registry/skiper/neon-glow-text'),
  'skiper-noise-background': () => import('@/components/registry/skiper/noise-background'),
  'skiper-particle-background': () => import('@/components/registry/skiper/particle-background'),
  'skiper-scatter-effect': () => import('@/components/registry/skiper/scatter-effect'),
  'skiper-scroll-morph-text': () => import('@/components/registry/skiper/scroll-morph-text'),
  'skiper-scroll-warp-text': () => import('@/components/registry/skiper/scroll-warp-text'),
  'skiper-tilt-parallax': () => import('@/components/registry/skiper/tilt-parallax'),
  'skiper-wave-animation': () => import('@/components/registry/skiper/wave-animation'),

  // === New Aceternity Components (25) ===
  'aceternity-auto-complete': () => import('@/components/registry/aceternity/auto-complete'),
  'aceternity-breadcrumb-animated': () => import('@/components/registry/aceternity/breadcrumb-animated'),
  'aceternity-chip-input': () => import('@/components/registry/aceternity/chip-input'),
  'aceternity-command-palette': () => import('@/components/registry/aceternity/command-palette'),
  'aceternity-countdown-timer': () => import('@/components/registry/aceternity/countdown-timer'),
  'aceternity-empty-state': () => import('@/components/registry/aceternity/empty-state'),
  'aceternity-error-state': () => import('@/components/registry/aceternity/error-state'),
  'aceternity-feature-card': () => import('@/components/registry/aceternity/feature-card'),
  'aceternity-image-gallery': () => import('@/components/registry/aceternity/image-gallery'),
  'aceternity-infinite-scroll': () => import('@/components/registry/aceternity/infinite-scroll'),
  'aceternity-loading-spinner': () => import('@/components/registry/aceternity/loading-spinner'),
  'aceternity-notification-popup': () => import('@/components/registry/aceternity/notification-popup'),
  'aceternity-pricing-card': () => import('@/components/registry/aceternity/pricing-card'),
  'aceternity-progress-tracker': () => import('@/components/registry/aceternity/progress-tracker'),
  'aceternity-range-slider': () => import('@/components/registry/aceternity/range-slider'),
  'aceternity-rating-stars': () => import('@/components/registry/aceternity/rating-stars'),
  'aceternity-search-bar': () => import('@/components/registry/aceternity/search-bar'),
  'aceternity-skeleton-loader': () => import('@/components/registry/aceternity/skeleton-loader'),
  'aceternity-social-proof': () => import('@/components/registry/aceternity/social-proof'),
  'aceternity-stats-counter': () => import('@/components/registry/aceternity/stats-counter'),
  'aceternity-stepper': () => import('@/components/registry/aceternity/stepper'),
  'aceternity-tag-cloud': () => import('@/components/registry/aceternity/tag-cloud'),
  'aceternity-testimonial-card': () => import('@/components/registry/aceternity/testimonial-card'),
  'aceternity-tree-view': () => import('@/components/registry/aceternity/tree-view'),
  'aceternity-video-player': () => import('@/components/registry/aceternity/video-player'),

  // === Custom imported components ===
  'custom-html-block': () => import('@/components/registry/custom/html-block'),
}

// Cache of loaded lazy components
const componentCache = new Map<string, LazyComponent>()

/**
 * Get a lazy-loaded React component by registry ID
 */
export function getComponent(registryId: string): LazyComponent | null {
  if (componentCache.has(registryId)) {
    return componentCache.get(registryId)!
  }

  const importFn = COMPONENT_MAP[registryId]
  if (!importFn) return null

  const LazyComp = lazy(importFn)
  componentCache.set(registryId, LazyComp)
  return LazyComp
}

/**
 * Check if a component implementation exists
 */
export function isComponentAvailable(registryId: string): boolean {
  return registryId in COMPONENT_MAP
}

/**
 * Preload a component (useful for hover preload in the browser)
 */
export async function preloadComponent(registryId: string): Promise<void> {
  const importFn = COMPONENT_MAP[registryId]
  if (importFn) {
    await importFn()
  }
}

/**
 * Get all available component IDs
 */
export function getAvailableComponentIds(): string[] {
  return Object.keys(COMPONENT_MAP)
}
