import type { ComponentRegistryItem } from '../types'

export const gsapEffects: ComponentRegistryItem[] = [
  {
    id: 'gsap-drag-cards',
    name: 'GsapDragCards',
    displayName: 'Drag Cards',
    source: 'gsap',
    categories: ['card', 'animation'],
    tags: ['drag', 'cards', 'draggable', 'interactive', 'stack'],
    description: 'A stack of draggable cards with inertia physics. Cards can be picked up, tossed, and rearranged with smooth elastic snap-back animations.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, image, and rotation',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card title' },
          { name: 'image', type: 'image', required: true, description: 'Card image URL' },
          { name: 'rotation', type: 'number', required: true, description: 'Initial rotation angle in degrees' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-drag-cards',
    level: 'primitive',
    code: '<GsapDragCards cards={[{ title: "Card One", image: "/img.jpg", rotation: -5 }]} />',
    suggestedWith: ['gsap-mouse-tilt-card', 'gsap-drag-infinite-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-drag-infinite-slider',
    name: 'GsapDragInfiniteSlider',
    displayName: 'Drag Infinite Slider',
    source: 'gsap',
    categories: ['animation', 'media'],
    tags: ['drag', 'slider', 'infinite', 'carousel', 'loop', 'auto-scroll'],
    description: 'An infinite looping slider that can be dragged and auto-scrolls. Supports horizontal and vertical directions with seamless wrapping.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of slider items with content and image',
        group: 'content',
        itemSchema: [
          { name: 'content', type: 'string', required: true, description: 'Item title text' },
          { name: 'image', type: 'image', required: true, description: 'Item image URL' },
        ],
      },
      {
        name: 'direction',
        type: 'select',
        default: 'horizontal',
        required: false,
        options: ['horizontal', 'vertical'],
        description: 'Scroll direction of the slider',
        group: 'behavior',
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-drag-infinite-slider',
    level: 'section',
    code: '<GsapDragInfiniteSlider direction="horizontal" />',
    suggestedWith: ['gsap-drag-cards', 'gsap-scroll-infinite-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-mouse-cursor-follower',
    name: 'GsapMouseCursorFollower',
    displayName: 'Cursor Follower',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'follower', 'mouse', 'interactive', 'custom-cursor'],
    description: 'A custom cursor follower with a smooth trailing circle and dot that tracks mouse movement with configurable size, color, and blend mode.',
    previewImage: '',
    props: [
      { name: 'size', type: 'number', default: 40, required: false, description: 'Diameter of the follower circle in pixels', group: 'style' },
      { name: 'color', type: 'color', default: 'rgba(102, 126, 234, 0.6)', required: false, description: 'Color of the follower circle', group: 'style' },
      { name: 'mixBlendMode', type: 'select', default: 'difference', required: false, options: ['difference', 'multiply', 'screen', 'overlay', 'normal'], description: 'CSS mix-blend-mode for the cursor circle', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to display inside the cursor area', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-cursor-follower',
    level: 'effect',
    code: '<GsapMouseCursorFollower size={40} color="rgba(102,126,234,0.6)">Content here</GsapMouseCursorFollower>',
    suggestedWith: ['gsap-mouse-spotlight-effect', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-inertia-gallery',
    name: 'GsapMouseInertiaGallery',
    displayName: 'Inertia Gallery',
    source: 'gsap',
    categories: ['media', 'animation'],
    tags: ['gallery', 'inertia', 'mouse', 'parallax', 'images', 'interactive'],
    description: 'An image grid that reacts to mouse movement with inertia-based parallax. Each image moves at a different depth for a layered 3D feel.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with src and alt text',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text for the image' },
        ],
      },
      { name: 'columns', type: 'number', default: 3, required: false, description: 'Number of grid columns', group: 'style' },
      { name: 'imageSize', type: 'number', default: 200, required: false, description: 'Size of each image in pixels', group: 'style' },
      { name: 'velocity', type: 'number', default: 0.15, required: false, description: 'Movement velocity multiplier', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-inertia-gallery',
    level: 'section',
    code: '<GsapMouseInertiaGallery columns={3} imageSize={200} velocity={0.15} />',
    suggestedWith: ['gsap-scroll-parallax-images', 'gsap-mouse-tilt-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-mouse-magnetic-element',
    name: 'GsapMouseMagneticElement',
    displayName: 'Magnetic Element',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['magnetic', 'hover', 'mouse', 'interactive', 'button', 'attraction'],
    description: 'An element that magnetically attracts toward the cursor when nearby, with elastic snap-back. Perfect for buttons and CTAs.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Content to make magnetic', group: 'content' },
      { name: 'strength', type: 'number', default: 0.4, required: false, description: 'Magnetic attraction strength (0-1)', group: 'behavior' },
      { name: 'radius', type: 'number', default: 200, required: false, description: 'Magnetic effect radius in pixels', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-magnetic-element',
    level: 'effect',
    code: '<GsapMouseMagneticElement strength={0.4} radius={200}><button>Hover me</button></GsapMouseMagneticElement>',
    suggestedWith: ['gsap-mouse-cursor-follower', 'gsap-mouse-tilt-card'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-spotlight-effect',
    name: 'GsapMouseSpotlightEffect',
    displayName: 'Spotlight Effect',
    source: 'gsap',
    categories: ['effect', 'background'],
    tags: ['spotlight', 'mouse', 'glow', 'radial', 'light', 'reveal'],
    description: 'A radial spotlight that follows the cursor, creating a dramatic reveal effect over dark backgrounds. Configurable radius, color, and intensity.',
    previewImage: '',
    props: [
      { name: 'radius', type: 'number', default: 200, required: false, description: 'Spotlight radius in pixels', group: 'style' },
      { name: 'color', type: 'color', default: 'rgba(102, 126, 234, 0.3)', required: false, description: 'Spotlight color', group: 'style' },
      { name: 'intensity', type: 'number', default: 1, required: false, description: 'Spotlight opacity intensity (0-1)', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to display under the spotlight', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-spotlight-effect',
    level: 'effect',
    code: '<GsapMouseSpotlightEffect radius={200} color="rgba(102,126,234,0.3)"><h2>Spotlight</h2></GsapMouseSpotlightEffect>',
    suggestedWith: ['gsap-mouse-cursor-follower', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-tilt-card',
    name: 'GsapMouseTiltCard',
    displayName: 'Tilt Card',
    source: 'gsap',
    categories: ['card', 'effect'],
    tags: ['tilt', '3d', 'perspective', 'card', 'hover', 'glare'],
    description: 'A 3D tilt card that responds to cursor position with perspective rotation and a dynamic glare overlay effect.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Tilt Card', required: false, description: 'Card title text', group: 'content' },
      { name: 'description', type: 'string', default: 'Move your mouse over this card to see the 3D tilt effect.', required: false, description: 'Card description text', group: 'content' },
      { name: 'image', type: 'image', default: 'https://picsum.photos/seed/tilt/400/250', required: false, description: 'Card cover image URL', group: 'content' },
      { name: 'maxTilt', type: 'number', default: 15, required: false, description: 'Maximum tilt angle in degrees', group: 'behavior' },
      { name: 'perspective', type: 'number', default: 1000, required: false, description: 'CSS perspective value in pixels', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-tilt-card',
    level: 'primitive',
    code: '<GsapMouseTiltCard title="My Card" image="/card.jpg" maxTilt={15} />',
    suggestedWith: ['gsap-drag-cards', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-counter',
    name: 'GsapScrollCounter',
    displayName: 'Scroll Counter',
    source: 'gsap',
    categories: ['animation', 'text'],
    tags: ['counter', 'number', 'scroll', 'count-up', 'statistics', 'animate'],
    description: 'An animated number counter that counts up when scrolled into view. Supports prefix, suffix, and decimal formatting.',
    previewImage: '',
    props: [
      { name: 'endValue', type: 'number', default: 1234, required: false, description: 'Target number to count to', group: 'content' },
      { name: 'duration', type: 'number', default: 2, required: false, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'prefix', type: 'string', default: '', required: false, description: 'Text before the number (e.g. "$")', group: 'content' },
      { name: 'suffix', type: 'string', default: '', required: false, description: 'Text after the number (e.g. "+")', group: 'content' },
      { name: 'decimals', type: 'number', default: 0, required: false, description: 'Number of decimal places', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-counter',
    level: 'primitive',
    code: '<GsapScrollCounter endValue={1234} prefix="$" suffix="+" />',
    suggestedWith: ['gsap-scroll-stagger-reveal', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-horizontal-section',
    name: 'GsapScrollHorizontalSection',
    displayName: 'Horizontal Scroll Section',
    source: 'gsap',
    categories: ['section', 'layout', 'animation'],
    tags: ['horizontal', 'scroll', 'section', 'pin', 'scrub', 'fullscreen'],
    description: 'Full-viewport horizontal scrolling sections pinned to the screen. Vertical scroll is translated into horizontal movement.',
    previewImage: '',
    props: [
      {
        name: 'sections',
        type: 'array',
        required: false,
        description: 'Array of section objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Section heading' },
          { name: 'content', type: 'string', required: true, description: 'Section body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Section background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-horizontal-section',
    level: 'section',
    code: '<GsapScrollHorizontalSection sections={[{ title: "One", content: "...", bgColor: "#1a1a2e" }]} />',
    suggestedWith: ['gsap-scroll-snap-sections', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-infinite-marquee',
    name: 'GsapScrollInfiniteMarquee',
    displayName: 'Infinite Marquee',
    source: 'gsap',
    categories: ['animation', 'text'],
    tags: ['marquee', 'infinite', 'scroll', 'ticker', 'loop', 'speed-boost'],
    description: 'An infinite scrolling text marquee that speeds up when the page is scrolled. Supports left/right direction and pause on hover.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings to display', group: 'content' },
      { name: 'speed', type: 'number', default: 50, required: false, description: 'Base scroll speed in pixels per second', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, options: ['left', 'right'], description: 'Marquee scroll direction', group: 'behavior' },
      { name: 'pauseOnHover', type: 'boolean', default: true, required: false, description: 'Pause marquee on mouse hover', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-infinite-marquee',
    level: 'primitive',
    code: '<GsapScrollInfiniteMarquee items={["Design", "Develop", "Deploy"]} speed={50} />',
    suggestedWith: ['gsap-drag-infinite-slider', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-parallax-images',
    name: 'GsapScrollParallaxImages',
    displayName: 'Parallax Images',
    source: 'gsap',
    categories: ['media', 'animation'],
    tags: ['parallax', 'images', 'scroll', 'depth', 'gallery'],
    description: 'A responsive image grid where each image moves at a different parallax speed on scroll, creating a layered depth effect.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with source, alt text, and parallax speed',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
          { name: 'speed', type: 'number', required: true, description: 'Parallax speed multiplier' },
        ],
      },
      { name: 'gap', type: 'number', default: 24, required: false, description: 'Gap between images in pixels', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-parallax-images',
    level: 'section',
    code: '<GsapScrollParallaxImages gap={24} />',
    suggestedWith: ['gsap-mouse-inertia-gallery', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-pin-section',
    name: 'GsapScrollPinSection',
    displayName: 'Pin Section',
    source: 'gsap',
    categories: ['section', 'animation'],
    tags: ['pin', 'sticky', 'scroll', 'section', 'fixed', 'reveal'],
    description: 'A section that pins in place while content animates in and out on scroll. Title and content fade in, hold, then fade away.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Pinned Section', required: false, description: 'Section heading', group: 'content' },
      { name: 'content', type: 'string', default: 'This section stays fixed while you scroll.', required: false, description: 'Section body text', group: 'content' },
      { name: 'bgColor', type: 'color', default: '#0f172a', required: false, description: 'Background color', group: 'style' },
      { name: 'duration', type: 'number', default: 300, required: false, description: 'Scroll distance as percentage of viewport', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-pin-section',
    level: 'section',
    code: '<GsapScrollPinSection title="Pinned" content="This stays fixed while you scroll." />',
    suggestedWith: ['gsap-scroll-horizontal-section', 'gsap-scroll-snap-sections'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-progress-bar',
    name: 'GsapScrollProgressBar',
    displayName: 'Scroll Progress Bar',
    source: 'gsap',
    categories: ['effect', 'navigation'],
    tags: ['progress', 'scroll', 'bar', 'indicator', 'fixed', 'reading'],
    description: 'A fixed progress bar that scales horizontally to indicate overall page scroll progress. Can be positioned at top or bottom.',
    previewImage: '',
    props: [
      { name: 'color', type: 'color', default: '#667eea', required: false, description: 'Progress bar color', group: 'style' },
      { name: 'height', type: 'number', default: 4, required: false, description: 'Bar height in pixels', group: 'style' },
      { name: 'position', type: 'select', default: 'top', required: false, options: ['top', 'bottom'], description: 'Fixed position on the viewport', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-progress-bar',
    level: 'effect',
    code: '<GsapScrollProgressBar color="#667eea" height={4} position="top" />',
    suggestedWith: ['gsap-scroll-snap-sections', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-scale-on-scroll',
    name: 'GsapScrollScale',
    displayName: 'Scale on Scroll',
    source: 'gsap',
    categories: ['animation', 'effect'],
    tags: ['scale', 'scroll', 'zoom', 'grow', 'reveal', 'scrub'],
    description: 'An element that scales up from small to full size as the user scrolls, with optional scrub for direct scroll-linked motion.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Content to scale on scroll', group: 'content' },
      { name: 'scaleFrom', type: 'number', default: 0.6, required: false, description: 'Starting scale value', group: 'behavior' },
      { name: 'scaleTo', type: 'number', default: 1, required: false, description: 'Ending scale value', group: 'behavior' },
      { name: 'scrub', type: 'boolean', default: true, required: false, description: 'Link animation directly to scroll position', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-scale-on-scroll',
    level: 'effect',
    code: '<GsapScrollScale scaleFrom={0.6} scaleTo={1}><div>Scale me</div></GsapScrollScale>',
    suggestedWith: ['gsap-scroll-stagger-reveal', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-snap-sections',
    name: 'GsapScrollSnapSections',
    displayName: 'Snap Sections',
    source: 'gsap',
    categories: ['section', 'layout', 'animation'],
    tags: ['snap', 'scroll', 'sections', 'fullscreen', 'paging'],
    description: 'Full-height sections with scroll snapping that locks each section into view. Content animates in with staggered reveal.',
    previewImage: '',
    props: [
      {
        name: 'sections',
        type: 'array',
        required: false,
        description: 'Array of section objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Section heading' },
          { name: 'content', type: 'string', required: true, description: 'Section body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Section background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-snap-sections',
    level: 'section',
    code: '<GsapScrollSnapSections sections={[{ title: "Welcome", content: "...", bgColor: "#0f172a" }]} />',
    suggestedWith: ['gsap-scroll-horizontal-section', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-stagger-reveal',
    name: 'GsapScrollStaggerReveal',
    displayName: 'Stagger Reveal',
    source: 'gsap',
    categories: ['animation', 'card'],
    tags: ['stagger', 'reveal', 'scroll', 'cards', 'grid', 'entrance'],
    description: 'A grid of cards that reveal with a staggered animation on scroll. Supports directional entrance from up, down, left, or right.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of items with title and description',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Item title' },
          { name: 'description', type: 'string', required: true, description: 'Item description' },
        ],
      },
      { name: 'stagger', type: 'number', default: 0.15, required: false, description: 'Delay between each item animation in seconds', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'up', required: false, options: ['up', 'down', 'left', 'right'], description: 'Direction items animate from', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-stagger-reveal',
    level: 'section',
    code: '<GsapScrollStaggerReveal direction="up" stagger={0.15} />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-text-reveal',
    name: 'GsapScrollTextReveal',
    displayName: 'Scroll Text Reveal',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['text', 'reveal', 'scroll', 'split', 'word', 'character', 'scrub'],
    description: 'Text that reveals word-by-word or character-by-character as the user scrolls. Scrub mode ties the animation directly to scroll position.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Scroll to reveal this amazing text animation that brings words to life as you navigate down the page.', required: false, description: 'Text content to reveal', group: 'content' },
      { name: 'splitBy', type: 'select', default: 'word', required: false, options: ['word', 'char', 'line'], description: 'How to split the text for animation', group: 'behavior' },
      { name: 'stagger', type: 'number', default: 0.05, required: false, description: 'Delay between each unit reveal', group: 'behavior' },
      { name: 'scrub', type: 'boolean', default: true, required: false, description: 'Link animation to scroll position', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-text-reveal',
    level: 'primitive',
    code: '<GsapScrollTextReveal text="Reveal this text on scroll" splitBy="word" />',
    suggestedWith: ['gsap-text-split-animation', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-kinetic-typography',
    name: 'GsapKineticTypography',
    displayName: 'Kinetic Typography',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['kinetic', 'typography', 'wave', 'bounce', 'elastic', 'rotate', 'characters'],
    description: 'Animated kinetic typography with multiple animation modes including wave, bounce, elastic, and stagger-rotate effects on individual characters.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'KINETIC', required: false, description: 'Text to animate', group: 'content' },
      { name: 'animation', type: 'select', default: 'wave', required: false, options: ['wave', 'bounce', 'elastic', 'stagger-rotate'], description: 'Animation style', group: 'behavior' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Animation speed multiplier', group: 'behavior' },
      { name: 'loop', type: 'boolean', default: true, required: false, description: 'Whether the animation loops continuously', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-kinetic-typography',
    level: 'primitive',
    code: '<GsapKineticTypography text="KINETIC" animation="wave" loop />',
    suggestedWith: ['gsap-text-scramble', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-scramble',
    name: 'GsapTextScramble',
    displayName: 'Text Scramble',
    source: 'gsap',
    categories: ['text', 'effect'],
    tags: ['scramble', 'text', 'decode', 'cipher', 'reveal', 'hover', 'glitch'],
    description: 'A text scramble effect that decodes characters one by one, triggered on hover, scroll, or page load.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'SCRAMBLE EFFECT', required: false, description: 'Text to display and scramble', group: 'content' },
      { name: 'speed', type: 'number', default: 50, required: false, description: 'Scramble interval in milliseconds', group: 'behavior' },
      { name: 'characters', type: 'string', default: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*', required: false, description: 'Character set used for scrambling', group: 'advanced' },
      { name: 'trigger', type: 'select', default: 'hover', required: false, options: ['hover', 'scroll', 'load'], description: 'What triggers the scramble animation', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-scramble',
    level: 'primitive',
    code: '<GsapTextScramble text="SCRAMBLE" trigger="hover" />',
    suggestedWith: ['gsap-text-kinetic-typography', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-split-animation',
    name: 'GsapTextSplitAnimation',
    displayName: 'Text Split Animation',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['split', 'text', 'animation', 'fadeUp', 'slideIn', 'rotateIn', 'entrance'],
    description: 'Text split animation that breaks text into characters, words, or lines and animates them in with fadeUp, slideIn, or rotateIn effects.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Beautiful text split animation with GSAP', required: false, description: 'Text to animate', group: 'content' },
      { name: 'splitBy', type: 'select', default: 'char', required: false, options: ['word', 'char', 'line'], description: 'How to split the text', group: 'behavior' },
      { name: 'animation', type: 'select', default: 'fadeUp', required: false, options: ['fadeUp', 'slideIn', 'rotateIn'], description: 'Animation entrance style', group: 'behavior' },
      { name: 'stagger', type: 'number', default: 0.03, required: false, description: 'Delay between each animated unit in seconds', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-split-animation',
    level: 'primitive',
    code: '<GsapTextSplitAnimation text="Hello World" splitBy="char" animation="fadeUp" />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  // ===== NEW GSAP EFFECTS (30 components) =====
  // --- Scroll Effects ---
  {
    id: 'gsap-scroll-image-reveal',
    name: 'GsapScrollImageReveal',
    displayName: 'Image Reveal Scroll',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'image', 'reveal', 'clip-path'],
    description: 'Image reveal with clip-path animation triggered by scroll',
    previewImage: '',
    props: [
      { name: 'imageSrc', type: 'image', required: false, default: '', description: 'Image source URL', group: 'content' },
      { name: 'alt', type: 'string', required: false, default: 'Revealed image', description: 'Alt text for the image', group: 'content' },
      { name: 'direction', type: 'select', required: false, default: 'left', options: ['left', 'right', 'top', 'bottom'], description: 'Direction of the reveal animation', group: 'behavior' },
      { name: 'duration', type: 'number', required: false, default: 1.2, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-image-reveal',
    level: 'effect',
    code: '<GsapScrollImageReveal direction="left" />',
    suggestedWith: ['gsap-scroll-clip-path', 'gsap-scroll-parallax-images'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-text-fade',
    name: 'GsapScrollTextFade',
    displayName: 'Text Fade Scroll',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['scroll', 'text', 'fade', 'paragraph'],
    description: 'Text paragraphs gracefully fade in as they enter the viewport on scroll',
    previewImage: '',
    props: [
      { name: 'paragraphs', type: 'array', required: false, description: 'Array of paragraph strings to display', group: 'content' },
      { name: 'stagger', type: 'number', required: false, default: 0.3, description: 'Stagger delay between paragraphs', group: 'behavior' },
      { name: 'duration', type: 'number', required: false, default: 0.8, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-text-fade',
    level: 'effect',
    code: '<GsapScrollTextFade />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-scroll-split-text'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-rotate-element',
    name: 'GsapScrollRotateElement',
    displayName: 'Rotate on Scroll',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'rotate', 'spin', 'scrub'],
    description: 'Elements rotate as the user scrolls, with configurable rotation angle and scrub',
    previewImage: '',
    props: [
      { name: 'rotation', type: 'number', required: false, default: 360, description: 'Total rotation in degrees', group: 'behavior' },
      { name: 'scrub', type: 'boolean', required: false, default: true, description: 'Link rotation to scroll position', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content to rotate', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-rotate-element',
    level: 'effect',
    code: '<GsapScrollRotateElement rotation={360} scrub />',
    suggestedWith: ['gsap-scroll-skew-element', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-color-change',
    name: 'GsapScrollColorChange',
    displayName: 'Color Change Scroll',
    source: 'gsap',
    categories: ['effect', 'background'],
    tags: ['scroll', 'color', 'background', 'transition'],
    description: 'Background color smoothly transitions between multiple colors as the user scrolls',
    previewImage: '',
    props: [
      { name: 'colors', type: 'array', required: false, description: 'Array of color strings for each section', group: 'style' },
      { name: 'height', type: 'string', required: false, default: '300vh', description: 'Total height of the scrollable area', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to display in sections', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-color-change',
    level: 'effect',
    code: '<GsapScrollColorChange colors={["#0f172a", "#4c1d95", "#ec4899"]} />',
    suggestedWith: ['gsap-scroll-snap-sections', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-split-text',
    name: 'GsapScrollSplitText',
    displayName: 'Split Text Scroll',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['scroll', 'split', 'text', 'letters', 'animation'],
    description: 'Text splits into individual letters and animates with fadeUp, scatter, or wave effects on scroll',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Split Text Animation', description: 'Text to split and animate', group: 'content' },
      { name: 'stagger', type: 'number', required: false, default: 0.03, description: 'Stagger delay between letters', group: 'behavior' },
      { name: 'duration', type: 'number', required: false, default: 0.6, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'animation', type: 'select', required: false, default: 'fadeUp', options: ['fadeUp', 'scatter', 'wave'], description: 'Animation style', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-split-text',
    level: 'effect',
    code: '<GsapScrollSplitText text="Split Text" animation="fadeUp" />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-timeline-vertical',
    name: 'GsapScrollTimelineVertical',
    displayName: 'Vertical Timeline',
    source: 'gsap',
    categories: ['effect', 'layout'],
    tags: ['scroll', 'timeline', 'vertical', 'reveal', 'line'],
    description: 'A vertical timeline with progressive line fill and staggered entry reveals on scroll',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Timeline items with title, description, and date',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Entry title' },
          { name: 'description', type: 'string', required: true, description: 'Entry description' },
          { name: 'date', type: 'string', required: true, description: 'Entry date label' },
        ],
      },
      { name: 'lineColor', type: 'color', required: false, default: '#667eea', description: 'Timeline line and dot color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-timeline-vertical',
    level: 'effect',
    code: '<GsapScrollTimelineVertical />',
    suggestedWith: ['gsap-scroll-timeline-horizontal', 'gsap-scroll-stagger-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-timeline-horizontal',
    name: 'GsapScrollTimelineHorizontal',
    displayName: 'Horizontal Timeline',
    source: 'gsap',
    categories: ['effect', 'layout'],
    tags: ['scroll', 'timeline', 'horizontal', 'pin', 'scrub'],
    description: 'A horizontal timeline that scrolls sideways with pinned viewport and progressive line reveal',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Timeline items with title, description, and date',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Entry title' },
          { name: 'description', type: 'string', required: true, description: 'Entry description' },
          { name: 'date', type: 'string', required: true, description: 'Entry date label' },
        ],
      },
      { name: 'lineColor', type: 'color', required: false, default: '#667eea', description: 'Timeline line and dot color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-timeline-horizontal',
    level: 'effect',
    code: '<GsapScrollTimelineHorizontal />',
    suggestedWith: ['gsap-scroll-timeline-vertical', 'gsap-scroll-horizontal-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-clip-path',
    name: 'GsapScrollClipPath',
    displayName: 'Clip Path Reveal',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'clip-path', 'reveal', 'shape', 'mask'],
    description: 'Content reveals through an expanding clip-path shape (circle, diamond, triangle, or inset) on scroll',
    previewImage: '',
    props: [
      { name: 'shape', type: 'select', required: false, default: 'circle', options: ['circle', 'diamond', 'triangle', 'inset'], description: 'Clip-path shape type', group: 'behavior' },
      { name: 'bgColor', type: 'color', required: false, default: '#667eea', description: 'Revealed area background color', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content inside the revealed area', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-clip-path',
    level: 'effect',
    code: '<GsapScrollClipPath shape="circle" bgColor="#667eea" />',
    suggestedWith: ['gsap-scroll-image-reveal', 'gsap-text-mask-reveal'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-parallax-layers',
    name: 'GsapScrollParallaxLayers',
    displayName: 'Parallax Layers',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'parallax', 'layers', 'depth', '3d'],
    description: 'Multiple layers move at different speeds on scroll to create a parallax depth effect',
    previewImage: '',
    props: [
      {
        name: 'layers',
        type: 'array',
        required: false,
        description: 'Array of layers with content, speed, and color',
        group: 'content',
        itemSchema: [
          { name: 'content', type: 'string', required: true, description: 'Layer text content' },
          { name: 'speed', type: 'number', required: true, description: 'Parallax speed multiplier' },
          { name: 'color', type: 'color', required: true, description: 'Layer background color' },
        ],
      },
      { name: 'height', type: 'string', required: false, default: '150vh', description: 'Container height', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-parallax-layers',
    level: 'effect',
    code: '<GsapScrollParallaxLayers />',
    suggestedWith: ['gsap-scroll-parallax-images', 'gsap-mouse-inertia-gallery'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-skew-element',
    name: 'GsapScrollSkewElement',
    displayName: 'Skew on Scroll',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'skew', 'distort', 'scrub'],
    description: 'Elements skew dynamically as the user scrolls past them',
    previewImage: '',
    props: [
      { name: 'skewAmount', type: 'number', required: false, default: 10, description: 'Maximum skew angle in degrees', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content to skew', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-skew-element',
    level: 'effect',
    code: '<GsapScrollSkewElement skewAmount={10} />',
    suggestedWith: ['gsap-scroll-rotate-element', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-video-scrub',
    name: 'GsapScrollVideoScrub',
    displayName: 'Video Scrub Scroll',
    source: 'gsap',
    categories: ['effect', 'media'],
    tags: ['scroll', 'video', 'scrub', 'playback', 'pin'],
    description: 'Video playback controlled by scroll position with pinned viewport',
    previewImage: '',
    props: [
      { name: 'videoSrc', type: 'string', required: false, default: '', description: 'Video source URL', group: 'content' },
      { name: 'poster', type: 'image', required: false, default: '', description: 'Video poster image', group: 'content' },
      { name: 'height', type: 'string', required: false, default: '300vh', description: 'Scroll height for video scrubbing', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-video-scrub',
    level: 'effect',
    code: '<GsapScrollVideoScrub videoSrc="/video.mp4" />',
    suggestedWith: ['gsap-scroll-video-playback', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-path-animation',
    name: 'GsapScrollPathAnimation',
    displayName: 'Path Draw Scroll',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'svg', 'path', 'draw', 'line'],
    description: 'SVG path drawing animation triggered and controlled by scroll position',
    previewImage: '',
    props: [
      { name: 'strokeColor', type: 'color', required: false, default: '#667eea', description: 'Path stroke color', group: 'style' },
      { name: 'strokeWidth', type: 'number', required: false, default: 3, description: 'Path stroke width', group: 'style' },
      { name: 'duration', type: 'number', required: false, default: 1, description: 'Animation duration multiplier', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-path-animation',
    level: 'effect',
    code: '<GsapScrollPathAnimation strokeColor="#667eea" />',
    suggestedWith: ['gsap-scroll-progress-bar', 'gsap-scroll-clip-path'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-number-counter-scroll',
    name: 'GsapNumberCounterScroll',
    displayName: 'Number Counter Scroll',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['scroll', 'counter', 'number', 'count-up', 'statistics'],
    description: 'Animated number counters that count up when scrolled into view, with prefix and suffix support',
    previewImage: '',
    props: [
      {
        name: 'counters',
        type: 'array',
        required: false,
        description: 'Array of counter items with label, value, prefix, and suffix',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Counter label text' },
          { name: 'value', type: 'number', required: true, description: 'Target counter value' },
          { name: 'prefix', type: 'string', required: false, description: 'Text before the number' },
          { name: 'suffix', type: 'string', required: false, description: 'Text after the number' },
        ],
      },
      { name: 'duration', type: 'number', required: false, default: 2, description: 'Count animation duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-number-counter-scroll',
    level: 'effect',
    code: '<GsapNumberCounterScroll />',
    suggestedWith: ['gsap-scroll-counter', 'gsap-scroll-stagger-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-stagger-list-items',
    name: 'GsapStaggerListItems',
    displayName: 'Stagger List Items',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['scroll', 'stagger', 'list', 'items', 'entrance'],
    description: 'List items stagger in from a configurable direction when scrolled into view',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings for list items', group: 'content' },
      { name: 'stagger', type: 'number', required: false, default: 0.1, description: 'Delay between each item in seconds', group: 'behavior' },
      { name: 'direction', type: 'select', required: false, default: 'up', options: ['left', 'right', 'up', 'down'], description: 'Direction items animate from', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-stagger-list-items',
    level: 'effect',
    code: '<GsapStaggerListItems direction="up" stagger={0.1} />',
    suggestedWith: ['gsap-scroll-stagger-reveal', 'gsap-scroll-text-fade'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-floating-elements',
    name: 'GsapFloatingElements',
    displayName: 'Floating Elements',
    source: 'gsap',
    categories: ['effect', 'background'],
    tags: ['floating', 'random', 'movement', 'shapes', 'ambient'],
    description: 'Decorative shapes float with random movement for ambient background effects',
    previewImage: '',
    props: [
      { name: 'count', type: 'number', required: false, default: 8, description: 'Number of floating elements', group: 'content' },
      { name: 'colors', type: 'array', required: false, description: 'Array of color strings for elements', group: 'style' },
      { name: 'speed', type: 'number', required: false, default: 1, description: 'Animation speed multiplier', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-floating-elements',
    level: 'effect',
    code: '<GsapFloatingElements count={8} speed={1} />',
    suggestedWith: ['gsap-scroll-parallax-layers', 'gsap-mouse-spotlight-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  // --- Hover/Mouse Effects ---
  {
    id: 'gsap-hover-image-distortion',
    name: 'GsapHoverImageDistortion',
    displayName: 'Image Distortion Hover',
    source: 'gsap',
    categories: ['effect', 'media'],
    tags: ['hover', 'image', 'distortion', 'scale', 'skew'],
    description: 'Image scale and skew distortion effect on mouse hover and movement',
    previewImage: '',
    props: [
      { name: 'imageSrc', type: 'image', required: false, default: '', description: 'Image source URL', group: 'content' },
      { name: 'alt', type: 'string', required: false, default: 'Distortion image', description: 'Image alt text', group: 'content' },
      { name: 'scaleAmount', type: 'number', required: false, default: 1.15, description: 'Hover scale amount', group: 'behavior' },
      { name: 'duration', type: 'number', required: false, default: 0.5, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-hover-image-distortion',
    level: 'effect',
    code: '<GsapHoverImageDistortion scaleAmount={1.15} />',
    suggestedWith: ['gsap-hover-reveal-image', 'gsap-mouse-tilt-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-hover-scale-text',
    name: 'GsapHoverScaleText',
    displayName: 'Scale Text Hover',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['hover', 'scale', 'text', 'letter', 'interactive'],
    description: 'Individual letters scale up with color change on hover',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Hover Me', description: 'Text to display', group: 'content' },
      { name: 'scaleAmount', type: 'number', required: false, default: 1.3, description: 'Scale factor on hover', group: 'behavior' },
      { name: 'duration', type: 'number', required: false, default: 0.3, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'color', type: 'color', required: false, default: '#667eea', description: 'Hover color for letters', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-hover-scale-text',
    level: 'effect',
    code: '<GsapHoverScaleText text="Hover Me" scaleAmount={1.3} />',
    suggestedWith: ['gsap-text-wave-animation', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-hover-reveal-image',
    name: 'GsapHoverRevealImage',
    displayName: 'Hover Reveal Image',
    source: 'gsap',
    categories: ['effect', 'media'],
    tags: ['hover', 'reveal', 'image', 'list', 'cursor'],
    description: 'A list of items that reveals a floating image preview following the cursor on hover',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of items with label and image source',
        group: 'content',
        itemSchema: [
          { name: 'label', type: 'string', required: true, description: 'Item label text' },
          { name: 'imageSrc', type: 'image', required: true, description: 'Image source URL' },
        ],
      },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-hover-reveal-image',
    level: 'effect',
    code: '<GsapHoverRevealImage />',
    suggestedWith: ['gsap-hover-image-distortion', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-cursor-trail-effect',
    name: 'GsapCursorTrailEffect',
    displayName: 'Cursor Trail',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'trail', 'mouse', 'particles', 'follow'],
    description: 'A trail of dots that smoothly follows the cursor with decreasing size and opacity',
    previewImage: '',
    props: [
      { name: 'trailCount', type: 'number', required: false, default: 12, description: 'Number of trail dots', group: 'behavior' },
      { name: 'trailColor', type: 'color', required: false, default: '#667eea', description: 'Trail dot color', group: 'style' },
      { name: 'trailSize', type: 'number', required: false, default: 20, description: 'Size of the largest trail dot in pixels', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content inside the trail area', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-cursor-trail-effect',
    level: 'effect',
    code: '<GsapCursorTrailEffect trailCount={12} trailColor="#667eea" />',
    suggestedWith: ['gsap-elastic-cursor', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-elastic-cursor',
    name: 'GsapElasticCursor',
    displayName: 'Elastic Cursor',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'elastic', 'stretch', 'mouse', 'custom-cursor'],
    description: 'An elastic cursor that stretches in the direction of movement with spring physics',
    previewImage: '',
    props: [
      { name: 'size', type: 'number', required: false, default: 40, description: 'Cursor diameter in pixels', group: 'style' },
      { name: 'color', type: 'color', required: false, default: 'rgba(102, 126, 234, 0.6)', description: 'Cursor color', group: 'style' },
      { name: 'elasticity', type: 'number', required: false, default: 0.15, description: 'Elasticity factor (0-1)', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content inside the cursor area', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-elastic-cursor',
    level: 'effect',
    code: '<GsapElasticCursor size={40} elasticity={0.15} />',
    suggestedWith: ['gsap-cursor-trail-effect', 'gsap-mouse-cursor-follower'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-flip-card-animation',
    name: 'GsapFlipCardAnimation',
    displayName: 'Flip Card',
    source: 'gsap',
    categories: ['effect', 'card'],
    tags: ['flip', 'card', '3d', 'hover', 'rotate'],
    description: '3D card that flips on hover to reveal back-side content',
    previewImage: '',
    props: [
      { name: 'frontTitle', type: 'string', required: false, default: 'Front Side', description: 'Front face title', group: 'content' },
      { name: 'frontDescription', type: 'string', required: false, default: 'Hover to flip this card and reveal the back side.', description: 'Front face description', group: 'content' },
      { name: 'backTitle', type: 'string', required: false, default: 'Back Side', description: 'Back face title', group: 'content' },
      { name: 'backDescription', type: 'string', required: false, default: 'This is the hidden content revealed on flip.', description: 'Back face description', group: 'content' },
      { name: 'duration', type: 'number', required: false, default: 0.6, description: 'Flip animation duration in seconds', group: 'behavior' },
      { name: 'width', type: 'number', required: false, default: 350, description: 'Card width in pixels', group: 'style' },
      { name: 'height', type: 'number', required: false, default: 250, description: 'Card height in pixels', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-flip-card-animation',
    level: 'effect',
    code: '<GsapFlipCardAnimation frontTitle="Front" backTitle="Back" />',
    suggestedWith: ['gsap-mouse-tilt-card', 'gsap-drag-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-reveal-menu',
    name: 'GsapRevealMenu',
    displayName: 'Reveal Menu',
    source: 'gsap',
    categories: ['effect', 'navigation'],
    tags: ['menu', 'reveal', 'overlay', 'navigation', 'clip-path'],
    description: 'Animated full-screen menu reveal with circular clip-path expansion and staggered item entrance',
    previewImage: '',
    props: [
      { name: 'menuItems', type: 'array', required: false, description: 'Array of menu item strings', group: 'content' },
      { name: 'bgColor', type: 'color', required: false, default: '#0f172a', description: 'Menu overlay background color', group: 'style' },
      { name: 'accentColor', type: 'color', required: false, default: '#667eea', description: 'Hover accent color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-reveal-menu',
    level: 'effect',
    code: '<GsapRevealMenu menuItems={["Home", "About", "Work", "Contact"]} />',
    suggestedWith: ['gsap-page-transition', 'gsap-scroll-clip-path'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-drag-slider-3d',
    name: 'GsapDragSlider3d',
    displayName: '3D Drag Slider',
    source: 'gsap',
    categories: ['effect', 'media'],
    tags: ['drag', 'slider', '3d', 'perspective', 'carousel'],
    description: 'A draggable slider with 3D perspective rotation and depth scaling based on distance from center',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of slide items with title and image',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Slide title' },
          { name: 'image', type: 'image', required: true, description: 'Slide image URL' },
        ],
      },
      { name: 'perspective', type: 'number', required: false, default: 800, description: 'CSS perspective value in pixels', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-drag-slider-3d',
    level: 'effect',
    code: '<GsapDragSlider3d perspective={800} />',
    suggestedWith: ['gsap-drag-infinite-slider', 'gsap-drag-cards'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  // --- Text Effects ---
  {
    id: 'gsap-text-wave-animation',
    name: 'GsapTextWaveAnimation',
    displayName: 'Text Wave',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['text', 'wave', 'animation', 'loop', 'letters'],
    description: 'Text characters animate in a continuous wave motion',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Wave Animation', description: 'Text to animate', group: 'content' },
      { name: 'speed', type: 'number', required: false, default: 1, description: 'Animation speed multiplier', group: 'behavior' },
      { name: 'amplitude', type: 'number', required: false, default: 20, description: 'Wave height in pixels', group: 'behavior' },
      { name: 'loop', type: 'boolean', required: false, default: true, description: 'Whether the wave loops continuously', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-wave-animation',
    level: 'effect',
    code: '<GsapTextWaveAnimation text="Wave" speed={1} loop />',
    suggestedWith: ['gsap-text-kinetic-typography', 'gsap-text-glitch-effect'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-glitch-effect',
    name: 'GsapTextGlitchEffect',
    displayName: 'Text Glitch',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['text', 'glitch', 'distortion', 'noise', 'cyber'],
    description: 'Glitch text effect with random offset and color layer distortion',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'GLITCH', description: 'Text to display with glitch', group: 'content' },
      { name: 'glitchColor1', type: 'color', required: false, default: '#ff0040', description: 'First glitch layer color', group: 'style' },
      { name: 'glitchColor2', type: 'color', required: false, default: '#00ffff', description: 'Second glitch layer color', group: 'style' },
      { name: 'intensity', type: 'number', required: false, default: 1, description: 'Glitch intensity multiplier', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-glitch-effect',
    level: 'effect',
    code: '<GsapTextGlitchEffect text="GLITCH" intensity={1} />',
    suggestedWith: ['gsap-text-scramble', 'gsap-text-wave-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-mask-reveal',
    name: 'GsapTextMaskReveal',
    displayName: 'Text Mask Reveal',
    source: 'gsap',
    categories: ['effect', 'text'],
    tags: ['text', 'mask', 'reveal', 'clip', 'entrance'],
    description: 'Text words reveal through overflow-hidden masks with staggered slide-up animation',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Masked Text Reveal', description: 'Text to reveal', group: 'content' },
      { name: 'duration', type: 'number', required: false, default: 0.8, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'stagger', type: 'number', required: false, default: 0.1, description: 'Stagger delay between words', group: 'behavior' },
      { name: 'triggerOnScroll', type: 'boolean', required: false, default: true, description: 'Whether to trigger on scroll or on mount', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-mask-reveal',
    level: 'effect',
    code: '<GsapTextMaskReveal text="Reveal This Text" />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-page-transition',
    name: 'GsapPageTransition',
    displayName: 'Page Transition',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['page', 'transition', 'overlay', 'entrance', 'exit'],
    description: 'Full page transition effect with a colored overlay slide animation',
    previewImage: '',
    props: [
      { name: 'overlayColor', type: 'color', required: false, default: '#667eea', description: 'Transition overlay color', group: 'style' },
      { name: 'duration', type: 'number', required: false, default: 0.8, description: 'Transition duration in seconds', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Page content', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-page-transition',
    level: 'effect',
    code: '<GsapPageTransition overlayColor="#667eea" />',
    suggestedWith: ['gsap-loading-sequence', 'gsap-reveal-menu'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-loading-sequence',
    name: 'GsapLoadingSequence',
    displayName: 'Loading Sequence',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['loading', 'sequence', 'progress', 'preloader', 'entrance'],
    description: 'Animated loading sequence with text stagger, progress bar, and counter before content reveal',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', required: false, default: 'Loading', description: 'Loading text', group: 'content' },
      { name: 'barColor', type: 'color', required: false, default: '#667eea', description: 'Progress bar color', group: 'style' },
      { name: 'duration', type: 'number', required: false, default: 2.5, description: 'Total loading duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-loading-sequence',
    level: 'effect',
    code: '<GsapLoadingSequence text="Loading" duration={2.5} />',
    suggestedWith: ['gsap-page-transition', 'gsap-scroll-progress-bar'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  // --- Special Effects ---
  {
    id: 'gsap-smooth-scroll',
    name: 'GsapSmoothScroll',
    displayName: 'Smooth Scroll',
    source: 'gsap',
    categories: ['effect', 'layout'],
    tags: ['smooth', 'scroll', 'lerp', 'wrapper', 'momentum'],
    description: 'Wrapper component that adds smooth momentum-based scrolling to its children',
    previewImage: '',
    props: [
      { name: 'speed', type: 'number', required: false, default: 1, description: 'Scroll speed multiplier', group: 'behavior' },
      { name: 'smoothness', type: 'number', required: false, default: 0.1, description: 'Smoothing factor (0-1, lower is smoother)', group: 'behavior' },
      { name: 'children', type: 'children', required: false, description: 'Content to apply smooth scroll to', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-smooth-scroll',
    level: 'effect',
    code: '<GsapSmoothScroll speed={1} smoothness={0.1}>Content</GsapSmoothScroll>',
    suggestedWith: ['gsap-scroll-parallax-layers', 'gsap-scroll-snap-sections'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-video-playback',
    name: 'GsapScrollVideoPlayback',
    displayName: 'Video Playback Scroll',
    source: 'gsap',
    categories: ['effect', 'media'],
    tags: ['scroll', 'video', 'playback', 'sync', 'pin'],
    description: 'Video playback synced to scroll position with overlay text and pinned viewport',
    previewImage: '',
    props: [
      { name: 'videoSrc', type: 'string', required: false, default: '', description: 'Video source URL', group: 'content' },
      { name: 'poster', type: 'image', required: false, default: '', description: 'Video poster image', group: 'content' },
      { name: 'overlayText', type: 'string', required: false, default: 'Scroll to play', description: 'Text overlay displayed on the video', group: 'content' },
      { name: 'scrubSmooth', type: 'number', required: false, default: 0.5, description: 'Scrub smoothing factor', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional classes', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-video-playback',
    level: 'effect',
    code: '<GsapScrollVideoPlayback videoSrc="/video.mp4" />',
    suggestedWith: ['gsap-scroll-video-scrub', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
]
