import type { ComponentRegistryItem } from '../types'

export const gsapEffects: ComponentRegistryItem[] = [
  {
    id: 'gsap-drag-cards',
    name: 'GsapDragCards',
    displayName: 'Drag Cards',
    source: 'gsap',
    categories: ['card', 'animation'],
    tags: ['drag', 'cards', 'draggable', 'interactive', 'stack'],
    description: 'A stack of draggable cards with inertia physics. Cards can be picked up, tossed, and rearranged with smooth elastic snap-back animations.',
    previewImage: '',
    props: [
      {
        name: 'cards',
        type: 'array',
        required: false,
        description: 'Array of card objects with title, image, and rotation',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Card title' },
          { name: 'image', type: 'image', required: true, description: 'Card image URL' },
          { name: 'rotation', type: 'number', required: true, description: 'Initial rotation angle in degrees' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-drag-cards',
    level: 'primitive',
    code: '<GsapDragCards cards={[{ title: "Card One", image: "/img.jpg", rotation: -5 }]} />',
    suggestedWith: ['gsap-mouse-tilt-card', 'gsap-drag-infinite-slider'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-drag-infinite-slider',
    name: 'GsapDragInfiniteSlider',
    displayName: 'Drag Infinite Slider',
    source: 'gsap',
    categories: ['animation', 'media'],
    tags: ['drag', 'slider', 'infinite', 'carousel', 'loop', 'auto-scroll'],
    description: 'An infinite looping slider that can be dragged and auto-scrolls. Supports horizontal and vertical directions with seamless wrapping.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of slider items with content and image',
        group: 'content',
        itemSchema: [
          { name: 'content', type: 'string', required: true, description: 'Item title text' },
          { name: 'image', type: 'image', required: true, description: 'Item image URL' },
        ],
      },
      {
        name: 'direction',
        type: 'select',
        default: 'horizontal',
        required: false,
        options: ['horizontal', 'vertical'],
        description: 'Scroll direction of the slider',
        group: 'behavior',
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-drag-infinite-slider',
    level: 'section',
    code: '<GsapDragInfiniteSlider direction="horizontal" />',
    suggestedWith: ['gsap-drag-cards', 'gsap-scroll-infinite-marquee'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-mouse-cursor-follower',
    name: 'GsapMouseCursorFollower',
    displayName: 'Cursor Follower',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['cursor', 'follower', 'mouse', 'interactive', 'custom-cursor'],
    description: 'A custom cursor follower with a smooth trailing circle and dot that tracks mouse movement with configurable size, color, and blend mode.',
    previewImage: '',
    props: [
      { name: 'size', type: 'number', default: 40, required: false, description: 'Diameter of the follower circle in pixels', group: 'style' },
      { name: 'color', type: 'color', default: 'rgba(102, 126, 234, 0.6)', required: false, description: 'Color of the follower circle', group: 'style' },
      { name: 'mixBlendMode', type: 'select', default: 'difference', required: false, options: ['difference', 'multiply', 'screen', 'overlay', 'normal'], description: 'CSS mix-blend-mode for the cursor circle', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to display inside the cursor area', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-cursor-follower',
    level: 'effect',
    code: '<GsapMouseCursorFollower size={40} color="rgba(102,126,234,0.6)">Content here</GsapMouseCursorFollower>',
    suggestedWith: ['gsap-mouse-spotlight-effect', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-inertia-gallery',
    name: 'GsapMouseInertiaGallery',
    displayName: 'Inertia Gallery',
    source: 'gsap',
    categories: ['media', 'animation'],
    tags: ['gallery', 'inertia', 'mouse', 'parallax', 'images', 'interactive'],
    description: 'An image grid that reacts to mouse movement with inertia-based parallax. Each image moves at a different depth for a layered 3D feel.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with src and alt text',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text for the image' },
        ],
      },
      { name: 'columns', type: 'number', default: 3, required: false, description: 'Number of grid columns', group: 'style' },
      { name: 'imageSize', type: 'number', default: 200, required: false, description: 'Size of each image in pixels', group: 'style' },
      { name: 'velocity', type: 'number', default: 0.15, required: false, description: 'Movement velocity multiplier', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-inertia-gallery',
    level: 'section',
    code: '<GsapMouseInertiaGallery columns={3} imageSize={200} velocity={0.15} />',
    suggestedWith: ['gsap-scroll-parallax-images', 'gsap-mouse-tilt-card'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-mouse-magnetic-element',
    name: 'GsapMouseMagneticElement',
    displayName: 'Magnetic Element',
    source: 'gsap',
    categories: ['effect', 'animation'],
    tags: ['magnetic', 'hover', 'mouse', 'interactive', 'button', 'attraction'],
    description: 'An element that magnetically attracts toward the cursor when nearby, with elastic snap-back. Perfect for buttons and CTAs.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Content to make magnetic', group: 'content' },
      { name: 'strength', type: 'number', default: 0.4, required: false, description: 'Magnetic attraction strength (0-1)', group: 'behavior' },
      { name: 'radius', type: 'number', default: 200, required: false, description: 'Magnetic effect radius in pixels', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-magnetic-element',
    level: 'effect',
    code: '<GsapMouseMagneticElement strength={0.4} radius={200}><button>Hover me</button></GsapMouseMagneticElement>',
    suggestedWith: ['gsap-mouse-cursor-follower', 'gsap-mouse-tilt-card'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-spotlight-effect',
    name: 'GsapMouseSpotlightEffect',
    displayName: 'Spotlight Effect',
    source: 'gsap',
    categories: ['effect', 'background'],
    tags: ['spotlight', 'mouse', 'glow', 'radial', 'light', 'reveal'],
    description: 'A radial spotlight that follows the cursor, creating a dramatic reveal effect over dark backgrounds. Configurable radius, color, and intensity.',
    previewImage: '',
    props: [
      { name: 'radius', type: 'number', default: 200, required: false, description: 'Spotlight radius in pixels', group: 'style' },
      { name: 'color', type: 'color', default: 'rgba(102, 126, 234, 0.3)', required: false, description: 'Spotlight color', group: 'style' },
      { name: 'intensity', type: 'number', default: 1, required: false, description: 'Spotlight opacity intensity (0-1)', group: 'style' },
      { name: 'children', type: 'children', required: false, description: 'Content to display under the spotlight', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-spotlight-effect',
    level: 'effect',
    code: '<GsapMouseSpotlightEffect radius={200} color="rgba(102,126,234,0.3)"><h2>Spotlight</h2></GsapMouseSpotlightEffect>',
    suggestedWith: ['gsap-mouse-cursor-follower', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-mouse-tilt-card',
    name: 'GsapMouseTiltCard',
    displayName: 'Tilt Card',
    source: 'gsap',
    categories: ['card', 'effect'],
    tags: ['tilt', '3d', 'perspective', 'card', 'hover', 'glare'],
    description: 'A 3D tilt card that responds to cursor position with perspective rotation and a dynamic glare overlay effect.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Tilt Card', required: false, description: 'Card title text', group: 'content' },
      { name: 'description', type: 'string', default: 'Move your mouse over this card to see the 3D tilt effect.', required: false, description: 'Card description text', group: 'content' },
      { name: 'image', type: 'image', default: 'https://picsum.photos/seed/tilt/400/250', required: false, description: 'Card cover image URL', group: 'content' },
      { name: 'maxTilt', type: 'number', default: 15, required: false, description: 'Maximum tilt angle in degrees', group: 'behavior' },
      { name: 'perspective', type: 'number', default: 1000, required: false, description: 'CSS perspective value in pixels', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-mouse-tilt-card',
    level: 'primitive',
    code: '<GsapMouseTiltCard title="My Card" image="/card.jpg" maxTilt={15} />',
    suggestedWith: ['gsap-drag-cards', 'gsap-mouse-magnetic-element'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-counter',
    name: 'GsapScrollCounter',
    displayName: 'Scroll Counter',
    source: 'gsap',
    categories: ['animation', 'text'],
    tags: ['counter', 'number', 'scroll', 'count-up', 'statistics', 'animate'],
    description: 'An animated number counter that counts up when scrolled into view. Supports prefix, suffix, and decimal formatting.',
    previewImage: '',
    props: [
      { name: 'endValue', type: 'number', default: 1234, required: false, description: 'Target number to count to', group: 'content' },
      { name: 'duration', type: 'number', default: 2, required: false, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'prefix', type: 'string', default: '', required: false, description: 'Text before the number (e.g. "$")', group: 'content' },
      { name: 'suffix', type: 'string', default: '', required: false, description: 'Text after the number (e.g. "+")', group: 'content' },
      { name: 'decimals', type: 'number', default: 0, required: false, description: 'Number of decimal places', group: 'content' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-counter',
    level: 'primitive',
    code: '<GsapScrollCounter endValue={1234} prefix="$" suffix="+" />',
    suggestedWith: ['gsap-scroll-stagger-reveal', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-horizontal-section',
    name: 'GsapScrollHorizontalSection',
    displayName: 'Horizontal Scroll Section',
    source: 'gsap',
    categories: ['section', 'layout', 'animation'],
    tags: ['horizontal', 'scroll', 'section', 'pin', 'scrub', 'fullscreen'],
    description: 'Full-viewport horizontal scrolling sections pinned to the screen. Vertical scroll is translated into horizontal movement.',
    previewImage: '',
    props: [
      {
        name: 'sections',
        type: 'array',
        required: false,
        description: 'Array of section objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Section heading' },
          { name: 'content', type: 'string', required: true, description: 'Section body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Section background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-horizontal-section',
    level: 'section',
    code: '<GsapScrollHorizontalSection sections={[{ title: "One", content: "...", bgColor: "#1a1a2e" }]} />',
    suggestedWith: ['gsap-scroll-snap-sections', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-infinite-marquee',
    name: 'GsapScrollInfiniteMarquee',
    displayName: 'Infinite Marquee',
    source: 'gsap',
    categories: ['animation', 'text'],
    tags: ['marquee', 'infinite', 'scroll', 'ticker', 'loop', 'speed-boost'],
    description: 'An infinite scrolling text marquee that speeds up when the page is scrolled. Supports left/right direction and pause on hover.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of text strings to display', group: 'content' },
      { name: 'speed', type: 'number', default: 50, required: false, description: 'Base scroll speed in pixels per second', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, options: ['left', 'right'], description: 'Marquee scroll direction', group: 'behavior' },
      { name: 'pauseOnHover', type: 'boolean', default: true, required: false, description: 'Pause marquee on mouse hover', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-infinite-marquee',
    level: 'primitive',
    code: '<GsapScrollInfiniteMarquee items={["Design", "Develop", "Deploy"]} speed={50} />',
    suggestedWith: ['gsap-drag-infinite-slider', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-parallax-images',
    name: 'GsapScrollParallaxImages',
    displayName: 'Parallax Images',
    source: 'gsap',
    categories: ['media', 'animation'],
    tags: ['parallax', 'images', 'scroll', 'depth', 'gallery'],
    description: 'A responsive image grid where each image moves at a different parallax speed on scroll, creating a layered depth effect.',
    previewImage: '',
    props: [
      {
        name: 'images',
        type: 'array',
        required: false,
        description: 'Array of images with source, alt text, and parallax speed',
        group: 'content',
        itemSchema: [
          { name: 'src', type: 'image', required: true, description: 'Image source URL' },
          { name: 'alt', type: 'string', required: true, description: 'Alt text' },
          { name: 'speed', type: 'number', required: true, description: 'Parallax speed multiplier' },
        ],
      },
      { name: 'gap', type: 'number', default: 24, required: false, description: 'Gap between images in pixels', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-parallax-images',
    level: 'section',
    code: '<GsapScrollParallaxImages gap={24} />',
    suggestedWith: ['gsap-mouse-inertia-gallery', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-pin-section',
    name: 'GsapScrollPinSection',
    displayName: 'Pin Section',
    source: 'gsap',
    categories: ['section', 'animation'],
    tags: ['pin', 'sticky', 'scroll', 'section', 'fixed', 'reveal'],
    description: 'A section that pins in place while content animates in and out on scroll. Title and content fade in, hold, then fade away.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Pinned Section', required: false, description: 'Section heading', group: 'content' },
      { name: 'content', type: 'string', default: 'This section stays fixed while you scroll.', required: false, description: 'Section body text', group: 'content' },
      { name: 'bgColor', type: 'color', default: '#0f172a', required: false, description: 'Background color', group: 'style' },
      { name: 'duration', type: 'number', default: 300, required: false, description: 'Scroll distance as percentage of viewport', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-pin-section',
    level: 'section',
    code: '<GsapScrollPinSection title="Pinned" content="This stays fixed while you scroll." />',
    suggestedWith: ['gsap-scroll-horizontal-section', 'gsap-scroll-snap-sections'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-progress-bar',
    name: 'GsapScrollProgressBar',
    displayName: 'Scroll Progress Bar',
    source: 'gsap',
    categories: ['effect', 'navigation'],
    tags: ['progress', 'scroll', 'bar', 'indicator', 'fixed', 'reading'],
    description: 'A fixed progress bar that scales horizontally to indicate overall page scroll progress. Can be positioned at top or bottom.',
    previewImage: '',
    props: [
      { name: 'color', type: 'color', default: '#667eea', required: false, description: 'Progress bar color', group: 'style' },
      { name: 'height', type: 'number', default: 4, required: false, description: 'Bar height in pixels', group: 'style' },
      { name: 'position', type: 'select', default: 'top', required: false, options: ['top', 'bottom'], description: 'Fixed position on the viewport', group: 'style' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-progress-bar',
    level: 'effect',
    code: '<GsapScrollProgressBar color="#667eea" height={4} position="top" />',
    suggestedWith: ['gsap-scroll-snap-sections', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-scale-on-scroll',
    name: 'GsapScrollScale',
    displayName: 'Scale on Scroll',
    source: 'gsap',
    categories: ['animation', 'effect'],
    tags: ['scale', 'scroll', 'zoom', 'grow', 'reveal', 'scrub'],
    description: 'An element that scales up from small to full size as the user scrolls, with optional scrub for direct scroll-linked motion.',
    previewImage: '',
    props: [
      { name: 'children', type: 'children', required: false, description: 'Content to scale on scroll', group: 'content' },
      { name: 'scaleFrom', type: 'number', default: 0.6, required: false, description: 'Starting scale value', group: 'behavior' },
      { name: 'scaleTo', type: 'number', default: 1, required: false, description: 'Ending scale value', group: 'behavior' },
      { name: 'scrub', type: 'boolean', default: true, required: false, description: 'Link animation directly to scroll position', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-scale-on-scroll',
    level: 'effect',
    code: '<GsapScrollScale scaleFrom={0.6} scaleTo={1}><div>Scale me</div></GsapScrollScale>',
    suggestedWith: ['gsap-scroll-stagger-reveal', 'gsap-scroll-text-reveal'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'gsap-scroll-snap-sections',
    name: 'GsapScrollSnapSections',
    displayName: 'Snap Sections',
    source: 'gsap',
    categories: ['section', 'layout', 'animation'],
    tags: ['snap', 'scroll', 'sections', 'fullscreen', 'paging'],
    description: 'Full-height sections with scroll snapping that locks each section into view. Content animates in with staggered reveal.',
    previewImage: '',
    props: [
      {
        name: 'sections',
        type: 'array',
        required: false,
        description: 'Array of section objects with title, content, and background color',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Section heading' },
          { name: 'content', type: 'string', required: true, description: 'Section body text' },
          { name: 'bgColor', type: 'color', required: true, description: 'Section background color' },
        ],
      },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-snap-sections',
    level: 'section',
    code: '<GsapScrollSnapSections sections={[{ title: "Welcome", content: "...", bgColor: "#0f172a" }]} />',
    suggestedWith: ['gsap-scroll-horizontal-section', 'gsap-scroll-pin-section'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-stagger-reveal',
    name: 'GsapScrollStaggerReveal',
    displayName: 'Stagger Reveal',
    source: 'gsap',
    categories: ['animation', 'card'],
    tags: ['stagger', 'reveal', 'scroll', 'cards', 'grid', 'entrance'],
    description: 'A grid of cards that reveal with a staggered animation on scroll. Supports directional entrance from up, down, left, or right.',
    previewImage: '',
    props: [
      {
        name: 'items',
        type: 'array',
        required: false,
        description: 'Array of items with title and description',
        group: 'content',
        itemSchema: [
          { name: 'title', type: 'string', required: true, description: 'Item title' },
          { name: 'description', type: 'string', required: true, description: 'Item description' },
        ],
      },
      { name: 'stagger', type: 'number', default: 0.15, required: false, description: 'Delay between each item animation in seconds', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'up', required: false, options: ['up', 'down', 'left', 'right'], description: 'Direction items animate from', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-stagger-reveal',
    level: 'section',
    code: '<GsapScrollStaggerReveal direction="up" stagger={0.15} />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-scroll-scale-on-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-scroll-text-reveal',
    name: 'GsapScrollTextReveal',
    displayName: 'Scroll Text Reveal',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['text', 'reveal', 'scroll', 'split', 'word', 'character', 'scrub'],
    description: 'Text that reveals word-by-word or character-by-character as the user scrolls. Scrub mode ties the animation directly to scroll position.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Scroll to reveal this amazing text animation that brings words to life as you navigate down the page.', required: false, description: 'Text content to reveal', group: 'content' },
      { name: 'splitBy', type: 'select', default: 'word', required: false, options: ['word', 'char', 'line'], description: 'How to split the text for animation', group: 'behavior' },
      { name: 'stagger', type: 'number', default: 0.05, required: false, description: 'Delay between each unit reveal', group: 'behavior' },
      { name: 'scrub', type: 'boolean', default: true, required: false, description: 'Link animation to scroll position', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-scroll-text-reveal',
    level: 'primitive',
    code: '<GsapScrollTextReveal text="Reveal this text on scroll" splitBy="word" />',
    suggestedWith: ['gsap-text-split-animation', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-kinetic-typography',
    name: 'GsapKineticTypography',
    displayName: 'Kinetic Typography',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['kinetic', 'typography', 'wave', 'bounce', 'elastic', 'rotate', 'characters'],
    description: 'Animated kinetic typography with multiple animation modes including wave, bounce, elastic, and stagger-rotate effects on individual characters.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'KINETIC', required: false, description: 'Text to animate', group: 'content' },
      { name: 'animation', type: 'select', default: 'wave', required: false, options: ['wave', 'bounce', 'elastic', 'stagger-rotate'], description: 'Animation style', group: 'behavior' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Animation speed multiplier', group: 'behavior' },
      { name: 'loop', type: 'boolean', default: true, required: false, description: 'Whether the animation loops continuously', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-kinetic-typography',
    level: 'primitive',
    code: '<GsapKineticTypography text="KINETIC" animation="wave" loop />',
    suggestedWith: ['gsap-text-scramble', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-scramble',
    name: 'GsapTextScramble',
    displayName: 'Text Scramble',
    source: 'gsap',
    categories: ['text', 'effect'],
    tags: ['scramble', 'text', 'decode', 'cipher', 'reveal', 'hover', 'glitch'],
    description: 'A text scramble effect that decodes characters one by one, triggered on hover, scroll, or page load.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'SCRAMBLE EFFECT', required: false, description: 'Text to display and scramble', group: 'content' },
      { name: 'speed', type: 'number', default: 50, required: false, description: 'Scramble interval in milliseconds', group: 'behavior' },
      { name: 'characters', type: 'string', default: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*', required: false, description: 'Character set used for scrambling', group: 'advanced' },
      { name: 'trigger', type: 'select', default: 'hover', required: false, options: ['hover', 'scroll', 'load'], description: 'What triggers the scramble animation', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-scramble',
    level: 'primitive',
    code: '<GsapTextScramble text="SCRAMBLE" trigger="hover" />',
    suggestedWith: ['gsap-text-kinetic-typography', 'gsap-text-split-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'gsap-text-split-animation',
    name: 'GsapTextSplitAnimation',
    displayName: 'Text Split Animation',
    source: 'gsap',
    categories: ['text', 'animation'],
    tags: ['split', 'text', 'animation', 'fadeUp', 'slideIn', 'rotateIn', 'entrance'],
    description: 'Text split animation that breaks text into characters, words, or lines and animates them in with fadeUp, slideIn, or rotateIn effects.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Beautiful text split animation with GSAP', required: false, description: 'Text to animate', group: 'content' },
      { name: 'splitBy', type: 'select', default: 'char', required: false, options: ['word', 'char', 'line'], description: 'How to split the text', group: 'behavior' },
      { name: 'animation', type: 'select', default: 'fadeUp', required: false, options: ['fadeUp', 'slideIn', 'rotateIn'], description: 'Animation entrance style', group: 'behavior' },
      { name: 'stagger', type: 'number', default: 0.03, required: false, description: 'Delay between each animated unit in seconds', group: 'behavior' },
    ],
    dependencies: ['gsap'],
    modulePath: 'gsap-text-split-animation',
    level: 'primitive',
    code: '<GsapTextSplitAnimation text="Hello World" splitBy="char" animation="fadeUp" />',
    suggestedWith: ['gsap-scroll-text-reveal', 'gsap-text-kinetic-typography'],
    version: '1.0.0',
    acceptsChildren: false,
  },
]
