import type { ComponentRegistryItem } from '../types'

export const skiperComponents: ComponentRegistryItem[] = [
  {
    id: 'skiper-animated-number',
    name: 'SkiperAnimatedNumber',
    displayName: 'Animated Number',
    source: 'skiper',
    categories: ['text', 'animation'],
    tags: ['number', 'counter', 'animated', 'statistics', 'count-up'],
    description: 'Animated number counter that springs from zero to a target value when scrolled into view.',
    previewImage: '',
    props: [
      { name: 'value', type: 'number', default: 12847, required: false, description: 'Target number value', group: 'content' },
      { name: 'duration', type: 'number', default: 2, required: false, description: 'Animation duration in seconds', group: 'behavior' },
      { name: 'prefix', type: 'string', default: '', required: false, description: 'Text before the number', group: 'content' },
      { name: 'suffix', type: 'string', default: '+', required: false, description: 'Text after the number', group: 'content' },
      { name: 'decimals', type: 'number', default: 0, required: false, description: 'Number of decimal places', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-animated-number',
    level: 'primitive',
    code: '<SkiperAnimatedNumber value={9999} suffix="+" duration={2} />',
    suggestedWith: ['skiper-rolling-text', 'skiper-horizontal-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-apple-feature-block',
    name: 'SkiperAppleFeatureBlock',
    displayName: 'Apple Feature Block',
    source: 'skiper',
    categories: ['feature', 'section'],
    tags: ['apple', 'features', 'cards', 'grid', 'scroll-reveal'],
    description: 'Apple-inspired feature section with large heading, subtitle, and scroll-triggered feature cards with image zoom.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Designed for the future.', required: false, description: 'Section title', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Packed with features that redefine...', required: false, description: 'Section subtitle', group: 'content' },
      { name: 'features', type: 'array', required: false, description: 'Array of feature objects with title, description, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-apple-feature-block',
    level: 'section',
    code: '<SkiperAppleFeatureBlock title="Features" features={[{ title: "Fast", description: "Blazing speed", image: "/img.jpg" }]} />',
    suggestedWith: ['skiper-projects-showcase', 'skiper-card-stack-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-apple-nav-bar',
    name: 'SkiperAppleNavBar',
    displayName: 'Apple Nav Bar',
    source: 'skiper',
    categories: ['navigation', 'header'],
    tags: ['apple', 'navbar', 'navigation', 'dropdown', 'responsive'],
    description: 'Apple-style navigation bar with animated dropdowns, mobile hamburger menu, and CTA button.',
    previewImage: '',
    props: [
      { name: 'logo', type: 'string', default: 'Acme', required: false, description: 'Logo text', group: 'content' },
      { name: 'items', type: 'array', required: false, description: 'Array of nav items with label, href, and optional children', group: 'content' },
      { name: 'ctaText', type: 'string', default: 'Get Started', required: false, description: 'CTA button text', group: 'content' },
      { name: 'ctaLink', type: 'string', default: '#', required: false, description: 'CTA button link', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-apple-nav-bar',
    level: 'primitive',
    code: '<SkiperAppleNavBar logo="Acme" ctaText="Get Started" />',
    suggestedWith: ['skiper-vercel-navigation', 'skiper-text-roll-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-canvas-crowd',
    name: 'SkiperCanvasCrowd',
    displayName: 'Canvas Crowd',
    source: 'skiper',
    categories: ['background', 'effect'],
    tags: ['canvas', 'particles', 'crowd', 'interactive', 'mouse'],
    description: 'Interactive canvas particle system with connected nodes that repel from mouse cursor movement.',
    previewImage: '',
    props: [
      { name: 'particleCount', type: 'number', default: 80, required: false, description: 'Number of particles', group: 'behavior' },
      { name: 'colors', type: 'array', default: ['#6366f1', '#ec4899', '#14b8a6', '#f97316', '#8b5cf6'], required: false, description: 'Particle colors array', group: 'style' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Particle movement speed', group: 'behavior' },
      { name: 'title', type: 'string', default: 'Crowd Simulation', required: false, description: 'Overlay title', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Interactive particle system...', required: false, description: 'Overlay subtitle', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-canvas-crowd',
    level: 'section',
    code: '<SkiperCanvasCrowd particleCount={80} speed={1} title="Particles" />',
    suggestedWith: ['skiper-interactive-3d-hero', 'skiper-pixel-preloader'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-card-stack-scroll',
    name: 'SkiperCardStackScroll',
    displayName: 'Card Stack Scroll',
    source: 'skiper',
    categories: ['section', 'animation'],
    tags: ['cards', 'stack', 'scroll', 'sticky', 'parallax'],
    description: 'Scroll-driven stacking card layout where cards scale down and fade as new ones come into view.',
    previewImage: '',
    props: [
      { name: 'cards', type: 'array', required: false, description: 'Array of card objects with title, description, image, and color', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-card-stack-scroll',
    level: 'section',
    code: '<SkiperCardStackScroll cards={[{ title: "Design", description: "Create", image: "/img.jpg", color: "#6366f1" }]} />',
    suggestedWith: ['skiper-apple-feature-block', 'skiper-parallax-scroll'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-drawing-cursor-effect',
    name: 'SkiperDrawingCursorEffect',
    displayName: 'Drawing Cursor Effect',
    source: 'skiper',
    categories: ['effect', 'other'],
    tags: ['drawing', 'cursor', 'canvas', 'interactive', 'svg'],
    description: 'SVG drawing canvas where users can draw with mouse clicks and strokes fade out over time.',
    previewImage: '',
    props: [
      { name: 'strokeColor', type: 'color', default: '#6366f1', required: false, description: 'Drawing stroke color', group: 'style' },
      { name: 'strokeWidth', type: 'number', default: 3, required: false, description: 'Stroke width in pixels', group: 'style' },
      { name: 'fadeSpeed', type: 'number', default: 2, required: false, description: 'Stroke fade time in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-drawing-cursor-effect',
    level: 'primitive',
    code: '<SkiperDrawingCursorEffect strokeColor="#6366f1" strokeWidth={3} fadeSpeed={2} />',
    suggestedWith: ['skiper-image-cursor-trail', 'skiper-canvas-crowd'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-dynamic-island',
    name: 'SkiperDynamicIsland',
    displayName: 'Dynamic Island',
    source: 'skiper',
    categories: ['other', 'animation'],
    tags: ['dynamic-island', 'apple', 'notification', 'pill', 'expandable'],
    description: 'Apple Dynamic Island-inspired component that expands from a pill shape to show contextual content.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of island items with icon, label, and expandedContent', group: 'content' },
      { name: 'variant', type: 'select', default: 'default', required: false, description: 'Island size variant', options: ['default', 'compact', 'wide'], group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-dynamic-island',
    level: 'primitive',
    code: '<SkiperDynamicIsland variant="default" />',
    suggestedWith: ['skiper-apple-nav-bar', 'skiper-vercel-tooltip'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-expand-on-hover',
    name: 'SkiperExpandOnHover',
    displayName: 'Expand on Hover',
    source: 'skiper',
    categories: ['card', 'animation'],
    tags: ['expand', 'hover', 'accordion', 'cards', 'animated'],
    description: 'Vertical list of cards that expand to reveal content and an image preview on hover.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of items with title, content, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-expand-on-hover',
    level: 'section',
    code: '<SkiperExpandOnHover items={[{ title: "Web Apps", content: "Description", image: "/img.jpg" }]} />',
    suggestedWith: ['skiper-hover-expand', 'skiper-hover-members'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-horizontal-text-reveal',
    name: 'SkiperHorizontalTextReveal',
    displayName: 'Horizontal Text Reveal',
    source: 'skiper',
    categories: ['text', 'animation'],
    tags: ['text', 'reveal', 'horizontal', 'scroll', 'clip-path'],
    description: 'Large text that reveals from left to right with a clip-path animation driven by scroll progress.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Creative Development Studio', required: false, description: 'Text to reveal', group: 'content' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Reveal speed multiplier', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-horizontal-text-reveal',
    level: 'section',
    code: '<SkiperHorizontalTextReveal text="Creative Studio" speed={1} />',
    suggestedWith: ['skiper-text-reveal-box', 'skiper-text-scroll-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-hover-expand',
    name: 'SkiperHoverExpand',
    displayName: 'Hover Expand',
    source: 'skiper',
    categories: ['card', 'media', 'animation'],
    tags: ['hover', 'expand', 'gallery', 'images', 'flex'],
    description: 'Horizontal row of image panels where hovering one expands it while others shrink proportionally.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of items with title, image, and description', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-hover-expand',
    level: 'section',
    code: '<SkiperHoverExpand items={[{ title: "Strategy", image: "/img.jpg", description: "Details" }]} />',
    suggestedWith: ['skiper-expand-on-hover', 'skiper-projects-showcase'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-hover-members',
    name: 'SkiperHoverMembers',
    displayName: 'Hover Members',
    source: 'skiper',
    categories: ['section', 'animation'],
    tags: ['team', 'members', 'hover', 'list', 'image-popup'],
    description: 'Team member list where hovering a name slides the text and reveals a floating portrait image.',
    previewImage: '',
    props: [
      { name: 'members', type: 'array', required: false, description: 'Array of members with name, role, and image', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-hover-members',
    level: 'section',
    code: '<SkiperHoverMembers members={[{ name: "Alex", role: "CEO", image: "/avatar.jpg" }]} />',
    suggestedWith: ['skiper-expand-on-hover', 'skiper-vercel-tooltip'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-image-cursor-trail',
    name: 'SkiperImageCursorTrail',
    displayName: 'Image Cursor Trail',
    source: 'skiper',
    categories: ['effect', 'media'],
    tags: ['cursor', 'trail', 'images', 'interactive', 'mouse'],
    description: 'Interactive effect where images appear and trail behind the cursor as it moves across the container.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs for the trail', group: 'content' },
      { name: 'trailLength', type: 'number', default: 8, required: false, description: 'Maximum trail images shown', group: 'behavior' },
      { name: 'fadeSpeed', type: 'number', default: 0.8, required: false, description: 'Fade-out speed in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-image-cursor-trail',
    level: 'primitive',
    code: '<SkiperImageCursorTrail images={["/img1.jpg", "/img2.jpg"]} trailLength={8} />',
    suggestedWith: ['skiper-drawing-cursor-effect', 'skiper-canvas-crowd'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-infinite-canvas',
    name: 'SkiperInfiniteCanvas',
    displayName: 'Infinite Canvas',
    source: 'skiper',
    categories: ['layout', 'other'],
    tags: ['canvas', 'infinite', 'pan', 'zoom', 'draggable'],
    description: 'Pannable and zoomable infinite canvas with positioned content items and a dot grid background.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of canvas items with content and position coordinates', group: 'content' },
      { name: 'backgroundColor', type: 'color', default: '#0a0a0a', required: false, description: 'Canvas background color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-infinite-canvas',
    level: 'primitive',
    code: '<SkiperInfiniteCanvas backgroundColor="#0a0a0a" />',
    suggestedWith: ['skiper-drawing-cursor-effect', 'skiper-canvas-crowd'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-interactive-3d-hero',
    name: 'SkiperInteractive3DHero',
    displayName: 'Interactive 3D Hero',
    source: 'skiper',
    categories: ['hero', 'animation'],
    tags: ['3d', 'hero', 'interactive', 'perspective', 'mouse-follow'],
    description: 'Hero section with mouse-following 3D perspective tilt, floating CSS cube, animated blobs, and CTA.',
    previewImage: '',
    props: [
      { name: 'title', type: 'string', default: 'Build the future\nof the web', required: false, description: 'Hero title (supports newlines)', group: 'content' },
      { name: 'subtitle', type: 'string', default: 'Create stunning interactive experiences...', required: false, description: 'Subtitle text', group: 'content' },
      { name: 'ctaText', type: 'string', default: 'Get Started', required: false, description: 'CTA button text', group: 'content' },
      { name: 'ctaLink', type: 'string', default: '#', required: false, description: 'CTA button link', group: 'content' },
      { name: 'modelUrl', type: 'image', required: false, description: 'Optional 3D model image URL', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-interactive-3d-hero',
    level: 'section',
    code: '<SkiperInteractive3DHero title="Build the future" ctaText="Get Started" />',
    suggestedWith: ['skiper-canvas-crowd', 'skiper-apple-nav-bar'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-parallax-scroll',
    name: 'SkiperParallaxScroll',
    displayName: 'Parallax Scroll',
    source: 'skiper',
    categories: ['media', 'animation'],
    tags: ['parallax', 'scroll', 'images', 'gallery', 'columns'],
    description: 'Three-column image gallery with parallax scroll effect where columns move at different speeds.',
    previewImage: '',
    props: [
      { name: 'images', type: 'array', required: false, description: 'Array of image URLs distributed across columns', group: 'content' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Parallax speed multiplier', group: 'behavior' },
      { name: 'gap', type: 'number', default: 8, required: false, description: 'Gap between images (multiplied by 4px)', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-parallax-scroll',
    level: 'section',
    code: '<SkiperParallaxScroll images={["/img1.jpg", "/img2.jpg", "/img3.jpg"]} speed={1} />',
    suggestedWith: ['skiper-card-stack-scroll', 'skiper-hover-expand'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-pixel-preloader',
    name: 'SkiperPixelPreloader',
    displayName: 'Pixel Preloader',
    source: 'skiper',
    categories: ['animation', 'effect'],
    tags: ['pixel', 'preloader', 'loading', 'grid', 'transition'],
    description: 'Pixel grid preloader animation that fills and clears cells in a randomized staggered pattern.',
    previewImage: '',
    props: [
      { name: 'gridSize', type: 'number', default: 10, required: false, description: 'Grid dimension (NxN)', group: 'behavior' },
      { name: 'color', type: 'color', default: '#6366f1', required: false, description: 'Pixel fill color', group: 'style' },
      { name: 'speed', type: 'number', default: 0.05, required: false, description: 'Animation speed factor', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-pixel-preloader',
    level: 'primitive',
    code: '<SkiperPixelPreloader gridSize={10} color="#6366f1" speed={0.05} />',
    suggestedWith: ['skiper-stairs-preloader', 'skiper-words-preloader'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-progressive-blur',
    name: 'SkiperProgressiveBlur',
    displayName: 'Progressive Blur',
    source: 'skiper',
    categories: ['effect', 'overlay'],
    tags: ['blur', 'progressive', 'fade', 'overlay', 'backdrop'],
    description: 'Progressive backdrop blur effect that increases intensity toward a configurable edge direction.',
    previewImage: '',
    props: [
      { name: 'intensity', type: 'number', default: 10, required: false, description: 'Maximum blur intensity in pixels', group: 'style' },
      { name: 'direction', type: 'select', default: 'bottom', required: false, description: 'Blur direction', options: ['top', 'bottom', 'left', 'right'], group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-progressive-blur',
    level: 'effect',
    code: '<SkiperProgressiveBlur intensity={10} direction="bottom">{children}</SkiperProgressiveBlur>',
    suggestedWith: ['skiper-scroll-with-fade', 'skiper-parallax-scroll'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'skiper-projects-showcase',
    name: 'SkiperProjectsShowcase',
    displayName: 'Projects Showcase',
    source: 'skiper',
    categories: ['section', 'media'],
    tags: ['projects', 'portfolio', 'showcase', 'grid', 'hover'],
    description: 'Portfolio project grid with hover-triggered image zoom, overlay darkening, and animated category badges.',
    previewImage: '',
    props: [
      { name: 'projects', type: 'array', required: false, description: 'Array of projects with title, category, image, and link', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-projects-showcase',
    level: 'section',
    code: '<SkiperProjectsShowcase projects={[{ title: "Project", category: "Web", image: "/img.jpg", link: "#" }]} />',
    suggestedWith: ['skiper-hover-expand', 'skiper-apple-feature-block'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-rolling-text',
    name: 'SkiperRollingText',
    displayName: 'Rolling Text',
    source: 'skiper',
    categories: ['text', 'animation'],
    tags: ['rolling', 'marquee', 'text', 'infinite', 'scroll'],
    description: 'Continuously scrolling horizontal text marquee with configurable speed and direction.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Design with purpose. Build with passion. Ship with confidence.', required: false, description: 'Text to scroll', group: 'content' },
      { name: 'speed', type: 'number', default: 30, required: false, description: 'Scroll duration in seconds (higher = slower)', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, description: 'Scroll direction', options: ['left', 'right'], group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-rolling-text',
    level: 'primitive',
    code: '<SkiperRollingText text="Scrolling text here" speed={30} direction="left" />',
    suggestedWith: ['skiper-text-scroll-animation', 'skiper-horizontal-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-scroll-with-fade',
    name: 'SkiperScrollWithFade',
    displayName: 'Scroll With Fade',
    source: 'skiper',
    categories: ['layout', 'effect'],
    tags: ['scroll', 'fade', 'container', 'overflow', 'gradient'],
    description: 'Scrollable container with gradient fade overlays at the top, bottom, or both edges.',
    previewImage: '',
    props: [
      { name: 'fadeHeight', type: 'number', default: 80, required: false, description: 'Height of fade gradient in pixels', group: 'style' },
      { name: 'direction', type: 'select', default: 'both', required: false, description: 'Which edges to fade', options: ['top', 'bottom', 'both'], group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-scroll-with-fade',
    level: 'primitive',
    code: '<SkiperScrollWithFade fadeHeight={80} direction="both">{children}</SkiperScrollWithFade>',
    suggestedWith: ['skiper-progressive-blur', 'skiper-card-stack-scroll'],
    version: '1.0.0',
    acceptsChildren: true,
  },
  {
    id: 'skiper-stairs-preloader',
    name: 'SkiperStairsPreloader',
    displayName: 'Stairs Preloader',
    source: 'skiper',
    categories: ['animation', 'effect'],
    tags: ['stairs', 'preloader', 'loading', 'transition', 'columns'],
    description: 'Staircase-style page transition preloader with staggered column animations entering and exiting.',
    previewImage: '',
    props: [
      { name: 'steps', type: 'number', default: 5, required: false, description: 'Number of stair columns', group: 'behavior' },
      { name: 'color', type: 'color', default: '#6366f1', required: false, description: 'Stair column color', group: 'style' },
      { name: 'duration', type: 'number', default: 1.5, required: false, description: 'Animation cycle duration in seconds', group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-stairs-preloader',
    level: 'primitive',
    code: '<SkiperStairsPreloader steps={5} color="#6366f1" duration={1.5} />',
    suggestedWith: ['skiper-pixel-preloader', 'skiper-words-preloader'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-text-reveal-box',
    name: 'SkiperTextRevealBox',
    displayName: 'Text Reveal Box',
    source: 'skiper',
    categories: ['text', 'animation'],
    tags: ['text', 'reveal', 'scroll', 'opacity', 'word-by-word'],
    description: 'Scroll-driven text reveal where each word transitions from dim to bright as the user scrolls.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'We build digital experiences that push the boundaries...', required: false, description: 'Text to reveal', group: 'content' },
      { name: 'revealColor', type: 'color', default: '#ffffff', required: false, description: 'Revealed text color', group: 'style' },
      { name: 'backgroundColor', type: 'color', default: '#0a0a0a', required: false, description: 'Section background color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-text-reveal-box',
    level: 'section',
    code: '<SkiperTextRevealBox text="Reveal this text on scroll" revealColor="#ffffff" />',
    suggestedWith: ['skiper-horizontal-text-reveal', 'skiper-text-scroll-animation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-text-roll-navigation',
    name: 'SkiperTextRollNavigation',
    displayName: 'Text Roll Navigation',
    source: 'skiper',
    categories: ['navigation', 'animation'],
    tags: ['navigation', 'text-roll', 'hover', 'links', 'animated'],
    description: 'Navigation links with a vertical text rolling animation on hover, revealing a secondary label.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of nav items with label and href', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-text-roll-navigation',
    level: 'primitive',
    code: '<SkiperTextRollNavigation items={[{ label: "Home", href: "#" }, { label: "About", href: "#" }]} />',
    suggestedWith: ['skiper-apple-nav-bar', 'skiper-vercel-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-text-scroll-animation',
    name: 'SkiperTextScrollAnimation',
    displayName: 'Text Scroll Animation',
    source: 'skiper',
    categories: ['text', 'animation'],
    tags: ['text', 'scroll', 'horizontal', 'parallax', 'large'],
    description: 'Large repeated text that moves horizontally based on scroll position with opacity and scale transitions.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'Scroll to Animate', required: false, description: 'Text to animate', group: 'content' },
      { name: 'speed', type: 'number', default: 1, required: false, description: 'Movement speed multiplier', group: 'behavior' },
      { name: 'direction', type: 'select', default: 'left', required: false, description: 'Movement direction', options: ['left', 'right'], group: 'behavior' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-text-scroll-animation',
    level: 'section',
    code: '<SkiperTextScrollAnimation text="Animate Me" speed={1} direction="left" />',
    suggestedWith: ['skiper-rolling-text', 'skiper-horizontal-text-reveal'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-three-d-perspective-text',
    name: 'Skiper3DPerspectiveText',
    displayName: '3D Perspective Text',
    source: 'skiper',
    categories: ['text', 'effect'],
    tags: ['3d', 'perspective', 'text', 'depth', 'interactive'],
    description: 'Large text with mouse-following 3D perspective rotation and layered depth shadow effects.',
    previewImage: '',
    props: [
      { name: 'text', type: 'string', default: 'PERSPECTIVE', required: false, description: 'Text to display', group: 'content' },
      { name: 'depth', type: 'number', default: 10, required: false, description: 'Number of depth layers', group: 'style' },
      { name: 'color', type: 'color', default: '#ffffff', required: false, description: 'Text color', group: 'style' },
      { name: 'rotateX', type: 'number', default: 0, required: false, description: 'Initial X rotation offset', group: 'style' },
      { name: 'rotateY', type: 'number', default: 0, required: false, description: 'Initial Y rotation offset', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-three-d-perspective-text',
    level: 'primitive',
    code: '<Skiper3DPerspectiveText text="HELLO" depth={10} color="#ffffff" />',
    suggestedWith: ['skiper-horizontal-text-reveal', 'skiper-text-reveal-box'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-vercel-navigation',
    name: 'SkiperVercelNavigation',
    displayName: 'Vercel Navigation',
    source: 'skiper',
    categories: ['navigation', 'header'],
    tags: ['vercel', 'navigation', 'tabs', 'active-indicator', 'badge'],
    description: 'Vercel-style tabbed navigation bar with animated active indicator, hover effects, and badge support.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of nav items with label, href, and optional badge', group: 'content' },
      { name: 'logo', type: 'string', default: 'Vercel', required: false, description: 'Logo text', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-vercel-navigation',
    level: 'primitive',
    code: '<SkiperVercelNavigation logo="MyApp" items={[{ label: "Overview", href: "#" }]} />',
    suggestedWith: ['skiper-apple-nav-bar', 'skiper-text-roll-navigation'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-vercel-tooltip',
    name: 'SkiperVercelTooltip',
    displayName: 'Vercel Tooltip',
    source: 'skiper',
    categories: ['other', 'animation'],
    tags: ['tooltip', 'avatar', 'vercel', 'hover', 'team'],
    description: 'Overlapping avatar row with Vercel-style tooltips that appear on hover with spring animations.',
    previewImage: '',
    props: [
      { name: 'items', type: 'array', required: false, description: 'Array of tooltip items with name, image, and href', group: 'content' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-vercel-tooltip',
    level: 'primitive',
    code: '<SkiperVercelTooltip items={[{ name: "John", image: "/avatar.jpg", href: "#" }]} />',
    suggestedWith: ['skiper-hover-members', 'skiper-dynamic-island'],
    version: '1.0.0',
    acceptsChildren: false,
  },
  {
    id: 'skiper-words-preloader',
    name: 'SkiperWordsPreloader',
    displayName: 'Words Preloader',
    source: 'skiper',
    categories: ['animation', 'effect'],
    tags: ['words', 'preloader', 'loading', 'transition', 'text'],
    description: 'Word-cycling preloader that animates through a list of words with blur transitions and a progress bar.',
    previewImage: '',
    props: [
      { name: 'words', type: 'array', default: ['Design', 'Create', 'Build', 'Ship', 'Iterate'], required: false, description: 'Words to cycle through', group: 'content' },
      { name: 'speed', type: 'number', default: 0.8, required: false, description: 'Time per word in seconds', group: 'behavior' },
      { name: 'backgroundColor', type: 'color', default: '#000000', required: false, description: 'Background color', group: 'style' },
      { name: 'textColor', type: 'color', default: '#ffffff', required: false, description: 'Text color', group: 'style' },
      { name: 'className', type: 'string', required: false, description: 'Additional CSS classes', group: 'style' },
    ],
    dependencies: ['framer-motion'],
    modulePath: 'skiper-words-preloader',
    level: 'primitive',
    code: '<SkiperWordsPreloader words={["Design", "Build", "Ship"]} speed={0.8} />',
    suggestedWith: ['skiper-pixel-preloader', 'skiper-stairs-preloader'],
    version: '1.0.0',
    acceptsChildren: false,
  },
]
