#!/usr/bin/env tsx
/**
 * Generate UI Source Map
 * Creates a TypeScript module with all UI component source code embedded as strings.
 * Used by the export engine for client-side ZIP generation.
 * 
 * Usage: npx tsx scripts/generate-ui-source-map.ts
 */

import fs from 'fs'
import path from 'path'

async function main() {
  const uiDir = path.join(process.cwd(), 'components', 'ui')
  const outputPath = path.join(process.cwd(), 'lib', 'export', 'ui-source-map.ts')

  const files = fs.readdirSync(uiDir).filter(f => f.endsWith('.tsx') || f.endsWith('.ts'))

  let output = '// Auto-generated by scripts/generate-ui-source-map.ts\n'
  output += '// Do not edit manually\n\n'
  output += 'export const UI_SOURCE_MAP: Record<string, string> = {\n'

  for (const file of files) {
    const content = fs.readFileSync(path.join(uiDir, file), 'utf-8')
    const escaped = content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$')
    output += `  '${file}': \`${escaped}\`,\n`
  }

  output += '}\n'

  fs.writeFileSync(outputPath, output)
  console.log(`Generated UI source map with ${files.length} components at ${outputPath}`)
}

main().catch(console.error)
